In [18]:
import pandas as pd
file_path = './data/countries_affiliation_df_canada.csv'  # Replace with your actual file path
canada_df = pd.read_csv(file_path)

In [23]:
canada_df.iloc[0]["PMID"]

28350526

In [141]:
import os
import shutil
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import time

class MyHandler(FileSystemEventHandler):
    def __init__(self, download_folder, pmid):
        self.download_folder = download_folder
        self.pmid = pmid
        self.downloaded_file_path = None

    def on_created(self, event):
        if not event.is_directory and event.src_path.endswith('.pdf'):
            self.downloaded_file_path = event.src_path
            print(f"New file detected: {event.src_path}")

    def get_downloaded_file_path(self):
        return self.downloaded_file_path

# Paths
chrome_driver_path = "/opt/homebrew/bin/chromedriver"  # Adjust this path to where you placed the chromedriver
download_folder = "/Users/yumcoder/Desktop/pubmed/download"  # Replace with your desired download folder path
# cookies_file = 'cookies.json'

def initialize_driver():
    service = Service(chrome_driver_path)
    options = webdriver.ChromeOptions()

    # Set the download folder for Chrome
    prefs = {
        "download.default_directory": download_folder,  # Change default directory for downloads
        "download.prompt_for_download": False,       # To auto download the file
        "plugins.always_open_pdf_externally": True,   # To disable PDF viewer and download the file directly
        "profile.default_content_setting_values.automatic_downloads": 1,
    }
    options.add_experimental_option("prefs", prefs)

    driver = webdriver.Chrome(service=service, options=options)

    # driver = webdriver.Safari()
    return driver

def login_and_save_cookies(driver):
    # Open the login page and perform login
    driver.get("https://pubmed-ncbi-nlm-nih-gov.myaccess.library.utoronto.ca/")
    
    # Wait for login elements and perform login (pseudo-code; adjust based on actual login process)
    wait = WebDriverWait(driver, 10)
    login_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "a.loginButton")))
    login_button.click()
     # Wait for the UTORid login page to appear
    WebDriverWait(driver, 10).until(EC.url_contains("utoronto.ca"))

    # Fill in the login form
    # Assuming you need to enter username and password and then click a login button
    # Adjust the locators and fields based on the actual UTORid login page structure
    username_field = wait.until(EC.presence_of_element_located((By.ID, "username")))
    password_field = wait.until(EC.presence_of_element_located((By.ID, "password")))
    submit_button = wait.until(EC.element_to_be_clickable((By.ID, "login-btn")))  # Adjust ID as needed
    username_field.send_keys("jafarin9")  # Replace with your actual username
    password_field.send_keys("=YumUofT2023!")  # Replace with your actual password
    submit_button.click()

    # Wait for the 'trust-browser-button' to appear and click it
    trust_browser_button = wait.until(EC.element_to_be_clickable((By.ID, "trust-browser-button")))
    trust_browser_button.click()
    # Wait for login to complete and save cookies
    WebDriverWait(driver, 30).until(EC.url_contains("https://pubmed-ncbi-nlm-nih-gov.myaccess.library.utoronto.ca/"))
    # id="trust-browser-button"

    # cookies = driver.get_cookies()
    # with open(cookies_file, 'w') as file:
    #     json.dump(cookies, file)
    # # print("Cookies saved.")

# def load_cookies(driver):
#     # Load cookies and add them to the browser
#     driver.get("https://pubmed-ncbi-nlm-nih-gov.myaccess.library.utoronto.ca/")
#     with open(cookies_file, 'r') as file:
#         cookies = json.load(file)
#     for cookie in cookies:
#         driver.add_cookie(cookie)

def download_pdfs(driver, pmid_list):
    # Loop through each PMID
    for index, row in pmid_list.iterrows():
        pmid = row['PMID']
        # if index > 20:
        #     break

        pdf_filename = os.path.join(download_folder, f"{pmid}.pdf")
        
        if os.path.exists(pdf_filename):
            print(f"File {pdf_filename} already exists, skipping...")
            continue

        try:
            # Open the PubMed article page
            driver.get(f"https://pubmed-ncbi-nlm-nih-gov.myaccess.library.utoronto.ca/{pmid}/")

            # Wait for the page to load and the full-text links to be visible
            wait = WebDriverWait(driver, 10)
            wait.until(EC.presence_of_element_located((By.CLASS_NAME, "full-text-links-list")))

            try:
                # Find all full-text links
                links = wait.until(EC.presence_of_all_elements_located((By.XPATH, "//div[@class='full-text-links-list']/a")))
                
                # Try each link until a successful download occurs
                download_successful = False
                for link in links:
                    link_text = link.get_attribute('textContent').strip()
                    link_href = link.get_attribute('href')
                    print(f"Trying link text: {link_text}")
                    print(f"Trying link href: {link_href}")
                    
                    # Click on the link
                    link.click()
                    
                    # Switch to the new tab if it opens
                    window_handles = driver.window_handles
                    if len(window_handles) > 1:
                        driver.switch_to.window(window_handles[-1])
                    else:
                        print("No new tab detected, continuing in the current tab.")


                    # Wait for the new page or current page to load the PDF link
                    wait.until(EC.presence_of_element_located((By.XPATH, "//a[text()='Download PDF'] | //*[contains(@href, '.pdf') or contains(@class, 'pdf') or contains(@data-article-pdf, 'pdf') or contains(@data-test, 'pdf') or contains(@data-download, 'pdf')]")))

                    # Attempt to find PDF link using multiple locators
                    pdf_links = driver.find_elements(By.XPATH, "//a[text()='Download PDF'] | //*[contains(@href, '.pdf') or contains(@class, 'pdf') or contains(@data-article-pdf, 'pdf') or contains(@data-test, 'pdf') or contains(@data-download, 'pdf')]")
                    # print('---pdf_links--->>>', [f.get_attribute("href") for f in pdf_links])
                    # Download the first valid PDF link found
                    for pdf_link in pdf_links:
                        pdf_url = pdf_link.get_attribute("href")
                       
                        if pdf_url and "www-sciencedirect-com" not in pdf_url.lower():
                            print(f"Found PDF link: {pdf_url}")
                           
                            if pdf_url.lower().endswith(".pdf"):
                                try:
                                    # Set up watchdog to monitor the download folder
                                    handler = MyHandler(download_folder, pmid)
                                    observer = Observer()
                                    observer.schedule(handler, download_folder, recursive=False)
                                    observer.start()
                                    print(f"Watching folder: {download_folder}")
                                    driver.get(pdf_url)

                                    # Wait for the file to appear and handle it
                                    while handler.get_downloaded_file_path() is None:
                                        time.sleep(1)
                                    
                                    downloaded_file_path = handler.get_downloaded_file_path()
                                    shutil.move(downloaded_file_path, pdf_filename)
                                    # download_button.click()
                                    # time.sleep(60)  # Wait for the download to complete
                                    download_successful = True
                                    break
                                finally:
                                    observer.stop()
                                    observer.join()


                            driver.get(pdf_url)  # Navigate to the PDF link to trigger download
                            driver.switch_to.window(driver.window_handles[-1])
                            #  | 
                            download_button = wait.until(EC.presence_of_element_located(
                                (By.XPATH, "//a[contains(@class, 'navbar-download') and contains(@href, 'download=true')]")
                            ))
                            if download_button:
                                # print("The element is a link.")
                                # Taylor & Francis
                                try:
                                    pdf_url_download_link = download_button.get_attribute("href")
                                    # Set up watchdog to monitor the download folder
                                    handler = MyHandler(download_folder, pmid)
                                    observer = Observer()
                                    observer.schedule(handler, download_folder, recursive=False)
                                    observer.start()
                                    print(f"Watching folder: {download_folder}")

                                    driver.get(pdf_url_download_link)
                                    driver.switch_to.window(driver.window_handles[-1])
                                    # Wait for the file to appear and handle it
                                    while handler.get_downloaded_file_path() is None:
                                        time.sleep(1)
                                    
                                    downloaded_file_path = handler.get_downloaded_file_path()
                                    shutil.move(downloaded_file_path, pdf_filename)
                                    # download_button.click()
                                    # time.sleep(60)  # Wait for the download to complete
                                    download_successful = True
                                    break
                                finally:
                                    driver.close()
                                    driver.switch_to.window(driver.window_handles[0])
                                    observer.stop()
                                    observer.join()

                    # Close the tab and switch back to the original tab if a new tab was opened
                    if len(driver.window_handles) > 1:
                        driver.close()
                        driver.switch_to.window(driver.window_handles[0])

                    if download_successful:
                        break  # Exit the link loop if successful

            except Exception as e:
                print(f"Full-text links not found for PMID: {pmid}: {e}")
        
        except Exception as e:
            print(f"An error occurred for PMID {pmid}: {e}")

def main():
    # Load PMIDs from the CSV file
    df_data = pd.read_csv('canada_pmid.csv', header=None, names=['PMID'])

    driver = initialize_driver()
    
    try:
        login_and_save_cookies(driver)

        # Perform the download
        download_pdfs(driver, df_data)

        time.sleep(600)
    finally:
        # Close the browser
        driver.quit()

if __name__ == "__main__":
    main()

SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /Applications/Google Chrome.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
0   chromedriver                        0x0000000102919024 cxxbridge1$str$ptr + 1887276
1   chromedriver                        0x0000000102911700 cxxbridge1$str$ptr + 1856264
2   chromedriver                        0x000000010252082c cxxbridge1$string$len + 88524
3   chromedriver                        0x0000000102551ad0 cxxbridge1$string$len + 289904
4   chromedriver                        0x000000010254d890 cxxbridge1$string$len + 272944
5   chromedriver                        0x000000010258c82c cxxbridge1$string$len + 530892
6   chromedriver                        0x0000000102559474 cxxbridge1$string$len + 321044
7   chromedriver                        0x000000010255a0e4 cxxbridge1$string$len + 324228
8   chromedriver                        0x00000001028e0a08 cxxbridge1$str$ptr + 1656336
9   chromedriver                        0x00000001028e5464 cxxbridge1$str$ptr + 1675372
10  chromedriver                        0x00000001028c68ec cxxbridge1$str$ptr + 1549556
11  chromedriver                        0x00000001028e5c14 cxxbridge1$str$ptr + 1677340
12  chromedriver                        0x00000001028b85fc cxxbridge1$str$ptr + 1491460
13  chromedriver                        0x0000000102902a5c cxxbridge1$str$ptr + 1795684
14  chromedriver                        0x0000000102902bd8 cxxbridge1$str$ptr + 1796064
15  chromedriver                        0x0000000102911334 cxxbridge1$str$ptr + 1855292
16  libsystem_pthread.dylib             0x000000019c846f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000019c841d34 thread_start + 8

In [144]:
! pip install webdriver-manager

275552.27s - pydevd: Sending message related to process being replaced timed-out after 5 seconds
Collecting webdriver-manager
  Using cached webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from webdriver-manager) (2.32.2)
Requirement already satisfied: python-dotenv in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: packaging in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from webdriver-manager) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests->webdriver-manager) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests->webdriver-manager) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests->webdriver-manager) (2024.6.2)
Using cached webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.2

In [41]:
! pip install pyperclip

Collecting pyperclip
  Downloading pyperclip-1.9.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyperclip
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.9.0-py3-none-any.whl size=11002 sha256=2bae6a68fbdfea549a91b2cff024fb1e61085f4d274aa6f298b027b75764830f
  Stored in directory: /Users/yumcoder/Library/Caches/pip/wheels/e0/e8/fc/8ab8aa326e33bc066ccd5f3ca9646eab4299881af933f94f09
Successfully built pyperclip
Installing collected packages: pyperclip
Successfully installed pyperclip-1.9.0

In [43]:
from selenium import webdriver
import pyperclip
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.common.keys import Keys
import os

def initialize_driver():
    """
    Initialize the Chrome WebDriver with specified options and service.
    """
    options = Options()
    # options.add_argument("--headless")  # Ensure GUI is off
    # options.add_argument("--no-sandbox")
    # options.add_argument("--disable-dev-shm-usage")

    service = Service("/opt/homebrew/bin/chromedriver")  # Adjust the path if needed
    driver = webdriver.Chrome(service=service, options=options)
    return driver

def fill_textarea(driver, wait, title, pmid):
    """
    Fill the last textarea found on the page with the specified text.
    """
    try:
        # Wait until the textarea is clickable
        textarea = wait.until(EC.element_to_be_clickable((By.XPATH, "//textarea[last()]")))
        textarea.clear()
        # Part 1
        textarea.send_keys("Given the provided academic paper:")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # Another new line
        textarea.send_keys(f"- **{title}**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line

        textarea.send_keys(f"- **PMID (PubMed)**: {pmid}")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # Another new line
        
        textarea.send_keys("extract and return the following information in JSON format:")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line

        # Part 2
        textarea.send_keys("1. **Patient Level Data:** A boolean value indicating whether the paper works on patient-level data.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        textarea.send_keys("2. **Institutions Involved:** A list of institutions that participated in the data collection process.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        textarea.send_keys("3. **Countries:** A list of countries associated with the institutions that participated in data collection.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        textarea.send_keys("4. **Data Collection Approach:** A string indicating whether the data was collected in a central repository (\"central\") or in a distributed manner (\"distributed\").")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        textarea.send_keys("5. **Total Dataset Size:** The exact count of individual records or samples.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("6. **pmid:** PubMed id.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        # Part 3
        textarea.send_keys("**Expected/Example of JSON format:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        textarea.send_keys("```json")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        textarea.send_keys("{")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys('  "patient_level_data": true,')
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys('  "institutions_involved": ["Institution A", "Institution B"],')
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys('  "countries": ["Country X", "Country Y"],')
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys('  "data_collection_approach": "central",')
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys('  "total_dataset_size": 1')
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys('  "pmid": 28589480')
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("}")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("```")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        # Part 4
        textarea.send_keys("Please analyze the paper and return ONLY the JSON object accordingly without any additional text; I mean only JSON should be in the result.")
        

        print("Text filled in the textarea.")
        textarea.send_keys(Keys.ENTER) #submit
    except Exception as e:
        print(f"Error filling textarea: {e}")

def click_copy_button(driver, wait):
    """
    Scroll to the button with a clipboard icon and click it to copy the response.
    """
    try:
        # Wait for the SVG element
        clipboard_svg = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "svg[data-icon='clipboard']")))

        # Get the parent button
        copy_button = clipboard_svg.find_element(By.XPATH, './ancestor::button')
        #print('copy_button>>>', copy_button)

        # Scroll the element into view
        driver.execute_script("arguments[0].scrollIntoView(true);", copy_button)
        #driver.save_screenshot('before_click.png')

        # Wait until the button is clickable
        # copy_button.click()
        driver.execute_script("arguments[0].click();", copy_button)

        print("Copy button clicked.")
    except Exception as e:
        print(f"Error clicking copy button: {e}")

def main():
    driver = initialize_driver()
    wait = WebDriverWait(driver, 10)  # Wait up to 10 seconds

    # data = [
    #     {
    #         "title": "Preliminary testing by adults of a haptics-assisted robot platform designed for children with physical impairments to access play",
    #         "pmid": 28696831
    #     },
    #     {
    #         "title": "Dark Flow, Depression and Multiline Slot Machine Play",
    #         "pmid": 28589480
    #     }
    # ]

    try:
        file_path = './data/countries_affiliation_df_canada.csv'  # Replace with your actual file path
        canada_df = pd.read_csv(file_path)
        print(f"len:{len(canada_df)}")
        driver.get("https://www.perplexity.ai/")
        original_window = driver.current_window_handle  # Store the handle of the original window
        input("Press any key to continue...")

        # for entry in data:
        for index, entry in canada_df.iterrows():
            # body = driver.find_element(By.TAG_NAME, 'body')
            # body.send_keys(Keys.COMMAND + 'k')  # For macOS

            # title = entry["title"]
            # pmid = entry["pmid"]
            title = entry["ArticleTitle"]
            pmid = entry["PMID"]

            # Check if file already exists
            filename = f"./perplexity/{pmid}.txt"
            if os.path.exists(filename):
                print(f"File {filename} already exists. Skipping...")
                continue  # Skip to the next iteration

            # Open a new tab and switch to it
            driver.execute_script("window.open('');")
            new_tab = driver.window_handles[-1]
            driver.switch_to.window(new_tab)

            # Load the page in the new tab
            driver.get("https://www.perplexity.ai/")

            fill_textarea(driver, wait, title, pmid)

            click_copy_button(driver, wait)

            # Allow time for the clipboard to update
            time.sleep(1)

            # Retrieve the string from the clipboard and print it
            clipboard_content = pyperclip.paste()
            print(f"Clipboard Content for PMID {pmid}:\n", clipboard_content)

            # Save the result to a file
            with open(filename, "w") as file:
                file.write(clipboard_content)

            # Close the new tab and switch back to the original tab
            driver.close()
            driver.switch_to.window(original_window)

    finally:
        # Ensure the driver is properly closed even if an error occurs
        driver.quit()

if __name__ == "__main__":
    main()

len:7756
File ./perplexity/28350526.txt already exists. Skipping...
File ./perplexity/28444633.txt already exists. Skipping...
File ./perplexity/28550657.txt already exists. Skipping...
File ./perplexity/28589480.txt already exists. Skipping...
File ./perplexity/28596271.txt already exists. Skipping...
File ./perplexity/28601499.txt already exists. Skipping...
File ./perplexity/28651909.txt already exists. Skipping...
File ./perplexity/28673115.txt already exists. Skipping...
File ./perplexity/28687962.txt already exists. Skipping...
File ./perplexity/28696831.txt already exists. Skipping...
File ./perplexity/28712346.txt already exists. Skipping...
File ./perplexity/28722148.txt already exists. Skipping...
File ./perplexity/28726811.txt already exists. Skipping...
File ./perplexity/28756487.txt already exists. Skipping...
File ./perplexity/28771699.txt already exists. Skipping...
File ./perplexity/28836083.txt already exists. Skipping...
File ./perplexity/28836836.txt already exists. Skipping...
File ./perplexity/28853237.txt already exists. Skipping...
File ./perplexity/28869436.txt already exists. Skipping...
File ./perplexity/28948655.txt already exists. Skipping...
File ./perplexity/28952798.txt already exists. Skipping...
File ./perplexity/28968847.txt already exists. Skipping...
File ./perplexity/28981875.txt already exists. Skipping...
File ./perplexity/28987903.txt already exists. Skipping...
File ./perplexity/29042099.txt already exists. Skipping...
File ./perplexity/29043544.txt already exists. Skipping...
File ./perplexity/29045814.txt already exists. Skipping...
File ./perplexity/29045911.txt already exists. Skipping...
File ./perplexity/29058118.txt already exists. Skipping...
File ./perplexity/29059324.txt already exists. Skipping...
File ./perplexity/29065782.txt already exists. Skipping...
File ./perplexity/29066576.txt already exists. Skipping...
File ./perplexity/29069413.txt already exists. Skipping...
File ./perplexity/29071211.txt already exists. Skipping...
File ./perplexity/29084099.txt already exists. Skipping...
File ./perplexity/29092082.txt already exists. Skipping...
File ./perplexity/29094375.txt already exists. Skipping...
File ./perplexity/29095574.txt already exists. Skipping...
File ./perplexity/29098645.txt already exists. Skipping...
File ./perplexity/29128490.txt already exists. Skipping...
File ./perplexity/29134430.txt already exists. Skipping...
File ./perplexity/29145629.txt already exists. Skipping...
File ./perplexity/29152876.txt already exists. Skipping...
File ./perplexity/29165610.txt already exists. Skipping...
File ./perplexity/29169029.txt already exists. Skipping...
File ./perplexity/29186351.txt already exists. Skipping...
File ./perplexity/29187508.txt already exists. Skipping...
File ./perplexity/29190576.txt already exists. Skipping...
File ./perplexity/29193460.txt already exists. Skipping...
File ./perplexity/29194610.txt already exists. Skipping...
File ./perplexity/29205792.txt already exists. Skipping...
File ./perplexity/29211476.txt already exists. Skipping...
File ./perplexity/29220306.txt already exists. Skipping...
File ./perplexity/29221873.txt already exists. Skipping...
File ./perplexity/29226512.txt already exists. Skipping...
File ./perplexity/29232649.txt already exists. Skipping...
File ./perplexity/29233605.txt already exists. Skipping...
File ./perplexity/29237237.txt already exists. Skipping...
File ./perplexity/29239117.txt already exists. Skipping...
File ./perplexity/29244479.txt already exists. Skipping...
File ./perplexity/29244902.txt already exists. Skipping...
File ./perplexity/29249050.txt already exists. Skipping...
File ./perplexity/29251172.txt already exists. Skipping...
File ./perplexity/29254878.txt already exists. Skipping...
File ./perplexity/29268169.txt already exists. Skipping...
File ./perplexity/29272464.txt already exists. Skipping...
File ./perplexity/29274736.txt already exists. Skipping...
File ./perplexity/29283934.txt already exists. Skipping...
File ./perplexity/29288983.txt already exists. Skipping...
File ./perplexity/29289761.txt already exists. Skipping...
File ./perplexity/29292137.txt already exists. Skipping...
File ./perplexity/29293692.txt already exists. Skipping...
File ./perplexity/29294157.txt already exists. Skipping...
File ./perplexity/29299640.txt already exists. Skipping...
File ./perplexity/29300432.txt already exists. Skipping...
File ./perplexity/29304138.txt already exists. Skipping...
File ./perplexity/29304373.txt already exists. Skipping...
File ./perplexity/29306756.txt already exists. Skipping...
File ./perplexity/29306928.txt already exists. Skipping...
File ./perplexity/29316091.txt already exists. Skipping...
File ./perplexity/29318397.txt already exists. Skipping...
File ./perplexity/29321174.txt already exists. Skipping...
File ./perplexity/29321970.txt already exists. Skipping...
File ./perplexity/29332401.txt already exists. Skipping...
File ./perplexity/29334038.txt already exists. Skipping...
File ./perplexity/29334467.txt already exists. Skipping...
File ./perplexity/29335008.txt already exists. Skipping...
File ./perplexity/29335608.txt already exists. Skipping...
File ./perplexity/29336922.txt already exists. Skipping...
File ./perplexity/29339407.txt already exists. Skipping...
File ./perplexity/29340580.txt already exists. Skipping...
File ./perplexity/29344313.txt already exists. Skipping...
File ./perplexity/29346029.txt already exists. Skipping...
File ./perplexity/29346286.txt already exists. Skipping...
File ./perplexity/29351240.txt already exists. Skipping...
File ./perplexity/29351281.txt already exists. Skipping...
File ./perplexity/29354080.txt already exists. Skipping...
File ./perplexity/29355792.txt already exists. Skipping...
File ./perplexity/29356281.txt already exists. Skipping...
File ./perplexity/29356346.txt already exists. Skipping...
File ./perplexity/29358700.txt already exists. Skipping...
File ./perplexity/29363423.txt already exists. Skipping...
File ./perplexity/29369637.txt already exists. Skipping...
File ./perplexity/29375612.txt already exists. Skipping...
File ./perplexity/29375647.txt already exists. Skipping...
File ./perplexity/29377156.txt already exists. Skipping...
File ./perplexity/29377902.txt already exists. Skipping...
File ./perplexity/29378522.txt already exists. Skipping...
File ./perplexity/29379444.txt already exists. Skipping...
File ./perplexity/29380275.txt already exists. Skipping...
File ./perplexity/29381440.txt already exists. Skipping...
File ./perplexity/29382744.txt already exists. Skipping...
File ./perplexity/29383883.txt already exists. Skipping...
File ./perplexity/29385611.txt already exists. Skipping...
File ./perplexity/29385842.txt already exists. Skipping...
File ./perplexity/29387152.txt already exists. Skipping...
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29391513:
 nw64t-dwghy

Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29397059:
 ```json
{
  "patient_level_data": false,
  "institutions_involved": ["California Department of Transportation"],
  "countries": ["United States"],
  "data_collection_approach": "central",
  "total_dataset_size": 1000,
  "pmid": 29397059
}
```

Citations:
[1] https://pubmed.ncbi.nlm.nih.gov/29397059/
[2] https://pubmed.ncbi.nlm.nih.gov/26687540/
[3] https://www.researchgate.net/publication/322835825_Modeling_When_and_Where_a_Secondary_Accident_Occurs
[4] https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0295343
[5] https://www.researchgate.net/publication/286640136_Modeling_secondary_accidents_identified_by_traffic_shock_waves
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29398207:
 ```json
{
  "patient_level_data": true,
  "institutions_involved": [],
  "countries": [],
  "data_collection_approach": "distributed",
  "total_dataset_size": 0,
  "pmid": 29398207
}
```

Citations:
[1] https://www.sciencedirect.com/science/article/pii/S0920996418300264
[2] https://pubmed.ncbi.nlm.nih.gov/29398207/
[3] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7468123/
[4] https://www.nature.com/articles/s41593-023-01404-6
[5] https://academic.oup.com/schizbullopen/article/1/1/sgaa056/5939751
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29407288:
 ```json
{
  "patient_level_data": true,
  "institutions_involved": ["McMaster University"],
  "countries": ["Canada"],
  "data_collection_approach": "central",
  "total_dataset_size": 186,
  "pmid": 29407288
}
```

Citations:
[1] https://www.sciencedirect.com/science/article/pii/S0022395617306945
[2] https://www.sciencedirect.com/science/article/abs/pii/S0022395617306945
[3] https://experts.mcmaster.ca/display/publication1543207
[4] https://europepmc.org/article/med/29407288
[5] https://www.researchgate.net/publication/332028282_GWAS-BASED_MACHINE_LEARNING_APPROACH_TO_PREDICT_DULOXETINE_RESPONSE_AND_REMISSION_IN_MAJOR_DEPRESSIVE_DISORDER
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29411379:
 ```json
{
  "patient_level_data": true,
  "institutions_involved": ["McMaster University"],
  "countries": ["Canada"],
  "data_collection_approach": "central",
  "total_dataset_size": 186,
  "pmid": 29407288
}
```

Citations:
[1] https://www.sciencedirect.com/science/article/pii/S0022395617306945
[2] https://www.sciencedirect.com/science/article/abs/pii/S0022395617306945
[3] https://experts.mcmaster.ca/display/publication1543207
[4] https://europepmc.org/article/med/29407288
[5] https://www.researchgate.net/publication/332028282_GWAS-BASED_MACHINE_LEARNING_APPROACH_TO_PREDICT_DULOXETINE_RESPONSE_AND_REMISSION_IN_MAJOR_DEPRESSIVE_DISORDER
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29426290:
 ```json
{
  "patient_level_data": false,
  "institutions_involved": ["Maize Research Institute, Sichuan Agricultural University"],
  "countries": ["China"],
  "data_collection_approach": "distributed",
  "total_dataset_size": 1255,
  "pmid": 29426290
}
```

Citations:
[1] https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4513-4
[2] https://pubmed.ncbi.nlm.nih.gov/29426290/
[3] https://www.sciencedirect.com/science/article/pii/S2214514119301187
[4] https://www.semanticscholar.org/paper/Transcriptome-profiling-of-two-maize-inbreds-with-Kebede-Johnston/a84313b8dca00287ed5cb26d1bf3b69cfe868226
[5] https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE92448
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29429021:
 ```json
{
  "patient_level_data": false,
  "institutions_involved": [],
  "countries": [],
  "data_collection_approach": "central",
  "total_dataset_size": 0,
  "pmid": 29429021
}
```

Citations:
[1] https://link.springer.com/article/10.1007/s10661-018-6508-7
[2] https://pubmed.ncbi.nlm.nih.gov/29429021/
[3] https://www.researchgate.net/publication/323106897_Ozonation_of_offshore_produced_water_kinetic_study_and_fuzzy_inference_system_modeling
[4] https://ouci.dntb.gov.ua/en/works/lm5vZ0Ql/
[5] https://search.ebscohost.com/login.aspx?AN=128379249&authtype=crawler&crl=c&direct=true&h=Pay6g3DlTIGc6opyXfOOKH4L6K5yjmb6UIfYh70ZLTP4Xx8ka9zyes5KtDFipebS%2BP7onc9Bqcgr8bG9sLle%2Fg%3D%3D&jrnl=01676369&profile=ehost&scope=site
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29432581:
 ```json
{
  "patient_level_data": false,
  "institutions_involved": [],
  "countries": [],
  "data_collection_approach": "central",
  "total_dataset_size": 0,
  "pmid": 29429021
}
```

Citations:
[1] https://link.springer.com/article/10.1007/s10661-018-6508-7
[2] https://pubmed.ncbi.nlm.nih.gov/29429021/
[3] https://www.researchgate.net/publication/323106897_Ozonation_of_offshore_produced_water_kinetic_study_and_fuzzy_inference_system_modeling
[4] https://ouci.dntb.gov.ua/en/works/lm5vZ0Ql/
[5] https://search.ebscohost.com/login.aspx?AN=128379249&authtype=crawler&crl=c&direct=true&h=Pay6g3DlTIGc6opyXfOOKH4L6K5yjmb6UIfYh70ZLTP4Xx8ka9zyes5KtDFipebS%2BP7onc9Bqcgr8bG9sLle%2Fg%3D%3D&jrnl=01676369&profile=ehost&scope=site
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29441361:
 ```json
{
  "patient_level_data": false,
  "institutions_involved": [
    "Scripps Research Institute",
    "University of California San Diego",
    "University of Ottawa"
  ],
  "countries": [
    "USA",
    "Canada"
  ],
  "data_collection_approach": "distributed",
  "total_dataset_size": 0,
  "pmid": 29441361
}
```

Citations:
[1] https://pubmed.ncbi.nlm.nih.gov/29441361/
[2] https://www.science.org/doi/10.1126/sciadv.aao3424
[3] https://www.science.org/doi/abs/10.1126/sciadv.aao3424
[4] https://www.researchgate.net/publication/323008376_Increased_proteomic_complexity_in_Drosophila_hybrids_during_development
[5] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5810618/
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29441527:
 ```json
{
  "patient_level_data": false,
  "institutions_involved": [
    "Utah State University",
    "McGill University",
    "Université du Québec à Montréal",
    "Harvard University",
    "Universidad de Alcalá"
  ],
  "countries": [
    "USA",
    "Canada",
    "Spain"
  ],
  "data_collection_approach": "distributed",
  "total_dataset_size": 578,
  "pmid": 29441527
}
```

Citations:
[1] https://pubmed.ncbi.nlm.nih.gov/29441527/
[2] https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=1032&context=eco_pubs
[3] https://europepmc.org/authors/0000-0002-9600-4473
[4] https://www.researchgate.net/publication/323171388_Global_macroevolution_and_macroecology_of_passerine_song
[5] https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0278522
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29450848:
 ```json
{
  "patient_level_data": true,
  "institutions_involved": ["Institution A", "Institution B"],
  "countries": ["Country X", "Country Y"],
  "data_collection_approach": "central",
  "total_dataset_size": 1000,
  "pmid": 29450848
}
```

Citations:
[1] https://pubmed.ncbi.nlm.nih.gov/29450848/
[2] http://www.digitalimaginggroup.ca/members/Shuo/PathogenesisSpine.pdf
[3] https://www.researchgate.net/publication/323211412_Automated_Pathogenesis-Based_Diagnosis_of_Lumbar_Neural_Foraminal_Stenosis_via_Deep_Multiscale_Multitask_Learning
[4] https://www.semanticscholar.org/paper/Automated-Pathogenesis-Based-Diagnosis-of-Lumbar-Han-Wei/a05b7a206c86b3928746cce935f6f85d534a43cd
[5] https://ouci.dntb.gov.ua/en/works/4Nba1XV4/
Text filled in the textarea.
Copy button clicked.
Clipboard Content for PMID 29454222:
 ```json
{
  "patient_level_data": true,
  "institutions_involved": ["Department of Psychiatry"],
  "countries": ["Not specified"],
  "data_collection_approach": "distributed",
  "total_dataset_size": 183,
  "pmid": 29454222
}
```

Citations:
[1] https://www.sciencedirect.com/science/article/pii/S0022395617312141
[2] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8530396/
[3] https://www.researchgate.net/publication/323083117_Obesity_dyslipidemia_and_brain_age_in_first-episode_psychosis
[4] https://www.semanticscholar.org/paper/Obesity%2C-dyslipidemia-and-brain-age-in-psychosis.-Koleni%C4%8D-Franke/f9920c684e5da8baa8a8e756bc816cd1d9c5924d
[5] https://www.nature.com/articles/s41380-022-01616-5
Text filled in the textarea.
Error clicking copy button: Message:
Stacktrace:
0   chromedriver                        0x000000010328d024 cxxbridge1$str$ptr + 1887276
1   chromedriver                        0x0000000103285700 cxxbridge1$str$ptr + 1856264
2   chromedriver                        0x0000000102e9482c cxxbridge1$string$len + 88524
3   chromedriver                        0x0000000102ed8834 cxxbridge1$string$len + 367060
4   chromedriver                        0x0000000102f1048c cxxbridge1$string$len + 595500
5   chromedriver                        0x0000000102ecd474 cxxbridge1$string$len + 321044
6   chromedriver                        0x0000000102ece0e4 cxxbridge1$string$len + 324228
7   chromedriver                        0x0000000103254a08 cxxbridge1$str$ptr + 1656336
8   chromedriver                        0x0000000103259464 cxxbridge1$str$ptr + 1675372
9   chromedriver                        0x000000010323a8ec cxxbridge1$str$ptr + 1549556
10  chromedriver                        0x0000000103259c14 cxxbridge1$str$ptr + 1677340
11  chromedriver                        0x000000010322c5fc cxxbridge1$str$ptr + 1491460
12  chromedriver                        0x0000000103276a5c cxxbridge1$str$ptr + 1795684
13  chromedriver                        0x0000000103276bd8 cxxbridge1$str$ptr + 1796064
14  chromedriver                        0x0000000103285334 cxxbridge1$str$ptr + 1855292
15  libsystem_pthread.dylib             0x0000000194cb5f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000194cb0d34 thread_start + 8

Clipboard Content for PMID 29454542:
 ```json
{
  "patient_level_data": true,
  "institutions_involved": ["Department of Psychiatry"],
  "countries": ["Not specified"],
  "data_collection_approach": "distributed",
  "total_dataset_size": 183,
  "pmid": 29454222
}
```

Citations:
[1] https://www.sciencedirect.com/science/article/pii/S0022395617312141
[2] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8530396/
[3] https://www.researchgate.net/publication/323083117_Obesity_dyslipidemia_and_brain_age_in_first-episode_psychosis
[4] https://www.semanticscholar.org/paper/Obesity%2C-dyslipidemia-and-brain-age-in-psychosis.-Koleni%C4%8D-Franke/f9920c684e5da8baa8a8e756bc816cd1d9c5924d
[5] https://www.nature.com/articles/s41380-022-01616-5
Text filled in the textarea.
Error clicking copy button: Message:
Stacktrace:
0   chromedriver                        0x000000010328d024 cxxbridge1$str$ptr + 1887276
1   chromedriver                        0x0000000103285700 cxxbridge1$str$ptr + 1856264
2   chromedriver                        0x0000000102e9482c cxxbridge1$string$len + 88524
3   chromedriver                        0x0000000102ed8834 cxxbridge1$string$len + 367060
4   chromedriver                        0x0000000102f1048c cxxbridge1$string$len + 595500
5   chromedriver                        0x0000000102ecd474 cxxbridge1$string$len + 321044
6   chromedriver                        0x0000000102ece0e4 cxxbridge1$string$len + 324228
7   chromedriver                        0x0000000103254a08 cxxbridge1$str$ptr + 1656336
8   chromedriver                        0x0000000103259464 cxxbridge1$str$ptr + 1675372
9   chromedriver                        0x000000010323a8ec cxxbridge1$str$ptr + 1549556
10  chromedriver                        0x0000000103259c14 cxxbridge1$str$ptr + 1677340
11  chromedriver                        0x000000010322c5fc cxxbridge1$str$ptr + 1491460
12  chromedriver                        0x0000000103276a5c cxxbridge1$str$ptr + 1795684
13  chromedriver                        0x0000000103276bd8 cxxbridge1$str$ptr + 1796064
14  chromedriver                        0x0000000103285334 cxxbridge1$str$ptr + 1855292
15  libsystem_pthread.dylib             0x0000000194cb5f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000194cb0d34 thread_start + 8

Clipboard Content for PMID 29464432:
 ```json
{
  "patient_level_data": true,
  "institutions_involved": ["Department of Psychiatry"],
  "countries": ["Not specified"],
  "data_collection_approach": "distributed",
  "total_dataset_size": 183,
  "pmid": 29454222
}
```

Citations:
[1] https://www.sciencedirect.com/science/article/pii/S0022395617312141
[2] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8530396/
[3] https://www.researchgate.net/publication/323083117_Obesity_dyslipidemia_and_brain_age_in_first-episode_psychosis
[4] https://www.semanticscholar.org/paper/Obesity%2C-dyslipidemia-and-brain-age-in-psychosis.-Koleni%C4%8D-Franke/f9920c684e5da8baa8a8e756bc816cd1d9c5924d
[5] https://www.nature.com/articles/s41380-022-01616-5

KeyboardInterrupt:

In [44]:
import os
import json

def extract_json_objects_from_text(text):
    json_objects = []
    while True:
        # Find the first '{' and the last '}'
        start_index = text.find('{')
        end_index = text.rfind('}')

        if start_index == -1 or end_index == -1 or start_index > end_index:
            break

        # Extract the substring from the first '{' to the last '}'
        json_str = text[start_index:end_index + 1]

        # Try to parse the extracted substring as JSON
        try:
            json_object = json.loads(json_str)
            json_objects.append(json_object)
            # Remove the processed part of the text
            text = text[end_index + 1:]
        except json.JSONDecodeError:
            # If parsing fails, continue searching in the remaining text
            text = text[end_index + 1:]

    return json_objects

def extract_json_objects_from_txt(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
    return extract_json_objects_from_text(content)

def read_json_from_folder(folder_path):
    all_json_objects = []
    for file_name in os.listdir(folder_path):
        if file_name.endswith('.txt'):
            file_path = os.path.join(folder_path, file_name)
            json_objects = extract_json_objects_from_txt(file_path)
            all_json_objects.extend(json_objects)
    return all_json_objects

# Example usage
folder_path = './perplexity/'
json_array = read_json_from_folder(folder_path)
print(json_array)

[{'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29790333}, {'patient_level_data': True, 'institutions_involved': ['Department of Psychiatry'], 'countries': ['Not specified'], 'data_collection_approach': 'distributed', 'total_dataset_size': 183, 'pmid': 29454222}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 5090, 'pmid': 29704323}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 29671385}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['China'], 'data_collection_approach': 'distributed', 'total_dataset_size': 1000, 'pmid': 29539596}, {'patient_level_data': True, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 53, 'pmid': 28350526}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29356281}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 30152128}, {'patient_level_data': True, 'institutions_involved': ['Medtronic, Inc.', 'National Academy of Medicine'], 'countries': ['United States'], 'data_collection_approach': 'central', 'total_dataset_size': 99965, 'pmid': 29042099}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29244479}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29555075}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 4, 'pmid': 29293692}, {'patient_level_data': True, 'institutions_involved': ['Agriculture and Agri-Food Canada', 'University of Alberta'], 'countries': ['Canada'], 'data_collection_approach': 'distributed', 'total_dataset_size': 190, 'pmid': 30149509}, {'patient_level_data': True, 'institutions_involved': ['University of Calgary', 'University of Alberta', 'University of British Columbia'], 'countries': ['Canada'], 'data_collection_approach': 'distributed', 'total_dataset_size': 57, 'pmid': 30155514}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29808466}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 29429021}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': ['Simon Fraser University', 'Medical University of Vienna', 'University of Campania', 'MetaOptima Technology Inc.'], 'countries': ['Canada', 'Austria', 'Italy'], 'data_collection_approach': 'central', 'total_dataset_size': 18829, 'pmid': 30207594}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 39, 'pmid': 29128490}, {'patient_level_data': True, 'institutions_involved': ['Ludwig-Maximilians-University', 'University of Regensburg', 'University Hospital Bonn'], 'countries': ['Germany'], 'data_collection_approach': 'central', 'total_dataset_size': 92, 'pmid': 28981875}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 5090, 'pmid': 29704323}, {'patient_level_data': False, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 4000, 'pmid': 29508298}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B', 'Institution C'], 'countries': ['Canada', 'South Korea', 'Eastern Europe'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29340580}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 29186351}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'distributed', 'total_dataset_size': 27, 'pmid': 29244902}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29205792}, {'patient_level_data': True, 'institutions_involved': ['McMaster University'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 186, 'pmid': 29407288}, {'patient_level_data': False, 'institutions_involved': ['The University of Sydney'], 'countries': ['Australia'], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 30138366}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29749141}, {'patient_level_data': True, 'institutions_involved': ['University Health Network'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29769044}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 140, 'pmid': 29045911}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': ['University of Kentucky', 'University of California, Berkeley'], 'countries': ['United States'], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29571894}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29346286}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29555075}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 29671385}, {'patient_level_data': True, 'institutions_involved': ["Stollery Children's Hospital"], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 30143502}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29497848}, {'patient_level_data': True, 'institutions_involved': ['Université de Montréal', 'Hôpital du Sacré-Cœur de Montréal'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 4791, 'pmid': 29717941}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ['University of Calgary', 'University of Alberta'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 98, 'pmid': 30218110}, {'patient_level_data': False, 'institutions_involved': ['Scripps Research Institute', 'University of California San Diego', 'University of Ottawa'], 'countries': ['USA', 'Canada'], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29441361}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ['Institut National de la Santé et de la Recherche Médicale (INSERM)', 'Assistance Publique des Hôpitaux de Paris (AP-HP)', 'Fondation FondaMental'], 'countries': ['France'], 'data_collection_approach': 'central', 'total_dataset_size': 635, 'pmid': 29766490}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ['Department of Psychiatry'], 'countries': ['Not specified'], 'data_collection_approach': 'distributed', 'total_dataset_size': 183, 'pmid': 29454222}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ["Addenbrooke's Hospital, University of Cambridge", 'University of Manitoba'], 'countries': ['UK', 'Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 41, 'pmid': 29043544}, {'patient_level_data': True, 'institutions_involved': ['Ryerson University', 'Toronto Rehabilitation Institute', 'University of L’Aquila', 'Florida State University', 'Goldsmiths, University of London'], 'countries': ['Canada', 'Italy', 'United States', 'United Kingdom'], 'data_collection_approach': 'distributed', 'total_dataset_size': 60, 'pmid': 29354080}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': ['University of Montreal', 'New York University'], 'countries': ['Canada', 'United States'], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 29381440}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29232649}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 52, 'pmid': 29581092}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ['Emory University', 'Xi’an Jiaotong University', 'The Second Hospital of Guangzhou Medical University'], 'countries': ['United States', 'China'], 'data_collection_approach': 'distributed', 'total_dataset_size': 140, 'pmid': 29766373}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29474917}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ['CancerCare Manitoba', 'Molecular Taxonomy of Breast Cancer International Consortium'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 1141, 'pmid': 29699511}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29589479}, {'patient_level_data': True, 'institutions_involved': ['SickKids Hospital', 'Lawrence Bloomberg Faculty of Nursing'], 'countries': ['Canada'], 'data_collection_approach': 'distributed', 'total_dataset_size': 40, 'pmid': 29893482}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 17499, 'pmid': 30153635}, {'patient_level_data': True, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 13, 'pmid': 28596271}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 30200566}, {'patient_level_data': True, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'central', 'total_dataset_size': 172, 'pmid': 29065782}, {'patient_level_data': True, 'institutions_involved': ['Université Laval', 'Centre intégré universitaire de santé et de services sociaux de la Capitale-Nationale', 'McGill University', 'Centre intégré de santé et de services sociaux de Laval'], 'countries': ['Canada'], 'data_collection_approach': 'distributed', 'total_dataset_size': 12, 'pmid': 29385842}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': ['University of Waterloo'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 0, 'pmid': 29220306}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29890954}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': ['University of Pittsburgh', 'Other Institutions'], 'countries': ['United States'], 'data_collection_approach': 'central', 'total_dataset_size': 73, 'pmid': 29548746}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29450848}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': ['France Life Imaging'], 'countries': ['France'], 'data_collection_approach': 'central', 'total_dataset_size': 176, 'pmid': 29268169}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': ['University of Calgary'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': None, 'pmid': 29059324}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 30209345}, {'patient_level_data': True, 'institutions_involved': ['University of Calgary'], 'countries': ['Canada'], 'data_collection_approach': 'distributed', 'total_dataset_size': 66370, 'pmid': 30226903}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': True, 'institutions_involved': ["St Michael's Hospital", 'University of Toronto'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': None, 'pmid': 29092082}, {'patient_level_data': True, 'institutions_involved': ['Institution A', 'Institution B'], 'countries': ['Country X', 'Country Y'], 'data_collection_approach': 'central', 'total_dataset_size': 1000, 'pmid': 29750403}, {'patient_level_data': True, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 82, 'pmid': 29321970}, {'patient_level_data': True, 'institutions_involved': ['University of New Brunswick', 'University of Alberta'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 100, 'pmid': 30212573}, {'patient_level_data': True, 'institutions_involved': ['University of Calgary', 'University of Alberta', 'University of British Columbia'], 'countries': ['Canada'], 'data_collection_approach': 'distributed', 'total_dataset_size': 57, 'pmid': 30155514}, {'patient_level_data': False, 'institutions_involved': [], 'countries': [], 'data_collection_approach': 'distributed', 'total_dataset_size': 0, 'pmid': 29926728}, {'patient_level_data': False, 'institutions_involved': ['The University of North Carolina, Chapel Hill', 'McGill University'], 'countries': ['USA', 'Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 5771, 'pmid': 29546805}, {'patient_level_data': True, 'institutions_involved': ['Montreal Neurological Institute'], 'countries': ['Canada'], 'data_collection_approach': 'central', 'total_dataset_size': 53, 'pmid': 29334038}, {'patient_level_data': True, 'institutions_involved': ['Nigist Eleni Mohamed Memorial Compressive Specialized Hospital', 'Jimma Institute of Technology', 'Rayalaseema University'], 'countries': ['Ethiopia', 'India'], 'data_collection_approach': 'central', 'total_dataset_size': 48, 'pmid': 29747532}, {'patient_level_data': False, 'institutions_involved': ['University of Lethbridge'], 'countries': ['Canada'], 'data_collection_approach': 'distributed', '

In [45]:
df_perplexity = pd.DataFrame(json_array)
df_perplexity

,patient_level_data,institutions_involved,countries,data_collection_approach,total_dataset_size,pmid
0,False,[],[],distributed,0.0,29926728
1,False,[],[],distributed,0.0,29790333
2,True,[Department of Psychiatry],[Not specified],distributed,183.0,29454222
3,True,"[Institution A, Institution B]","[Country X, Country Y]",central,5090.0,29704323
4,False,[],[],central,0.0,29671385
...,...,...,...,...,...,...
389,True,[],[],central,116.0,28756487
390,False,"[Beef Cattle Institute, Kansas State University]",[United States],distributed,0.0,29385611
391,True,"[Nizhny Novgorod State Medical Academy, Instit...",[Russia],central,1024.0,28853237
392,True,"[University of Calgary, University of Alberta,...",[Canada],distributed,57.0,30155514
393,False,[],[],distributed,0.0,29884691

In [46]:
df_perplexity[(df_perplexity['patient_level_data'] == True) & (df_perplexity['data_collection_approach'] != 'central')]

,patient_level_data,institutions_involved,countries,data_collection_approach,total_dataset_size,pmid
2,True,[Department of Psychiatry],[Not specified],distributed,183.0,29454222
16,True,"[Agriculture and Agri-Food Canada, University ...",[Canada],distributed,190.0,30149509
17,True,"[University of Calgary, University of Alberta,...",[Canada],distributed,57.0,30155514
31,True,"[Institution A, Institution B]","[Country X, Country Y]",distributed,27.0,29244902
52,True,[Department of Psychiatry],[Not specified],distributed,183.0,29454222
...,...,...,...,...,...,...
382,True,[Centre Hospitalier Regional et Universitaire ...,"[France, Canada]",distributed,1000.0,30154742
383,True,"[Brigham and Women’s Hospital, Harvard Medical...","[USA, Portugal, Canada, Japan]",distributed,9.0,29869321
384,True,"[Institution A, Institution B]","[Country X, Country Y]",distributed,48.0,29344313
388,True,[],[],distributed,4.0,29382744
392,True,"[University of Calgary, University of Alberta,...",[Canada],distributed,57.0,30155514

In [1]:
import pandas as pd
file_path = 'data-full-text.csv'  # Replace with your actual file path
canada_df = pd.read_csv(file_path)

In [2]:
canada_df

           pid                                              title
0     29609039  Computer-aided diagnosis of cavernous malforma...
1     29616521  The relationship between cerebral oxygen satur...
2     29632364  Multimodal and Multiscale Deep Neural Networks...
3     29636016  Machine learning classification of first-episo...
4     29642656  Socioeconomic disparities and difficulties to ...
...        ...                                                ...
3524  39001096  Derivative Method to Detect Sleep and Awake St...
3525  39001410  Deep Learning Algorithms for Bladder Cancer Se...
3526  39002043  Predictors of High Healthcare Cost Among Patie...
3527  39012781  Short-Term Exposure to Wildfire-Specific PM2.5...
3528  39013639  The performance of digital technologies for me...

[3529 rows x 2 columns]

In [25]:
from selenium import webdriver
import pyperclip
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.common.keys import Keys
import os

def initialize_driver():
    """
    Initialize the Chrome WebDriver with specified options and service.
    """
    options = Options()
    # options.add_argument("--headless")  # Ensure GUI is off
    # options.add_argument("--no-sandbox")
    # options.add_argument("--disable-dev-shm-usage")
 
    # Enable clipboard access
    options.add_experimental_option("prefs", {
        "profile.default_content_setting_values.clipboard": 1  # 1: allow, 2: block
    })

    service = Service("/opt/homebrew/bin/chromedriver")  # Adjust the path if needed
    driver = webdriver.Chrome(service=service, options=options)
    return driver

def fill_textarea(driver, wait, title, pmid):
    """
    Fill the last textarea found on the page with the specified text.
    """
    try:
        # Wait until the textarea is clickable
        textarea = wait.until(EC.element_to_be_clickable((By.XPATH, "//textarea[last()]")))
        textarea.clear()
        # Part 1
        textarea.send_keys("Consider this paper I MEAN FULL TEXT OF THE PAPER,")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # Another new line
        textarea.send_keys(f"- **{title}**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line

        textarea.send_keys(f"- **PMID (PubMed)**: {pmid}")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # Another new line
        
        textarea.send_keys("extract and return the following information in JSON format:")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)  # New line

        # Part 2
        textarea.send_keys("1. **Total Dataset Size:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Number of Records/Samples: Exact count of individual records or samples.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Size in GB/TB: The physical size of the dataset.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Number of Data Points per Sample: Average number of data points collected per sample.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("2. **Data Collection Method:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Type: Centralized vs. Decentralized.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Source of Data: Specific institutions, countries, or regions where data was collected.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Timeframe of Data Collection: Period during which the data was collected.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("3. **Data Modalities:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Type of Data: Imaging, genomic, clinical, sensor, etc.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Combination of Modalities: Whether multiple data types were used together (e.g., multimodal learning).")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Data Format: Structured, unstructured, semi-structured.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("4. **Number of Features in Datasets:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Feature Count: Exact number of features.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Feature Types: Categorical, numerical, text, image, etc.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Feature Selection Methods: Techniques used to select or engineer features.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("5. **AI Methods:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Specific Algorithms: Deep learning, support vector machines, random forests, etc.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Model Architecture: Details on model design, such as layers in neural networks.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Training Techniques: Techniques like transfer learning, ensemble learning, federated learning.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Performance Metrics: Accuracy, precision, recall, F1 score, AUC, etc.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("6. **Number of Collaborators:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Number of Institutions: Count of participating organizations.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Geographical Distribution: Countries or regions involved.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Roles: Specific roles of collaborators (e.g., data providers, algorithm developers, model trainers).")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("7. **Data Privacy Techniques:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Privacy-Preserving Methods: Differential privacy, homomorphic encryption, secure multi-party computation.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Compliance with Regulations: GDPR, HIPAA, etc.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Data Anonymization: Techniques for anonymizing sensitive information.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("8. **Data Heterogeneity:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Source Diversity: Variability in data sources (e.g., hospitals, clinics, sensors).")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Population Diversity: Diversity of patient demographics (e.g., age, ethnicity, gender).")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Consistency Across Datasets: Measures taken to standardize data for analysis.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("9. **Data Sharing and Collaboration Mechanisms:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Platforms Used: Specific platforms or frameworks (e.g., GA4GH, DataSHIELD).")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Collaboration Models: Types of collaboration (e.g., open, consortium-based).")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("   - Data Accessibility: Level of access (open access, restricted access, etc.).")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)

        textarea.send_keys("10. **Ethical Considerations:**")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("    - Ethical Approvals: Details on ethics committee approvals.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("    - Informed Consent: How informed consent was obtained from participants.")
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys("    - Bias Mitigation: Steps taken to address bias in data collection and analysis.")
        
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        textarea.send_keys(Keys.SHIFT + Keys.ENTER)
        
        # Part 4
        textarea.send_keys("Please analyze the paper and return ONLY the JSON object accordingly without any additional text; I mean only JSON should be in the result.")
        

        print("Text filled in the textarea.")
        textarea.send_keys(Keys.ENTER) #submit
    except Exception as e:
        print(f"Error filling textarea: {e}")

def click_copy_button(driver, wait):
    """
    Scroll to the button with a clipboard icon and click it to copy the response.
    """
    try:
        # Wait for the SVG element
        clipboard_svg = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "svg[data-icon='clipboard']")))

        # Get the parent button
        copy_button = clipboard_svg.find_element(By.XPATH, './ancestor::button')
        #print('copy_button>>>', copy_button)

        # Scroll the element into view
        driver.execute_script("arguments[0].scrollIntoView(true);", copy_button)
        #driver.save_screenshot('before_click.png')

        # Wait until the button is clickable
        # copy_button.click()
        driver.execute_script("arguments[0].click();", copy_button)

        print("Copy button clicked.")
    except Exception as e:
        print(f"Error clicking copy button: {e}")

def main():
    driver = initialize_driver()
    wait = WebDriverWait(driver, 10)  # Wait up to 10 seconds

    # data = [
    #     {
    #         "title": "Preliminary testing by adults of a haptics-assisted robot platform designed for children with physical impairments to access play",
    #         "pmid": 28696831
    #     },
    #     {
    #         "title": "Dark Flow, Depression and Multiline Slot Machine Play",
    #         "pmid": 28589480
    #     }
    # ]

    try:
        file_path = 'data-full-text.csv'  # Replace with your actual file path
        canada_df = pd.read_csv(file_path)
        print(f"len:{len(canada_df)}")
        driver.get("https://www.perplexity.ai/")
        original_window = driver.current_window_handle  # Store the handle of the original window
        input("Press any key to continue...")

        # for entry in data:
        for index, entry in canada_df.iterrows():
            pyperclip.copy('')  # Clear the clipboard before starting
            # body = driver.find_element(By.TAG_NAME, 'body')
            # body.send_keys(Keys.COMMAND + 'k')  # For macOS

            # if index> 1:
            #     break

            # title = entry["title"]
            # pmid = entry["pmid"]
            title = entry["title"]
            pmid = entry["pid"]

            # Check if file already exists
            filename = f"./perplexity-ft/{pmid}.txt"
            if os.path.exists(filename):
                print(f"File {filename} already exists. Skipping...")
                continue  # Skip to the next iteration

            # Open a new tab and switch to it
            driver.execute_script("window.open('');")
            new_tab = driver.window_handles[-1]
            driver.switch_to.window(new_tab)

            # Load the page in the new tab
            driver.get("https://www.perplexity.ai/")

            fill_textarea(driver, wait, title, pmid)

            click_copy_button(driver, wait)

            # Allow time for the clipboard to update
            time.sleep(1)

            # Retrieve the string from the clipboard and print it
            clipboard_content = pyperclip.paste()
            print(f"Clipboard Content for PMID {pmid}:\n", clipboard_content)

            # Save the result to a file
            with open(filename, "w") as file:
                file.write(clipboard_content)

            # Close the new tab and switch back to the original tab
            # input("Press Enter to close the browser...")
            driver.close()
            driver.switch_to.window(original_window)
    finally:
        # Ensure the driver is properly closed even if an error occurs
        driver.quit()

if __name__ == "__main__":
    main()

len:3529
File ./perplexity-ft/29609039.txt already exists. Skipping...
File ./perplexity-ft/29616521.txt already exists. Skipping...
File ./perplexity-ft/29632364.txt already exists. Skipping...
File ./perplexity-ft/29636016.txt already exists. Skipping...
File ./perplexity-ft/29642656.txt already exists. Skipping...
File ./perplexity-ft/29708944.txt already exists. Skipping...
File ./perplexity-ft/29854259.txt already exists. Skipping...
File ./perplexity-ft/29860189.txt already exists. Skipping...
File ./perplexity-ft/30290728.txt already exists. Skipping...
File ./perplexity-ft/30300751.txt already exists. Skipping...
File ./perplexity-ft/30301895.txt already exists. Skipping...
File ./perplexity-ft/33934542.txt already exists. Skipping...
File ./perplexity-ft/30992063.txt already exists. Skipping...
File ./perplexity-ft/32193665.txt already exists. Skipping...
File ./perplexity-ft/32864270.txt already exists. Skipping...
File ./perplexity-ft/32864596.txt already exists. Skipping...
File ./perplexity-ft/32941770.txt already exists. Skipping...
File ./perplexity-ft/32943286.txt already exists. Skipping...
File ./perplexity-ft/32943654.txt already exists. Skipping...
File ./perplexity-ft/32945910.txt already exists. Skipping...
File ./perplexity-ft/32957946.txt already exists. Skipping...
File ./perplexity-ft/32997560.txt already exists. Skipping...
File ./perplexity-ft/33002841.txt already exists. Skipping...
File ./perplexity-ft/33003163.txt already exists. Skipping...
File ./perplexity-ft/33003524.txt already exists. Skipping...
File ./perplexity-ft/33005028.txt already exists. Skipping...
File ./perplexity-ft/33288765.txt already exists. Skipping...
File ./perplexity-ft/33289519.txt already exists. Skipping...
File ./perplexity-ft/33500958.txt already exists. Skipping...
File ./perplexity-ft/28350526.txt already exists. Skipping...
File ./perplexity-ft/33655433.txt already exists. Skipping...
File ./perplexity-ft/33657184.txt already exists. Skipping...
File ./perplexity-ft/33658605.txt already exists. Skipping...
File ./perplexity-ft/33672259.txt already exists. Skipping...
File ./perplexity-ft/35126902.txt already exists. Skipping...
File ./perplexity-ft/35127487.txt already exists. Skipping...
File ./perplexity-ft/34140617.txt already exists. Skipping...
File ./perplexity-ft/34181661.txt already exists. Skipping...
File ./perplexity-ft/34183345.txt already exists. Skipping...
File ./perplexity-ft/34185253.txt already exists. Skipping...
File ./perplexity-ft/34185798.txt already exists. Skipping...
File ./perplexity-ft/34213529.txt already exists. Skipping...
File ./perplexity-ft/34214101.txt already exists. Skipping...
File ./perplexity-ft/34214980.txt already exists. Skipping...
File ./perplexity-ft/34248903.txt already exists. Skipping...
File ./perplexity-ft/28601499.txt already exists. Skipping...
File ./perplexity-ft/28651909.txt already exists. Skipping...
File ./perplexity-ft/34487910.txt already exists. Skipping...
File ./perplexity-ft/34487983.txt already exists. Skipping...
File ./perplexity-ft/34489404.txt already exists. Skipping...
File ./perplexity-ft/34490899.txt already exists. Skipping...
File ./perplexity-ft/34490909.txt already exists. Skipping...
File ./perplexity-ft/34541337.txt already exists. Skipping...
File ./perplexity-ft/34543173.txt already exists. Skipping...
File ./perplexity-ft/34547916.txt already exists. Skipping...
File ./perplexity-ft/34557674.txt already exists. Skipping...
File ./perplexity-ft/34694234.txt already exists. Skipping...
File ./perplexity-ft/34694564.txt already exists. Skipping...
File ./perplexity-ft/34760140.txt already exists. Skipping...
File ./perplexity-ft/28696831.txt already exists. Skipping...
File ./perplexity-ft/29869321.txt already exists. Skipping...
File ./perplexity-ft/35269470.txt already exists. Skipping...
File ./perplexity-ft/34936195.txt already exists. Skipping...
File ./perplexity-ft/34936894.txt already exists. Skipping...
File ./perplexity-ft/34936945.txt already exists. Skipping...
File ./perplexity-ft/34937750.txt already exists. Skipping...
File ./perplexity-ft/34938605.txt already exists. Skipping...
File ./perplexity-ft/34949699.txt already exists. Skipping...
File ./perplexity-ft/34950616.txt already exists. Skipping...
File ./perplexity-ft/29886268.txt already exists. Skipping...
File ./perplexity-ft/29886760.txt already exists. Skipping...
File ./perplexity-ft/29889330.txt already exists. Skipping...
File ./perplexity-ft/35468151.txt already exists. Skipping...
File ./perplexity-ft/35469087.txt already exists. Skipping...
File ./perplexity-ft/35472473.txt already exists. Skipping...
File ./perplexity-ft/35474073.txt already exists. Skipping...
File ./perplexity-ft/35475554.txt already exists. Skipping...
File ./perplexity-ft/35477557.txt already exists. Skipping...
File ./perplexity-ft/35478098.txt already exists. Skipping...
File ./perplexity-ft/29893482.txt already exists. Skipping...
File ./perplexity-ft/29902277.txt already exists. Skipping...
File ./perplexity-ft/36836230.txt already exists. Skipping...
File ./perplexity-ft/29905649.txt already exists. Skipping...
File ./perplexity-ft/29905656.txt already exists. Skipping...
File ./perplexity-ft/29921920.txt already exists. Skipping...
File ./perplexity-ft/36005841.txt already exists. Skipping...
File ./perplexity-ft/29949021.txt already exists. Skipping...
File ./perplexity-ft/31636101.txt already exists. Skipping...
File ./perplexity-ft/31636895.txt already exists. Skipping...
File ./perplexity-ft/31638491.txt already exists. Skipping...
File ./perplexity-ft/36046472.txt already exists. Skipping...
File ./perplexity-ft/36050434.txt already exists. Skipping...
File ./perplexity-ft/36055201.txt already exists. Skipping...
File ./perplexity-ft/36072822.txt already exists. Skipping...
File ./perplexity-ft/36075963.txt already exists. Skipping...
File ./perplexity-ft/36081373.txt already exists. Skipping...
File ./perplexity-ft/36083416.txt already exists. Skipping...
File ./perplexity-ft/30255819.txt already exists. Skipping...
File ./perplexity-ft/30262516.txt already exists. Skipping...
File ./perplexity-ft/30263040.txt already exists. Skipping...
File ./perplexity-ft/32887670.txt already exists. Skipping...
File ./perplexity-ft/32888727.txt already exists. Skipping...
File ./perplexity-ft/33915960.txt already exists. Skipping...
File ./perplexity-ft/30340027.txt already exists. Skipping...
File ./perplexity-ft/30352783.txt already exists. Skipping...
File ./perplexity-ft/30354561.txt already exists. Skipping...
File ./perplexity-ft/30367117.txt already exists. Skipping...
File ./perplexity-ft/30373211.txt already exists. Skipping...
File ./perplexity-ft/36229614.txt already exists. Skipping...
File ./perplexity-ft/36233593.txt already exists. Skipping...
File ./perplexity-ft/36236373.txt already exists. Skipping...
File ./perplexity-ft/36236422.txt already exists. Skipping...
File ./perplexity-ft/36284402.txt already exists. Skipping...
File ./perplexity-ft/30381856.txt already exists. Skipping...
File ./perplexity-ft/30383850.txt already exists. Skipping...
File ./perplexity-ft/36324086.txt already exists. Skipping...
File ./perplexity-ft/36326618.txt already exists. Skipping...
File ./perplexity-ft/36327383.txt already exists. Skipping...
File ./perplexity-ft/36329531.txt already exists. Skipping...
File ./perplexity-ft/36332954.txt already exists. Skipping...
File ./perplexity-ft/36336953.txt already exists. Skipping...
File ./perplexity-ft/36339062.txt already exists. Skipping...
File ./perplexity-ft/30794559.txt already exists. Skipping...
File ./perplexity-ft/36574245.txt already exists. Skipping...
File ./perplexity-ft/28756487.txt already exists. Skipping...
File ./perplexity-ft/28771699.txt already exists. Skipping...
File ./perplexity-ft/28853237.txt already exists. Skipping...
File ./perplexity-ft/28869436.txt already exists. Skipping...
File ./perplexity-ft/28952798.txt already exists. Skipping...
File ./perplexity-ft/28968847.txt already exists. Skipping...
File ./perplexity-ft/28981875.txt already exists. Skipping...
File ./perplexity-ft/28987903.txt already exists. Skipping...
File ./perplexity-ft/30807586.txt already exists. Skipping...
File ./perplexity-ft/30809047.txt already exists. Skipping...
File ./perplexity-ft/36756643.txt already exists. Skipping...
File ./perplexity-ft/36810139.txt already exists. Skipping...
File ./perplexity-ft/36812626.txt already exists. Skipping...
File ./perplexity-ft/36812632.txt already exists. Skipping...
File ./perplexity-ft/36812648.txt already exists. Skipping...
File ./perplexity-ft/36812932.txt already exists. Skipping...
File ./perplexity-ft/36813095.txt already exists. Skipping...
File ./perplexity-ft/36817429.txt already exists. Skipping...
File ./perplexity-ft/29043544.txt already exists. Skipping...
File ./perplexity-ft/29065782.txt already exists. Skipping...
File ./perplexity-ft/29071211.txt already exists. Skipping...
File ./perplexity-ft/29084099.txt already exists. Skipping...
File ./perplexity-ft/29094375.txt already exists. Skipping...
File ./perplexity-ft/29098645.txt already exists. Skipping...
File ./perplexity-ft/29128490.txt already exists. Skipping...
File ./perplexity-ft/29145629.txt already exists. Skipping...
File ./perplexity-ft/29169029.txt already exists. Skipping...
File ./perplexity-ft/29193460.txt already exists. Skipping...
File ./perplexity-ft/29194610.txt already exists. Skipping...
File ./perplexity-ft/38468224.txt already exists. Skipping...
File ./perplexity-ft/38469689.txt already exists. Skipping...
File ./perplexity-ft/38470880.txt already exists. Skipping...
File ./perplexity-ft/30839433.txt already exists. Skipping...
File ./perplexity-ft/38479730.txt already exists. Skipping...
File ./perplexity-ft/38480766.txt already exists. Skipping...
File ./perplexity-ft/38483388.txt already exists. Skipping...
File ./perplexity-ft/38484398.txt already exists. Skipping...
File ./perplexity-ft/30870597.txt already exists. Skipping...
File ./perplexity-ft/31150083.txt already exists. Skipping...
File ./perplexity-ft/31150956.txt already exists. Skipping...
File ./perplexity-ft/31151119.txt already exists. Skipping...
File ./perplexity-ft/31153115.txt already exists. Skipping...
File ./perplexity-ft/31154512.txt already exists. Skipping...
File ./perplexity-ft/37087135.txt already exists. Skipping...
File ./perplexity-ft/37090433.txt already exists. Skipping...
File ./perplexity-ft/31158822.txt already exists. Skipping...
File ./perplexity-ft/31161221.txt already exists. Skipping...
File ./perplexity-ft/31163373.txt already exists. Skipping...
File ./perplexity-ft/37231096.txt already exists. Skipping...
File ./perplexity-ft/37233646.txt already exists. Skipping...
File ./perplexity-ft/31164212.txt already exists. Skipping...
File ./perplexity-ft/37296806.txt already exists. Skipping...
File ./perplexity-ft/37322132.txt already exists. Skipping...
File ./perplexity-ft/37322550.txt already exists. Skipping...
File ./perplexity-ft/37323123.txt already exists. Skipping...
File ./perplexity-ft/37323348.txt already exists. Skipping...
File ./perplexity-ft/37326960.txt already exists. Skipping...
File ./perplexity-ft/31191926.txt already exists. Skipping...
File ./perplexity-ft/31194627.txt already exists. Skipping...
File ./perplexity-ft/31194873.txt already exists. Skipping...
File ./perplexity-ft/31196619.txt already exists. Skipping...
File ./perplexity-ft/31208434.txt already exists. Skipping...
File ./perplexity-ft/31216543.txt already exists. Skipping...
File ./perplexity-ft/31216619.txt already exists. Skipping...
File ./perplexity-ft/31219947.txt already exists. Skipping...
File ./perplexity-ft/31226518.txt already exists. Skipping...
File ./perplexity-ft/31227653.txt already exists. Skipping...
File ./perplexity-ft/31227879.txt already exists. Skipping...
File ./perplexity-ft/31228556.txt already exists. Skipping...
File ./perplexity-ft/32042111.txt already exists. Skipping...
File ./perplexity-ft/37544983.txt already exists. Skipping...
File ./perplexity-ft/32045708.txt already exists. Skipping...
File ./perplexity-ft/32053425.txt already exists. Skipping...
File ./perplexity-ft/32054511.txt already exists. Skipping...
File ./perplexity-ft/32055239.txt already exists. Skipping...
File ./perplexity-ft/37624384.txt already exists. Skipping...
File ./perplexity-ft/37625418.txt already exists. Skipping...
File ./perplexity-ft/37629214.txt already exists. Skipping...
File ./perplexity-ft/31286534.txt already exists. Skipping...
File ./perplexity-ft/31287020.txt already exists. Skipping...
File ./perplexity-ft/32463180.txt already exists. Skipping...
File ./perplexity-ft/32464565.txt already exists. Skipping...
File ./perplexity-ft/32467650.txt already exists. Skipping...
File ./perplexity-ft/37658409.txt already exists. Skipping...
File ./perplexity-ft/37658890.txt already exists. Skipping...
File ./perplexity-ft/37658963.txt already exists. Skipping...
File ./perplexity-ft/29237237.txt already exists. Skipping...
File ./perplexity-ft/29244902.txt already exists. Skipping...
File ./perplexity-ft/29251172.txt already exists. Skipping...
File ./perplexity-ft/29254878.txt already exists. Skipping...
File ./perplexity-ft/29268169.txt already exists. Skipping...
File ./perplexity-ft/29272464.txt already exists. Skipping...
File ./perplexity-ft/29274736.txt already exists. Skipping...
File ./perplexity-ft/29288983.txt already exists. Skipping...
File ./perplexity-ft/29753765.txt already exists. Skipping...
File ./perplexity-ft/29762023.txt already exists. Skipping...
File ./perplexity-ft/31405148.txt already exists. Skipping...
File ./perplexity-ft/31406675.txt already exists. Skipping...
File ./perplexity-ft/31414853.txt already exists. Skipping...
File ./perplexity-ft/32473064.txt already exists. Skipping...
File ./perplexity-ft/29294157.txt already exists. Skipping...
File ./perplexity-ft/29300432.txt already exists. Skipping...
File ./perplexity-ft/29304138.txt already exists. Skipping...
File ./perplexity-ft/29306928.txt already exists. Skipping...
File ./perplexity-ft/29321174.txt already exists. Skipping...
File ./perplexity-ft/29321970.txt already exists. Skipping...
File ./perplexity-ft/29334038.txt already exists. Skipping...
File ./perplexity-ft/29334467.txt already exists. Skipping...
File ./perplexity-ft/29335008.txt already exists. Skipping...
File ./perplexity-ft/29336922.txt already exists. Skipping...
File ./perplexity-ft/29340580.txt already exists. Skipping...
File ./perplexity-ft/29344313.txt already exists. Skipping...
File ./perplexity-ft/29346286.txt already exists. Skipping...
File ./perplexity-ft/29354080.txt already exists. Skipping...
File ./perplexity-ft/29355792.txt already exists. Skipping...
File ./perplexity-ft/29356281.txt already exists. Skipping...
File ./perplexity-ft/29356346.txt already exists. Skipping...
File ./perplexity-ft/29377156.txt already exists. Skipping...
File ./perplexity-ft/29378522.txt already exists. Skipping...
File ./perplexity-ft/29380275.txt already exists. Skipping...
File ./perplexity-ft/31505292.txt already exists. Skipping...
File ./perplexity-ft/31507022.txt already exists. Skipping...
File ./perplexity-ft/31508207.txt already exists. Skipping...
File ./perplexity-ft/31508367.txt already exists. Skipping...
File ./perplexity-ft/32473385.txt already exists. Skipping...
File ./perplexity-ft/32474393.txt already exists. Skipping...
File ./perplexity-ft/32475986.txt already exists. Skipping...
File ./perplexity-ft/29391513.txt already exists. Skipping...
File ./perplexity-ft/29398207.txt already exists. Skipping...
File ./perplexity-ft/29407288.txt already exists. Skipping...
File ./perplexity-ft/29450848.txt already exists. Skipping...
File ./perplexity-ft/29454222.txt already exists. Skipping...
File ./perplexity-ft/38486013.txt already exists. Skipping...
File ./perplexity-ft/38486268.txt already exists. Skipping...
File ./perplexity-ft/38487766.txt already exists. Skipping...
File ./perplexity-ft/38492206.txt already exists. Skipping...
File ./perplexity-ft/38493562.txt already exists. Skipping...
File ./perplexity-ft/38494468.txt already exists. Skipping...
File ./perplexity-ft/29502031.txt already exists. Skipping...
File ./perplexity-ft/32477638.txt already exists. Skipping...
File ./perplexity-ft/32477683.txt already exists. Skipping...
File ./perplexity-ft/29539639.txt already exists. Skipping...
File ./perplexity-ft/29540617.txt already exists. Skipping...
File ./perplexity-ft/29543895.txt already exists. Skipping...
File ./perplexity-ft/38497716.txt already exists. Skipping...
File ./perplexity-ft/38734697.txt already exists. Skipping...
File ./perplexity-ft/38739557.txt already exists. Skipping...
File ./perplexity-ft/29546805.txt already exists. Skipping...
File ./perplexity-ft/29548746.txt already exists. Skipping...
File ./perplexity-ft/29550305.txt already exists. Skipping...
File ./perplexity-ft/29558208.txt already exists. Skipping...
File ./perplexity-ft/29571749.txt already exists. Skipping...
File ./perplexity-ft/29581092.txt already exists. Skipping...
File ./perplexity-ft/32634140.txt already exists. Skipping...
File ./perplexity-ft/32635216.txt already exists. Skipping...
File ./perplexity-ft/32636008.txt already exists. Skipping...
File ./perplexity-ft/32636768.txt already exists. Skipping...
File ./perplexity-ft/32637418.txt already exists. Skipping...
File ./perplexity-ft/32640028.txt already exists. Skipping...
File ./perplexity-ft/32641740.txt already exists. Skipping...
File ./perplexity-ft/29603092.txt already exists. Skipping...
File ./perplexity-ft/29606521.txt already exists. Skipping...
File ./perplexity-ft/29662628.txt already exists. Skipping...
File ./perplexity-ft/29664902.txt already exists. Skipping...
File ./perplexity-ft/29665537.txt already exists. Skipping...
File ./perplexity-ft/29673341.txt already exists. Skipping...
File ./perplexity-ft/29674371.txt already exists. Skipping...
File ./perplexity-ft/29766373.txt already exists. Skipping...
File ./perplexity-ft/29678095.txt already exists. Skipping...
File ./perplexity-ft/29688388.txt already exists. Skipping...
File ./perplexity-ft/29689632.txt already exists. Skipping...
File ./perplexity-ft/29693792.txt already exists. Skipping...
File ./perplexity-ft/29699511.txt already exists. Skipping...
File ./perplexity-ft/29704323.txt already exists. Skipping...
File ./perplexity-ft/38446445.txt already exists. Skipping...
File ./perplexity-ft/38446766.txt already exists. Skipping...
File ./perplexity-ft/29717941.txt already exists. Skipping...
File ./perplexity-ft/29747532.txt already exists. Skipping...
File ./perplexity-ft/29748112.txt already exists. Skipping...
File ./perplexity-ft/29766490.txt already exists. Skipping...
File ./perplexity-ft/29766558.txt already exists. Skipping...
File ./perplexity-ft/29775951.txt already exists. Skipping...
File ./perplexity-ft/29779671.txt already exists. Skipping...
File ./perplexity-ft/29780871.txt already exists. Skipping...
File ./perplexity-ft/29801696.txt already exists. Skipping...
File ./perplexity-ft/29803920.txt already exists. Skipping...
File ./perplexity-ft/29806042.txt already exists. Skipping...
File ./perplexity-ft/29844507.txt already exists. Skipping...
File ./perplexity-ft/29844511.txt already exists. Skipping...
File ./perplexity-ft/29847723.txt already exists. Skipping...
File ./perplexity-ft/29964127.txt already exists. Skipping...
File ./perplexity-ft/29969172.txt already exists. Skipping...
File ./perplexity-ft/29971330.txt already exists. Skipping...
File ./perplexity-ft/29973250.txt already exists. Skipping...
File ./perplexity-ft/29980214.txt already exists. Skipping...
File ./perplexity-ft/38450221.txt already exists. Skipping...
File ./perplexity-ft/30005591.txt already exists. Skipping...
File ./perplexity-ft/30010088.txt already exists. Skipping...

In [17]:
# import os
# import hashlib

# def hash_file(filepath):
#     """Generate a hash for the contents of a file."""
#     hasher = hashlib.md5()
#     with open(filepath, 'rb') as file:
#         buf = file.read()
#         hasher.update(buf)
#     return hasher.hexdigest()

# def find_and_delete_duplicates(folder_path):
#     """Find and delete original text files if duplicates exist in the specified folder."""
#     file_hashes = {}
#     duplicates_to_delete = []

#     # First pass: Identify duplicates
#     for filename in os.listdir(folder_path):
#         if filename.endswith(".txt"):
#             file_path = os.path.join(folder_path, filename)
#             file_hash = hash_file(file_path)

#             if file_hash in file_hashes:
#                 # Add both the original and the duplicate to the deletion list
#                 duplicates_to_delete.append(file_path)
#                 if file_hashes[file_hash] is not None:
#                     duplicates_to_delete.append(file_hashes[file_hash])
#                     file_hashes[file_hash] = None  # Mark original for deletion
#             else:
#                 file_hashes[file_hash] = file_path

#     # Second pass: Delete files
#     for file_path in set(duplicates_to_delete):  # Use set to avoid double deletion
#         os.remove(file_path)
#         print(f"Deleted file: {file_path}")

# if __name__ == "__main__":
#     folder_path = "./perplexity-ft/"  # Replace with your folder path
#     find_and_delete_duplicates(folder_path)

Deleted file: ./perplexity-ft/29194610.txt
Deleted file: ./perplexity-ft/32356095.txt
Deleted file: ./perplexity-ft/33113221.txt
Deleted file: ./perplexity-ft/31414853.txt
Deleted file: ./perplexity-ft/31782551.txt
Deleted file: ./perplexity-ft/32561782.txt
Deleted file: ./perplexity-ft/30018571.txt
Deleted file: ./perplexity-ft/37658409.txt
Deleted file: ./perplexity-ft/31104700.txt
Deleted file: ./perplexity-ft/38265444.txt
Deleted file: ./perplexity-ft/33131680.txt
Deleted file: ./perplexity-ft/29237237.txt
Deleted file: ./perplexity-ft/31179487.txt
Deleted file: ./perplexity-ft/31284154.txt
Deleted file: ./perplexity-ft/32670113.txt
Deleted file: ./perplexity-ft/30573458.txt
Deleted file: ./perplexity-ft/33958739.txt
Deleted file: ./perplexity-ft/32318076.txt
Deleted file: ./perplexity-ft/32563597.txt
Deleted file: ./perplexity-ft/32715024.txt
Deleted file: ./perplexity-ft/32803448.txt
Deleted file: ./perplexity-ft/31133782.txt
Deleted file: ./perplexity-ft/29717941.txt
Deleted file: ./perplexity-ft/33131085.txt
Deleted file: ./perplexity-ft/36813095.txt
Deleted file: ./perplexity-ft/37768107.txt
Deleted file: ./perplexity-ft/33037266.txt
Deleted file: ./perplexity-ft/32555410.txt
Deleted file: ./perplexity-ft/31325985.txt
Deleted file: ./perplexity-ft/32710834.txt
Deleted file: ./perplexity-ft/31991302.txt
Deleted file: ./perplexity-ft/34310676.txt
Deleted file: ./perplexity-ft/31871069.txt
Deleted file: ./perplexity-ft/31797592.txt
Deleted file: ./perplexity-ft/32771686.txt
Deleted file: ./perplexity-ft/32178532.txt
Deleted file: ./perplexity-ft/32743554.txt
Deleted file: ./perplexity-ft/30614553.txt
Deleted file: ./perplexity-ft/32406850.txt
Deleted file: ./perplexity-ft/30155514.txt
Deleted file: ./perplexity-ft/38267475.txt
Deleted file: ./perplexity-ft/30084192.txt
Deleted file: ./perplexity-ft/32444812.txt
Deleted file: ./perplexity-ft/30476213.txt
Deleted file: ./perplexity-ft/31797611.txt
Deleted file: ./perplexity-ft/32978299.txt
Deleted file: ./perplexity-ft/30171211.txt
Deleted file: ./perplexity-ft/34850171.txt
Deleted file: ./perplexity-ft/36812648.txt
Deleted file: ./perplexity-ft/31338709.txt
Deleted file: ./perplexity-ft/31505292.txt
Deleted file: ./perplexity-ft/38446445.txt
Deleted file: ./perplexity-ft/32424317.txt
Deleted file: ./perplexity-ft/31694835.txt
Deleted file: ./perplexity-ft/32153047.txt
Deleted file: ./perplexity-ft/29779671.txt
Deleted file: ./perplexity-ft/32732967.txt
Deleted file: ./perplexity-ft/32453488.txt
Deleted file: ./perplexity-ft/30185806.txt
Deleted file: ./perplexity-ft/31822130.txt
Deleted file: ./perplexity-ft/32602222.txt
Deleted file: ./perplexity-ft/32682223.txt
Deleted file: ./perplexity-ft/32333121.txt
Deleted file: ./perplexity-ft/38618957.txt
Deleted file: ./perplexity-ft/33202340.txt
Deleted file: ./perplexity-ft/32797086.txt
Deleted file: ./perplexity-ft/32687564.txt
Deleted file: ./perplexity-ft/29356346.txt
Deleted file: ./perplexity-ft/33161063.txt
Deleted file: ./perplexity-ft/31443858.txt
Deleted file: ./perplexity-ft/32540846.txt
Deleted file: ./perplexity-ft/30267208.txt
Deleted file: ./perplexity-ft/36336953.txt
Deleted file: ./perplexity-ft/30300751.txt
Deleted file: ./perplexity-ft/33956307.txt
Deleted file: ./perplexity-ft/33219845.txt
Deleted file: ./perplexity-ft/32024819.txt
Deleted file: ./perplexity-ft/29665537.txt
Deleted file: ./perplexity-ft/32900610.txt
Deleted file: ./perplexity-ft/29762023.txt
Deleted file: ./perplexity-ft/31219947.txt
Deleted file: ./perplexity-ft/37322550.txt
Deleted file: ./perplexity-ft/30464478.txt
Deleted file: ./perplexity-ft/38626440.txt
Deleted file: ./perplexity-ft/33640674.txt
Deleted file: ./perplexity-ft/32021737.txt
Deleted file: ./perplexity-ft/32686681.txt
Deleted file: ./perplexity-ft/31128628.txt
Deleted file: ./perplexity-ft/32614505.txt
Deleted file: ./perplexity-ft/32325033.txt
Deleted file: ./perplexity-ft/29550305.txt
Deleted file: ./perplexity-ft/32591639.txt
Deleted file: ./perplexity-ft/33059718.txt
Deleted file: ./perplexity-ft/32688049.txt
Deleted file: ./perplexity-ft/38539236.txt
Deleted file: ./perplexity-ft/38268052.txt
Deleted file: ./perplexity-ft/32508229.txt
Deleted file: ./perplexity-ft/31733815.txt
Deleted file: ./perplexity-ft/31242238.txt
Deleted file: ./perplexity-ft/29708944.txt
Deleted file: ./perplexity-ft/31173905.txt
Deleted file: ./perplexity-ft/37625418.txt
Deleted file: ./perplexity-ft/31071228.txt
Deleted file: ./perplexity-ft/32848533.txt
Deleted file: ./perplexity-ft/33264099.txt
Deleted file: ./perplexity-ft/33780727.txt
Deleted file: ./perplexity-ft/32193870.txt
Deleted file: ./perplexity-ft/33137396.txt
Deleted file: ./perplexity-ft/29268169.txt
Deleted file: ./perplexity-ft/33289613.txt
Deleted file: ./perplexity-ft/33962603.txt
Deleted file: ./perplexity-ft/32440643.txt
Deleted file: ./perplexity-ft/32880697.txt
Deleted file: ./perplexity-ft/32686236.txt
Deleted file: ./perplexity-ft/32404485.txt
Deleted file: ./perplexity-ft/30229903.txt
Deleted file: ./perplexity-ft/33194219.txt
Deleted file: ./perplexity-ft/38267686.txt
Deleted file: ./perplexity-ft/33285356.txt
Deleted file: ./perplexity-ft/33770525.txt
Deleted file: ./perplexity-ft/32958802.txt
Deleted file: ./perplexity-ft/33166947.txt
Deleted file: ./perplexity-ft/32198433.txt
Deleted file: ./perplexity-ft/32770269.txt
Deleted file: ./perplexity-ft/33293364.txt
Deleted file: ./perplexity-ft/31696396.txt
Deleted file: ./perplexity-ft/32938996.txt
Deleted file: ./perplexity-ft/32383971.txt
Deleted file: ./perplexity-ft/32174253.txt
Deleted file: ./perplexity-ft/32413546.txt
Deleted file: ./perplexity-ft/31915534.txt
Deleted file: ./perplexity-ft/34357510.txt
Deleted file: ./perplexity-ft/31546227.txt
Deleted file: ./perplexity-ft/31805020.txt
Deleted file: ./perplexity-ft/31832652.txt
Deleted file: ./perplexity-ft/33324443.txt
Deleted file: ./perplexity-ft/33066454.txt
Deleted file: ./perplexity-ft/30809047.txt
Deleted file: ./perplexity-ft/31785402.txt
Deleted file: ./perplexity-ft/32071251.txt
Deleted file: ./perplexity-ft/32604080.txt
Deleted file: ./perplexity-ft/29304138.txt
Deleted file: ./perplexity-ft/33042905.txt
Deleted file: ./perplexity-ft/31952981.txt
Deleted file: ./perplexity-ft/33168895.txt
Deleted file: ./perplexity-ft/32284876.txt
Deleted file: ./perplexity-ft/34183345.txt
Deleted file: ./perplexity-ft/33149148.txt
Deleted file: ./perplexity-ft/31281024.txt
Deleted file: ./perplexity-ft/32023504.txt
Deleted file: ./perplexity-ft/38607809.txt
Deleted file: ./perplexity-ft/33144873.txt
Deleted file: ./perplexity-ft/38564508.txt
Deleted file: ./perplexity-ft/29300432.txt
Deleted file: ./perplexity-ft/29860189.txt
Deleted file: ./perplexity-ft/32673230.txt
Deleted file: ./perplexity-ft/29905656.txt
Deleted file: ./perplexity-ft/37323348.txt
Deleted file: ./perplexity-ft/31780395.txt
Deleted file: ./perplexity-ft/32248366.txt
Deleted file: ./perplexity-ft/32854798.txt
Deleted file: ./perplexity-ft/38266105.txt
Deleted file: ./perplexity-ft/31655612.txt
Deleted file: ./perplexity-ft/34858824.txt
Deleted file: ./perplexity-ft/32187319.txt
Deleted file: ./perplexity-ft/32532358.txt
Deleted file: ./perplexity-ft/29251172.txt
Deleted file: ./perplexity-ft/32185875.txt
Deleted file: ./perplexity-ft/31981624.txt
Deleted file: ./perplexity-ft/31883208.txt
Deleted file: ./perplexity-ft/34850112.txt
Deleted file: ./perplexity-ft/32554374.txt
Deleted file: ./perplexity-ft/32531021.txt
Deleted file: ./perplexity-ft/30947496.txt
Deleted file: ./perplexity-ft/31434533.txt
Deleted file: ./perplexity-ft/31256570.txt
Deleted file: ./perplexity-ft/37745926.txt
Deleted file: ./perplexity-ft/38538415.txt
Deleted file: ./perplexity-ft/38537536.txt
Deleted file: ./perplexity-ft/30770034.txt
Deleted file: ./perplexity-ft/32059918.txt
Deleted file: ./perplexity-ft/38267481.txt
Deleted file: ./perplexity-ft/31369994.txt
Deleted file: ./perplexity-ft/32232546.txt
Deleted file: ./perplexity-ft/32686118.txt
Deleted file: ./perplexity-ft/31062050.txt
Deleted file: ./perplexity-ft/32072271.txt
Deleted file: ./perplexity-ft/31382766.txt
Deleted file: ./perplexity-ft/30337678.txt
Deleted file: ./perplexity-ft/32533137.txt
Deleted file: ./perplexity-ft/32335226.txt
Deleted file: ./perplexity-ft/31117831.txt
Deleted file: ./perplexity-ft/31884486.txt
Deleted file: ./perplexity-ft/30459321.txt
Deleted file: ./perplexity-ft/33184741.txt
Deleted file: ./perplexity-ft/30519968.txt
Deleted file: ./perplexity-ft/37629214.txt
Deleted file: ./perplexity-ft/32962272.txt
Deleted file: ./perplexity-ft/36836230.txt
Deleted file: ./perplexity-ft/32655572.txt
Deleted file: ./perplexity-ft/32204950.txt
Deleted file: ./perplexity-ft/33277724.txt
Deleted file: ./perplexity-ft/33151087.txt
Deleted file: ./perplexity-ft/32143792.txt
Deleted file: ./perplexity-ft/33360844.txt
Deleted file: ./perplexity-ft/32935059.txt
Deleted file: ./perplexity-ft/31286067.txt
Deleted file: ./perplexity-ft/32164523.txt
Deleted file: ./perplexity-ft/32611681.txt
Deleted file: ./perplexity-ft/31186508.txt
Deleted file: ./perplexity-ft/32455927.txt
Deleted file: ./perplexity-ft/29274736.txt
Deleted file: ./perplexity-ft/32473064.txt
Deleted file: ./perplexity-ft/30587458.txt
Deleted file: ./perplexity-ft/31428758.txt
Deleted file: ./perplexity-ft/31325722.txt
Deleted file: ./perplexity-ft/38534937.txt
Deleted file: ./perplexity-ft/32054511.txt
Deleted file: ./perplexity-ft/32859912.txt
Deleted file: ./perplexity-ft/32615979.txt
Deleted file: ./perplexity-ft/32852320.txt
Deleted file: ./perplexity-ft/31305529.txt
Deleted file: ./perplexity-ft/29775951.txt
Deleted file: ./perplexity-ft/31101443.txt
Deleted file: ./perplexity-ft/30962703.txt
Deleted file: ./perplexity-ft/32904064.txt
Deleted file: ./perplexity-ft/33166800.txt
Deleted file: ./perplexity-ft/33112249.txt
Deleted file: ./perplexity-ft/36236422.txt
Deleted file: ./perplexity-ft/33074746.txt
Deleted file: ./perplexity-ft/32855842.txt
Deleted file: ./perplexity-ft/30187575.txt
Deleted file: ./perplexity-ft/32678722.txt
Deleted file: ./perplexity-ft/33028696.txt
Deleted file: ./perplexity-ft/31194873.txt
Deleted file: ./perplexity-ft/33094925.txt
Deleted file: ./perplexity-ft/30509988.txt
Deleted file: ./perplexity-ft/32819467.txt
Deleted file: ./perplexity-ft/33174832.txt
Deleted file: ./perplexity-ft/32045708.txt
Deleted file: ./perplexity-ft/38537130.txt
Deleted file: ./perplexity-ft/32568668.txt
Deleted file: ./perplexity-ft/32396346.txt
Deleted file: ./perplexity-ft/38532015.txt
Deleted file: ./perplexity-ft/32211946.txt
Deleted file: ./perplexity-ft/33038139.txt
Deleted file: ./perplexity-ft/31797603.txt
Deleted file: ./perplexity-ft/38564199.txt
Deleted file: ./perplexity-ft/31816503.txt
Deleted file: ./perplexity-ft/33285711.txt
Deleted file: ./perplexity-ft/31405148.txt
Deleted file: ./perplexity-ft/33142939.txt
Deleted file: ./perplexity-ft/33772335.txt
Deleted file: ./perplexity-ft/33500958.txt
Deleted file: ./perplexity-ft/33067468.txt
Deleted file: ./perplexity-ft/32068890.txt
Deleted file: ./perplexity-ft/34851292.txt
Deleted file: ./perplexity-ft/32542034.txt
Deleted file: ./perplexity-ft/29244902.txt
Deleted file: ./perplexity-ft/32840766.txt
Deleted file: ./perplexity-ft/38538559.txt
Deleted file: ./perplexity-ft/32076662.txt
Deleted file: ./perplexity-ft/31967531.txt
Deleted file: ./perplexity-ft/31267266.txt
Deleted file: ./perplexity-ft/32703973.txt
Deleted file: ./perplexity-ft/31406675.txt
Deleted file: ./perplexity-ft/32464565.txt
Deleted file: ./perplexity-ft/33190462.txt
Deleted file: ./perplexity-ft/30252978.txt
Deleted file: ./perplexity-ft/32071965.txt
Deleted file: ./perplexity-ft/30218900.txt
Deleted file: ./perplexity-ft/32071383.txt
Deleted file: ./perplexity-ft/32467650.txt
Deleted file: ./perplexity-ft/32719123.txt
Deleted file: ./perplexity-ft/31249104.txt
Deleted file: ./perplexity-ft/32287265.txt
Deleted file: ./perplexity-ft/32754898.txt
Deleted file: ./perplexity-ft/30497186.txt
Deleted file: ./perplexity-ft/30461117.txt
Deleted file: ./perplexity-ft/31117509.txt
Deleted file: ./perplexity-ft/32581221.txt
Deleted file: ./perplexity-ft/33658605.txt
Deleted file: ./perplexity-ft/32749585.txt
Deleted file: ./perplexity-ft/32304875.txt
Deleted file: ./perplexity-ft/31009356.txt
Deleted file: ./perplexity-ft/32571904.txt
Deleted file: ./perplexity-ft/32662055.txt
Deleted file: ./perplexity-ft/38747976.txt
Deleted file: ./perplexity-ft/38542033.txt
Deleted file: ./perplexity-ft/33224912.txt
Deleted file: ./perplexity-ft/31171447.txt
Deleted file: ./perplexity-ft/31174510.txt
Deleted file: ./perplexity-ft/33216001.txt
Deleted file: ./perplexity-ft/32111185.txt
Deleted file: ./perplexity-ft/32235059.txt
Deleted file: ./perplexity-ft/31317178.txt
Deleted file: ./perplexity-ft/32222642.txt
Deleted file: ./perplexity-ft/31208434.txt
Deleted file: ./perplexity-ft/32079905.txt
Deleted file: ./perplexity-ft/32658741.txt
Deleted file: ./perplexity-ft/33122735.txt
Deleted file: ./perplexity-ft/33955603.txt
Deleted file: ./perplexity-ft/31176387.txt
Deleted file: ./perplexity-ft/32597194.txt
Deleted file: ./perplexity-ft/32688204.txt
Deleted file: ./perplexity-ft/33033492.txt
Deleted file: ./perplexity-ft/36050434.txt
Deleted file: ./perplexity-ft/33205591.txt
Deleted file: ./perplexity-ft/33298128.txt
Deleted file: ./perplexity-ft/31772171.txt
Deleted file: ./perplexity-ft/38617584.txt
Deleted file: ./perplexity-ft/34181661.txt
Deleted file: ./perplexity-ft/31326191.txt
Deleted file: ./perplexity-ft/30807586.txt
Deleted file: ./perplexity-ft/30010088.txt
Deleted file: ./perplexity-ft/36810139.txt
Deleted file: ./perplexity-ft/31655198.txt
Deleted file: ./perplexity-ft/31337542.txt
Deleted file: ./perplexity-ft/30992063.txt
Deleted file: ./perplexity-ft/31479590.txt
Deleted file: ./perplexity-ft/32379801.txt
Deleted file: ./perplexity-ft/36284402.txt
Deleted file: ./perplexity-ft/32583617.txt
Deleted file: ./perplexity-ft/33262083.txt
Deleted file: ./perplexity-ft/38520921.txt
Deleted file: ./perplexity-ft/32627049.txt
Deleted file: ./perplexity-ft/33075658.txt
Deleted file: ./perplexity-ft/31798403.txt
Deleted file: ./perplexity-ft/31955415.txt
Deleted file: ./perplexity-ft/32862015.txt
Deleted file: ./perplexity-ft/32623366.txt
Deleted file: ./perplexity-ft/31787423.txt
Deleted file: ./perplexity-ft/32750012.txt
Deleted file: ./perplexity-ft/33075640.txt
Deleted file: ./perplexity-ft/37658890.txt
Deleted file: ./perplexity-ft/33246080.txt
Deleted file: ./perplexity-ft/38762552.txt
Deleted file: ./perplexity-ft/33182258.txt
Deleted file: ./perplexity-ft/31964625.txt
Deleted file: ./perplexity-ft/32853182.txt
Deleted file: ./perplexity-ft/33070051.txt
Deleted file: ./perplexity-ft/33280248.txt
Deleted file: ./perplexity-ft/33767948.txt
Deleted file: ./perplexity-ft/33359305.txt
Deleted file: ./perplexity-ft/38575814.txt
Deleted file: ./perplexity-ft/33280549.txt
Deleted file: ./perplexity-ft/30209345.txt
Deleted file: ./perplexity-ft/31885041.txt
Deleted file: ./perplexity-ft/38531844.txt
Deleted file: ./perplexity-ft/32610095.txt
Deleted file: ./perplexity-ft/32649890.txt
Deleted file: ./perplexity-ft/32920800.txt
Deleted file: ./perplexity-ft/29321970.txt
Deleted file: ./perplexity-ft/32039500.txt
Deleted file: ./perplexity-ft/32616912.txt
Deleted file: ./perplexity-ft/31847220.txt
Deleted file: ./perplexity-ft/30216352.txt
Deleted file: ./perplexity-ft/35269470.txt
Deleted file: ./perplexity-ft/33118957.txt
Deleted file: ./perplexity-ft/32410265.txt
Deleted file: ./perplexity-ft/33951562.txt
Deleted file: ./perplexity-ft/31286534.txt
Deleted file: ./perplexity-ft/33169409.txt
Deleted file: ./perplexity-ft/32217212.txt
Deleted file: ./perplexity-ft/32941770.txt
Deleted file: ./perplexity-ft/32908645.txt
Deleted file: ./perplexity-ft/32399513.txt
Deleted file: ./perplexity-ft/37624384.txt
Deleted file: ./perplexity-ft/33125268.txt
Deleted file: ./perplexity-ft/29973250.txt
Deleted file: ./perplexity-ft/30243203.txt
Deleted file: ./perplexity-ft/32220502.txt
Deleted file: ./perplexity-ft/32767763.txt
Deleted file: ./perplexity-ft/33760390.txt
Deleted file: ./perplexity-ft/30020426.txt
Deleted file: ./perplexity-ft/32834174.txt
Deleted file: ./perplexity-ft/30734544.txt
Deleted file: ./perplexity-ft/32445550.txt
Deleted file: ./perplexity-ft/32746967.txt
Deleted file: ./perplexity-ft/31285340.txt
Deleted file: ./perplexity-ft/32582542.txt
Deleted file: ./perplexity-ft/38539074.txt
Deleted file: ./perplexity-ft/32818081.txt
Deleted file: ./perplexity-ft/38446766.txt
Deleted file: ./perplexity-ft/31332903.txt
Deleted file: ./perplexity-ft/28756487.txt
Deleted file: ./perplexity-ft/32433583.txt
Deleted file: ./perplexity-ft/30154742.txt
Deleted file: ./perplexity-ft/29980214.txt
Deleted file: ./perplexity-ft/36756643.txt
Deleted file: ./perplexity-ft/38260634.txt
Deleted file: ./perplexity-ft/29766490.txt
Deleted file: ./perplexity-ft/29407288.txt
Deleted file: ./perplexity-ft/28696831.txt
Deleted file: ./perplexity-ft/32915810.txt
Deleted file: ./perplexity-ft/33064342.txt
Deleted file: ./perplexity-ft/31835700.txt
Deleted file: ./perplexity-ft/29854259.txt
Deleted file: ./perplexity-ft/29886268.txt
Deleted file: ./perplexity-ft/30745169.txt
Deleted file: ./perplexity-ft/32719375.txt
Deleted file: ./perplexity-ft/32987299.txt
Deleted file: ./perplexity-ft/33177493.txt
Deleted file: ./perplexity-ft/31268541.txt
Deleted file: ./perplexity-ft/38574756.txt
Deleted file: ./perplexity-ft/32025015.txt
Deleted file: ./perplexity-ft/32181922.txt
Deleted file: ./perplexity-ft/30216140.txt
Deleted file: ./perplexity-ft/33240071.txt
Deleted file: ./perplexity-ft/34362709.txt
Deleted file: ./perplexity-ft/32594794.txt
Deleted file: ./perplexity-ft/32463180.txt
Deleted file: ./perplexity-ft/33193341.txt
Deleted file: ./perplexity-ft/31369338.txt
Deleted file: ./perplexity-ft/35469087.txt
Deleted file: ./perplexity-ft/31318894.txt
Deleted file: ./perplexity-ft/33159092.txt
Deleted file: ./perplexity-ft/32387817.txt
Deleted file: ./perplexity-ft/32441656.txt
Deleted file: ./perplexity-ft/29272464.txt
Deleted file: ./perplexity-ft/29606521.txt
Deleted file: ./perplexity-ft/30216362.txt
Deleted file: ./perplexity-ft/38519152.txt
Deleted file: ./perplexity-ft/32144629.txt
Deleted file: ./perplexity-ft/31856806.txt
Deleted file: ./perplexity-ft/31138084.txt
Deleted file: ./perplexity-ft/32130646.txt
Deleted file: ./perplexity-ft/38621801.txt
Deleted file: ./perplexity-ft/32972660.txt
Deleted file: ./perplexity-ft/32326349.txt
Deleted file: ./perplexity-ft/30135484.txt
Deleted file: ./perplexity-ft/33289519.txt
Deleted file: ./perplexity-ft/32704450.txt
Deleted file: ./perplexity-ft/33956971.txt
Deleted file: ./perplexity-ft/32192211.txt
Deleted file: ./perplexity-ft/34522068.txt
Deleted file: ./perplexity-ft/32651401.txt
Deleted file: ./perplexity-ft/32407457.txt
Deleted file: ./perplexity-ft/32409715.txt
Deleted file: ./perplexity-ft/32317241.txt
Deleted file: ./perplexity-ft/31558433.txt
Deleted file: ./perplexity-ft/38450221.txt
Deleted file: ./perplexity-ft/38532639.txt
Deleted file: ./perplexity-ft/33940534.txt
Deleted file: ./perplexity-ft/32701655.txt
Deleted file: ./perplexity-ft/37787678.txt
Deleted file: ./perplexity-ft/38544181.txt
Deleted file: ./perplexity-ft/32319263.txt
Deleted file: ./perplexity-ft/32681101.txt
Deleted file: ./perplexity-ft/29398207.txt
Deleted file: ./perplexity-ft/29288983.txt
Deleted file: ./perplexity-ft/30170769.txt
Deleted file: ./perplexity-ft/31093956.txt
Deleted file: ./perplexity-ft/33247597.txt
Deleted file: ./perplexity-ft/30560362.txt
Deleted file: ./perplexity-ft/33336385.txt
Deleted file: ./perplexity-ft/31730620.txt
Deleted file: ./perplexity-ft/36055201.txt
Deleted file: ./perplexity-ft/31285702.txt
Deleted file: ./perplexity-ft/33205549.txt
Deleted file: ./perplexity-ft/37761350.txt
Deleted file: ./perplexity-ft/32580177.txt
Deleted file: ./perplexity-ft/30563267.txt
Deleted file: ./perplexity-ft/31989163.txt
Deleted file: ./perplexity-ft/38547927.txt

In [26]:
import os
import json

def extract_json_objects_from_text(text):
    json_objects = []
    while True:
        # Find the first '{' and the last '}'
        start_index = text.find('{')
        end_index = text.rfind('}')

        if start_index == -1 or end_index == -1 or start_index > end_index:
            break

        # Extract the substring from the first '{' to the last '}'
        json_str = text[start_index:end_index + 1]

        # Try to parse the extracted substring as JSON
        try:
            json_object = json.loads(json_str)
            json_objects.append(json_object)
            # Remove the processed part of the text
            text = text[end_index + 1:]
        except json.JSONDecodeError:
            # If parsing fails, continue searching in the remaining text
            text = text[end_index + 1:]

    return json_objects

def extract_json_objects_from_txt(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
    return extract_json_objects_from_text(content)

def read_json_from_folder(folder_path):
    all_json_objects = []
    for file_name in os.listdir(folder_path):
        if file_name.endswith('.txt'):
            file_path = os.path.join(folder_path, file_name)
            json_objects = extract_json_objects_from_txt(file_path)
            # If no JSON objects were found, add an empty object
            if not json_objects:
                json_objects.append({})
            # Add the JSON objects with the corresponding PID (file name without extension)
            for json_object in json_objects:
                pid = os.path.splitext(file_name)[0]
                all_json_objects.append({'pid': pid, 'data': json_object})
    return all_json_objects

# Example usage
folder_path = './perplexity-ft/'
json_array = read_json_from_folder(folder_path)
print(json_array)

[{'pid': '30659193', 'data': {'Total Dataset Size': {'Number of Records/Samples': 174, 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 'Not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Singapore and Taiwan', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Neuroimaging (fMRI)', 'Combination of Modalities': 'Single modality', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Not specified', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Ensemble learning', 'Model Architecture': 'Stacked predictions from multiple models', 'Training Techniques': 'Not specified', 'Performance Metrics': {'Accuracy': '87%', 'Other Metrics': 'Not specified'}}, 'Number of Collaborators': {'Number of Institutions': 5, 'Geographical Distribution': ['Singapore', 'Taiwan'], 'Roles': ['Data providers', 'Algorithm developers', 'Model trainers']}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Not specified', 'Population Diversity': 'Not specified', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '32379801', 'data': {'Total Dataset Size': {'Number of Records/Samples': 13, 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 'Not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Healthy male subjects', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Sensor data (marker trajectories)', 'Combination of Modalities': 'No', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Not specified', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Artificial neural network', 'Model Architecture': 'Not specified', 'Training Techniques': 'Not specified', 'Performance Metrics': 'Average error < 0.6 mm'}, 'Number of Collaborators': {'Number of Institutions': 'Not specified', 'Geographical Distribution': 'Not specified', 'Roles': 'Not specified'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Not specified', 'Population Diversity': 'Healthy male subjects', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Open access'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '35717344', 'data': {}}, {'pid': '35841241', 'data': {}}, {'pid': '33857785', 'data': {}}, {'pid': '33066454', 'data': {'Total Dataset Size': {'Number of Records/Samples': 1112, 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 'Not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Autism Brain Imaging Data Exchange (ABIDE)', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Imaging (rs-fMRI)', 'Combination of Modalities': 'No', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Not specified', 'Feature Selection Methods': 'Autoencoder'}, 'AI Methods': {'Specific Algorithms': 'Autoencoder, Convolutional Neural Networks (CNN)', 'Model Architecture': 'Autoencoder combined with CNN', 'Training Techniques': 'Not specified', 'Performance Metrics': {'Accuracy': 84.05, 'AUC': 0.78}}, 'Number of Collaborators': {'Number of Institutions': 'Not specified', 'Geographical Distribution': 'Not specified', 'Roles': 'Not specified'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Single source (ABIDE)', 'Population Diversity': 'Not specified', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '30060575', 'data': {}}, {'pid': '29801696', 'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not provided', 'Size in GB/TB': 'Exact size not provided', 'Number of Data Points per Sample': 'Average not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Specific institutions not detailed', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': ['Plain text', 'Structured data on primary hypertension'], 'Combination of Modalities': 'Yes, multimodal learning', 'Data Format': ['Structured', 'Unstructured']}, 'Number of Features in Datasets': {'Feature Count': 'Exact number not provided', 'Feature Types': ['Categorical', 'Numerical'], 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': ['Deep Belief Network', 'Support Vector Machine'], 'Model Architecture': 'Seven-layer deep belief network', 'Training Techniques': ['Unsupervised learning', 'Supervised learning'], 'Performance Metrics': ['Mean', 'Variance', 'Average precision', 'Coverage']}, 'Number of Collaborators': {'Number of Institutions': 'Count not specified', 'Geographical Distribution': 'Not detailed', 'Roles': ['Data providers', 'Algorithm developers', 'Model trainers']}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not mentioned', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not mentioned'}, 'Data Heterogeneity': {'Source Diversity': 'Not specified', 'Population Diversity': 'Not detailed', 'Consistency Across Datasets': 'Measures not mentioned'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not mentioned', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not mentioned', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not detailed'}}}, {'pid': '29454222', 'data': {'Total Dataset Size': {'Number of Records/Samples': 338, 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 'Not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Multiple institutions across various countries', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Imaging (MRI), clinical data', 'Combination of Modalities': 'Yes, multimodal learning', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Categorical, numerical', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Machine learning, regression analysis', 'Model Architecture': 'Not specified', 'Training Techniques': 'Not specified', 'Performance Metrics': 'Not specified'}, 'Number of Collaborators': {'Number of Institutions': 'Multiple', 'Geographical Distribution': 'Various countries', 'Roles': 'Data providers, algorithm developers'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Multiple hospitals and clinics', 'Population Diversity': 'Diverse patient demographics', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Consortium-based', 'Data Accessibility': 'Restricted access'}, 'Ethical Considerations': {'Ethical Approvals': 'Approved by ethics committees', 'Informed Consent': 'Obtained from participants', 'Bias Mitigation': 'Not specified'}}}, {'pid': '36329531', 'data': {'Total Dataset Size': {'Number of Records/Samples': 57, 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 'Not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'The Cancer Genome Atlas and other datasets', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Genomic', 'Combination of Modalities': 'No', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 207, 'Feature Types': 'Categorical, numerical', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Random Forests', 'Model Architecture': 'Not specified', 'Training Techniques': 'Ensemble learning', 'Performance Metrics': 'Accuracy, MCC, ROC AUC'}, 'Number of Collaborators': {'Number of Institutions': 'Not specified', 'Geographical Distribution': 'Not specified', 'Roles': 'Data providers, algorithm developers'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Not specified', 'Population Diversity': 'Not specified', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '37095759', 'data': {}}, {'pid': '34766125', 'data': {}}, {'pid': '33802753', 'data': {}}, {'pid': '31154512', 'data': {'Total Dataset Size': {'Number of Records/Samples': '12', 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 'Not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Not specified', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Gait acceleration (ACC), electroencephalogram (EEG), electromyogram (EMG), skin conductance (SC)', 'Combination of Modalities': 'Yes', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': '16', 'Feature Types': 'Not specified', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Long Short-Term Memory (LSTM)', 'Model Architecture': 'Not specified', 'Training Techniques': 'Leave-one-freezer-out cross validation', 'Performance Metrics': {'Accuracy': 'Not specified', 'Precision': 'Not specified', 'Recall': 'Not specified', 'F1 score': 'Not specified', 'AUC': 'Not specified'}}, 'Number of Collaborators': {'Number of Institutions': 'Not specified', 'Geographical Distribution': 'Not specified', 'Roles': 'Not specified'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Not specified', 'Population Diversity': 'Not specified', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '35951085', 'data': {}}, {'pid': '32992069', 'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not specified', 'Size in GB/TB': 'Physical size not specified', 'Number of Data Points per Sample': 'Average number not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Not specified', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Linguistic, morphological', 'Combination of Modalities': 'Multimodal learning used', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Categorical, numerical', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Deep learning, support vector machines', 'Model Architecture': 'Not specified', 'Training Techniques': 'Not specified', 'Performance Metrics': 'Not specified'}, 'Number of Collaborators': {'Number of Institutions': 'Not specified', 'Geographical Distribution': 'Not specified', 'Roles': 'Not specified'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Not specified', 'Population Diversity': 'Not specified', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '38784249', 'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not specified', 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 'Not specified'}, 'Data Collection Method': {'Type': 'Not specified', 'Source of Data': 'Not specified', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Not specified', 'Combination of Modalities': 'Not specified', 'Data Format': 'Not specified'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Not specified', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Boosted trees (XGBoost)', 'Model Architecture': 'Not specified', 'Training Techniques': 'Not specified', 'Performance Metrics': 'Not specified'}, 'Number of Collaborators': {'Number of Institutions': 4, 'Geographical Distribution': 'Iran, Canada', 'Roles': 'Data providers, algorithm developers, model trainers'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Not specified', 'Population Diversity': 'Not specified', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '35294251', 'data': {}}, {'pid': '37264917', 'data': {}}, {'pid': '34048901', 'data': {}}, {'pid': '30630441', 'data': {'Total Dataset Size': {'Number of Records/Samples': '300 to 3000 participants per city', 'Size in GB/TB': '100 TB', 'Number of Data Points per Sample': 'Varies based on surveys and sensor data'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Four Canadian cities (Vancouver, Victoria, Saskatoon, Montreal)', 'Timeframe of Data Collection': 'Over 5 years'}, 'Data Modalities': {'Type of Data': 'Sensor-based location and physical activity data, health and activity space surveys', 'Combination of Modalities': 'Yes, multimodal data collection', 'Data Format': 'Structured and unstructured'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Categorical, numerical, text', 'Feature Selection Methods': 'Machine learning methods'}, 'AI Methods': {'Specific Algorithms': 'Machine learning methods for detecting transportation mode use and physical activity', 'Model Architecture': 'Not specified', 'Training Techniques': 'Not specified', 'Performance Metrics': 'Not specified'}, 'Number of Collaborators': {'Number of Institutions': 'Approximately 230 partnering organizations', 'Geographical Distribution': 'Canada', 'Roles': 'Interdisciplinary scientists, urban planners, public health decision makers'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Ethics approval from multiple institutions', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Various urban interventions in different cities', 'Population Diversity': 'Adult participants aged 18 or older', 'Consistency Across Datasets': 'Standardized data collection methods'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Consortium-based', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Received from ethics boards of Simon Fraser University and University of Saskatchewan', 'Informed Consent': 'Obtained from participants', 'Bias Mitigation': 'Not specified'}}}, {'pid': '38497716', 'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not provided', 'Size in GB/TB': 'Physical size not provided', 'Number of Data Points per Sample': 'Average not specified'}, 'Data Collection Method': {'Type': 'Centralized', 'Source of Data': 'Kazakhstan and South America', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Mass spectrometry data', 'Combination of Modalities': 'Not specified', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 'Not specified', 'Feature Types': 'Not specified', 'Feature Selection Methods': 'Not specified'}, 'AI Methods': {'Specific Algorithms': 'Machine learning algorithms', 'Model Architecture': 'Not specified', 'Training Techniques': 'Not specified', 'Performance Metrics': 'Accuracy of 98.3%, PPA of 100%, NPA of 96%'}, 'Number of Collaborators': {'Number of Institutions': 6, 'Geographical Distribution': 'Kazakhstan, South America', 'Roles': 'Data providers, algorithm developers'}, 'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified', 'Compliance with Regulations': 'Not specified', 'Data Anonymization': 'Not specified'}, 'Data Heterogeneity': {'Source Diversity': 'Hospitals and research centers', 'Population Diversity': 'Not specified', 'Consistency Across Datasets': 'Not specified'}, 'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified', 'Collaboration Models': 'Not specified', 'Data Accessibility': 'Not specified'}, 'Ethical Considerations': {'Ethical Approvals': 'Not specified', 'Informed Consent': 'Not specified', 'Bias Mitigation': 'Not specified'}}}, {'pid': '37847539', 'data': {}}, {'pid': '37956346', 'data': {}}, {'pid': '36948537', 'data': {}}, {'pid': '38774435', 'data': {}}, {'pid': '32179311', 'data': {'Total Dataset Size': {'Number of Records/Samples': 'Not specified', 'Size in GB/TB': 'Not specified', 'Number of Data Points per Sample': 55}, 'Data Collection Method': {'Type': 'Not specified', 'Source of Data': 'Z-Alizadeh Sani dataset', 'Timeframe of Data Collection': 'Not specified'}, 'Data Modalities': {'Type of Data': 'Clinical data', 'Combination of Modalities': 'Not specified', 'Data Format': 'Structured'}, 'Number of Features in Datasets': {'Feature Count': 55, 'Feature Types': 'Numerical and categorical', 'Feature Selection Methods': 'Pearson correlation feature selection'}, 'AI Methods': {'Specific Algorithms': ['CART', 'Random Forest', 'Support Vector Machines', 'Logistic Regression', 'Deep Learning', 'XGBoost'], 'Model Architecture': 'Not

In [29]:
json_array

[{'pid': '30659193',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 174,
    'Size in GB/TB': 'Not specified',
    'Number of Data Points per Sample': 'Not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Singapore and Taiwan',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Neuroimaging (fMRI)',
    'Combination of Modalities': 'Single modality',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Not specified',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Ensemble learning',
    'Model Architecture': 'Stacked predictions from multiple models',
    'Training Techniques': 'Not specified',
    'Performance Metrics': {'Accuracy': '87%',
     'Other Metrics': 'Not specified'}},
   'Number of Collaborators': {'Number of Institutions': 5,
    'Geographical Distribution': ['Singapore', 'Taiwan'],
    'Roles': ['Data providers', 'Algorithm developers', 'Model trainers']},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Not specified',
    'Population Diversity': 'Not specified',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not specified',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Not specified',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '32379801',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 13,
    'Size in GB/TB': 'Not specified',
    'Number of Data Points per Sample': 'Not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Healthy male subjects',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Sensor data (marker trajectories)',
    'Combination of Modalities': 'No',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Not specified',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Artificial neural network',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Not specified',
    'Performance Metrics': 'Average error < 0.6 mm'},
   'Number of Collaborators': {'Number of Institutions': 'Not specified',
    'Geographical Distribution': 'Not specified',
    'Roles': 'Not specified'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Not specified',
    'Population Diversity': 'Healthy male subjects',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not specified',
    'Data Accessibility': 'Open access'},
   'Ethical Considerations': {'Ethical Approvals': 'Not specified',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '35717344', 'data': {}},
 {'pid': '35841241', 'data': {}},
 {'pid': '33857785', 'data': {}},
 {'pid': '33066454',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 1112,
    'Size in GB/TB': 'Not specified',
    'Number of Data Points per Sample': 'Not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Autism Brain Imaging Data Exchange (ABIDE)',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Imaging (rs-fMRI)',
    'Combination of Modalities': 'No',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Not specified',
    'Feature Selection Methods': 'Autoencoder'},
   'AI Methods': {'Specific Algorithms': 'Autoencoder, Convolutional Neural Networks (CNN)',
    'Model Architecture': 'Autoencoder combined with CNN',
    'Training Techniques': 'Not specified',
    'Performance Metrics': {'Accuracy': 84.05, 'AUC': 0.78}},
   'Number of Collaborators': {'Number of Institutions': 'Not specified',
    'Geographical Distribution': 'Not specified',
    'Roles': 'Not specified'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Single source (ABIDE)',
    'Population Diversity': 'Not specified',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not specified',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Not specified',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '30060575', 'data': {}},
 {'pid': '29801696',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not provided',
    'Size in GB/TB': 'Exact size not provided',
    'Number of Data Points per Sample': 'Average not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Specific institutions not detailed',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': ['Plain text',
     'Structured data on primary hypertension'],
    'Combination of Modalities': 'Yes, multimodal learning',
    'Data Format': ['Structured', 'Unstructured']},
   'Number of Features in Datasets': {'Feature Count': 'Exact number not provided',
    'Feature Types': ['Categorical', 'Numerical'],
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': ['Deep Belief Network',
     'Support Vector Machine'],
    'Model Architecture': 'Seven-layer deep belief network',
    'Training Techniques': ['Unsupervised learning', 'Supervised learning'],
    'Performance Metrics': ['Mean',
     'Variance',
     'Average precision',
     'Coverage']},
   'Number of Collaborators': {'Number of Institutions': 'Count not specified',
    'Geographical Distribution': 'Not detailed',
    'Roles': ['Data providers', 'Algorithm developers', 'Model trainers']},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not mentioned',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not mentioned'},
   'Data Heterogeneity': {'Source Diversity': 'Not specified',
    'Population Diversity': 'Not detailed',
    'Consistency Across Datasets': 'Measures not mentioned'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not mentioned',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Not mentioned',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not detailed'}}},
 {'pid': '29454222',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 338,
    'Size in GB/TB': 'Not specified',
    'Number of Data Points per Sample': 'Not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Multiple institutions across various countries',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Imaging (MRI), clinical data',
    'Combination of Modalities': 'Yes, multimodal learning',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Categorical, numerical',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Machine learning, regression analysis',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Not specified',
    'Performance Metrics': 'Not specified'},
   'Number of Collaborators': {'Number of Institutions': 'Multiple',
    'Geographical Distribution': 'Various countries',
    'Roles': 'Data providers, algorithm developers'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Multiple hospitals and clinics',
    'Population Diversity': 'Diverse patient demographics',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Consortium-based',
    'Data Accessibility': 'Restricted access'},
   'Ethical Considerations': {'Ethical Approvals': 'Approved by ethics committees',
    'Informed Consent': 'Obtained from participants',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '36329531',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 57,
    'Size in GB/TB': 'Not specified',
    'Number of Data Points per Sample': 'Not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'The Cancer Genome Atlas and other datasets',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Genomic',
    'Combination of Modalities': 'No',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': 207,
    'Feature Types': 'Categorical, numerical',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Random Forests',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Ensemble learning',
    'Performance Metrics': 'Accuracy, MCC, ROC AUC'},
   'Number of Collaborators': {'Number of Institutions': 'Not specified',
    'Geographical Distribution': 'Not specified',
    'Roles': 'Data providers, algorithm developers'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Not specified',
    'Population Diversity': 'Not specified',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not specified',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Not specified',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '37095759', 'data': {}},
 {'pid': '34766125', 'data': {}},
 {'pid': '33802753', 'data': {}},
 {'pid': '31154512',
  'data': {'Total Dataset Size': {'Number of Records/Samples': '12',
    'Size in GB/TB': 'Not specified',
    'Number of Data Points per Sample': 'Not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Not specified',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Gait acceleration (ACC), electroencephalogram (EEG), electromyogram (EMG), skin conductance (SC)',
    'Combination of Modalities': 'Yes',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': '16',
    'Feature Types': 'Not specified',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Long Short-Term Memory (LSTM)',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Leave-one-freezer-out cross validation',
    'Performance Metrics': {'Accuracy': 'Not specified',
     'Precision': 'Not specified',
     'Recall': 'Not specified',
     'F1 score': 'Not specified',
     'AUC': 'Not specified'}},
   'Number of Collaborators': {'Number of Institutions': 'Not specified',
    'Geographical Distribution': 'Not specified',
    'Roles': 'Not specified'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Not specified',
    'Population Diversity': 'Not specified',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not specified',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Not specified',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '35951085', 'data': {}},
 {'pid': '32992069',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not specified',
    'Size in GB/TB': 'Physical size not specified',
    'Number of Data Points per Sample': 'Average number not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Not specified',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Linguistic, morphological',
    'Combination of Modalities': 'Multimodal learning used',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Categorical, numerical',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Deep learning, support vector machines',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Not specified',
    'Performance Metrics': 'Not specified'},
   'Number of Collaborators': {'Number of Institutions': 'Not specified',
    'Geographical Distribution': 'Not specified',
    'Roles': 'Not specified'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Not specified',
    'Population Diversity': 'Not specified',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not specified',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Not specified',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '38784249',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not specified',
    'Size in GB/TB': 'Not specified',
    'Number of Data Points per Sample': 'Not specified'},
   'Data Collection Method': {'Type': 'Not specified',
    'Source of Data': 'Not specified',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Not specified',
    'Combination of Modalities': 'Not specified',
    'Data Format': 'Not specified'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Not specified',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Boosted trees (XGBoost)',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Not specified',
    'Performance Metrics': 'Not specified'},
   'Number of Collaborators': {'Number of Institutions': 4,
    'Geographical Distribution': 'Iran, Canada',
    'Roles': 'Data providers, algorithm developers, model trainers'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Not specified',
    'Population Diversity': 'Not specified',
    'Consistency Across Datasets': 'Not specified'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Not specified',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Not specified',
    'Informed Consent': 'Not specified',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '35294251', 'data': {}},
 {'pid': '37264917', 'data': {}},
 {'pid': '34048901', 'data': {}},
 {'pid': '30630441',
  'data': {'Total Dataset Size': {'Number of Records/Samples': '300 to 3000 participants per city',
    'Size in GB/TB': '100 TB',
    'Number of Data Points per Sample': 'Varies based on surveys and sensor data'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Four Canadian cities (Vancouver, Victoria, Saskatoon, Montreal)',
    'Timeframe of Data Collection': 'Over 5 years'},
   'Data Modalities': {'Type of Data': 'Sensor-based location and physical activity data, health and activity space surveys',
    'Combination of Modalities': 'Yes, multimodal data collection',
    'Data Format': 'Structured and unstructured'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Categorical, numerical, text',
    'Feature Selection Methods': 'Machine learning methods'},
   'AI Methods': {'Specific Algorithms': 'Machine learning methods for detecting transportation mode use and physical activity',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Not specified',
    'Performance Metrics': 'Not specified'},
   'Number of Collaborators': {'Number of Institutions': 'Approximately 230 partnering organizations',
    'Geographical Distribution': 'Canada',
    'Roles': 'Interdisciplinary scientists, urban planners, public health decision makers'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Ethics approval from multiple institutions',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Various urban interventions in different cities',
    'Population Diversity': 'Adult participants aged 18 or older',
    'Consistency Across Datasets': 'Standardized data collection methods'},
   'Data Sharing and Collaboration Mechanisms': {'Platforms Used': 'Not specified',
    'Collaboration Models': 'Consortium-based',
    'Data Accessibility': 'Not specified'},
   'Ethical Considerations': {'Ethical Approvals': 'Received from ethics boards of Simon Fraser University and University of Saskatchewan',
    'Informed Consent': 'Obtained from participants',
    'Bias Mitigation': 'Not specified'}}},
 {'pid': '38497716',
  'data': {'Total Dataset Size': {'Number of Records/Samples': 'Exact count not provided',
    'Size in GB/TB': 'Physical size not provided',
    'Number of Data Points per Sample': 'Average not specified'},
   'Data Collection Method': {'Type': 'Centralized',
    'Source of Data': 'Kazakhstan and South America',
    'Timeframe of Data Collection': 'Not specified'},
   'Data Modalities': {'Type of Data': 'Mass spectrometry data',
    'Combination of Modalities': 'Not specified',
    'Data Format': 'Structured'},
   'Number of Features in Datasets': {'Feature Count': 'Not specified',
    'Feature Types': 'Not specified',
    'Feature Selection Methods': 'Not specified'},
   'AI Methods': {'Specific Algorithms': 'Machine learning algorithms',
    'Model Architecture': 'Not specified',
    'Training Techniques': 'Not specified',
    'Performance Metrics': 'Accuracy of 98.3%, PPA of 100%, NPA of 96%'},
   'Number of Collaborators': {'Number of Institutions': 6,
    'Geographical Distribution': 'Kazakhstan, South America',
    'Roles': 'Data providers, algorithm developers'},
   'Data Privacy Techniques': {'Privacy-Preserving Methods': 'Not specified',
    'Compliance with Regulations': 'Not specified',
    'Data Anonymization': 'Not specified'},
   'Data Heterogeneity': {'Source Diversity': 'Hospitals and research centers',

In [30]:
import json
import psycopg2

# Connect to PostgreSQL
conn = psycopg2.connect(
    dbname="postgres",
    user="postgres",
    password="yum",
    host="localhost",
    port="5432"
)
cursor = conn.cursor()

# Insert data into the table
for record in json_array:
    cursor.execute(
        """
        INSERT INTO perplexity (pid, data)
        VALUES (%s, %s::jsonb)
        """,
         (record['pid'], json.dumps(record['data']))
    )

# Commit the transaction and close the connection
conn.commit()
cursor.close()
conn.close()

In [35]:
! pip install pandas scikit-learn nltk

Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: scikit-learn in /opt/homebrew/anaconda3/lib/python3.12/site-packages (1.4.2)
Requirement already satisfied: nltk in /opt/homebrew/anaconda3/lib/python3.12/site-packages (3.8.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.6.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: click in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from nltk) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from nltk) (4.66.4)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [33]:
file_path = 'data-full-text.csv'  # Replace with your actual file path
canada_df = pd.read_csv(file_path)
canada_df

           pid                                              title
0     29609039  Computer-aided diagnosis of cavernous malforma...
1     29616521  The relationship between cerebral oxygen satur...
2     29632364  Multimodal and Multiscale Deep Neural Networks...
3     29636016  Machine learning classification of first-episo...
4     29642656  Socioeconomic disparities and difficulties to ...
...        ...                                                ...
3524  39001096  Derivative Method to Detect Sleep and Awake St...
3525  39001410  Deep Learning Algorithms for Bladder Cancer Se...
3526  39002043  Predictors of High Healthcare Cost Among Patie...
3527  39012781  Short-Term Exposure to Wildfire-Specific PM2.5...
3528  39013639  The performance of digital technologies for me...

[3529 rows x 2 columns]

In [38]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import nltk
from nltk.corpus import stopwords

# Download stopwords
nltk.download('stopwords')

# Load your data
data = canada_df

# Assuming your dataset has a 'text' column that contains the content to analyze
texts = data['title'].fillna('')  # Fill NaNs with empty strings

# Preprocess the text
stop_words = stopwords.words('english')  # Use a list instead of a set
vectorizer = TfidfVectorizer(stop_words=stop_words)
X = vectorizer.fit_transform(texts)

# Fit the KMeans model
num_clusters = 15  # Change this based on your needs
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(X)

# Assign cluster labels back to the original DataFrame
data['theme'] = kmeans.labels_

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/yumcoder/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [6]:
import pandas as pd
file_path = './data-modalities-usa.csv'  # Replace with your actual file path
data = pd.read_csv(file_path)
data

,pid,modalities,modalities2,x
0,28952798,{Medical},"{Blood,Pressure,Systolic,BP,Diastolic,BP}","{Blood,BP,Diastolic,Medical,Pressure,Systolic}"
1,28968847,{MRI},{MRI},{MRI}
2,28981875,{Nil},"{Text,Audio}","{Audio,Nil,Text}"
3,29194610,"{dental-related,claims}","{topical,fluoride,dental,sealants}","{claims,dental,dental-related,fluoride,sealant..."
4,29251172,"{Gene,expression,profile}","{gene,expression}","{expression,gene,Gene,profile}"
...,...,...,...,...
904,31926806,"{""null"",""null"",""null"",""null"",""null""}",NaN,"{""null""}"
905,38783089,"{cervical,extension,traction,(CET)}",NaN,"{cervical,(CET),extension,traction}"
906,37829182,"{Medical,Imaging,Electronic,Health,Records}",NaN,"{Electronic,Health,Imaging,Medical,Records}"
907,36280681,"{Ultrasound,Clinical}",NaN,"{Clinical,Ultrasound}"
908,31919503,NaN,NaN,{}

In [54]:
import pandas as pd
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import re

stemmer = PorterStemmer()

def normalize_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove non-alphanumeric characters except for whitespace
    text = re.sub(r'[^\w\s]', '', text)
    # Tokenize and stem
    tokens = word_tokenize(text)
    normalized_tokens = [stemmer.stem(token) for token in tokens]
    return ' '.join(normalized_tokens)

def process_names(names):
    if pd.isna(names):
        return []
    # Normalize and split
    names_list = [normalize_text(name.strip()) for name in names.replace('""', '"').split(',')]
    # Remove duplicates and return as a list
    return list(set(names_list))

# Apply the function to the 'x' column
data['unique_names'] = data['x'].apply(process_names)

# Display the DataFrame with the new column
data.head(5)

,pid,countries,x,modalities,modalities2,unique_names
0,28601499,"[""Australia"", ""Canada""]","[""fMRI""], [""fMRI""]","[""fMRI""]","[""fMRI""]",[fmri]
1,28651909,"[""Canada"", ""China""]","[""Computerized Cambridge Neurocognitive Test A...","[""Computerized Cambridge Neurocognitive Test A...","[""cognitive tests""]",[immedi and delay logic memori of the wechsler...
2,28756487,"[""Canada"", ""France"", ""United Kingdom""]","[""anatomical"", ""functional""], [""voice-sensitiv...","[""anatomical"", ""functional""]","[""voice-sensitive cortex"", ""functional voice a...","[anatom, function, function voic activ, voices..."
3,28771699,"[""Brazil"", ""Canada"", ""Israel""]","[""Checkerboard DNA-DNA hybridisation""], [""DNA-...","[""Checkerboard DNA-DNA hybridisation""]","[""DNA-DNA hybridisation""]","[dnadna hybridis, checkerboard dnadna hybridis]"
4,28853237,"[""Canada"", ""Russia""]","[""Optical Coherence Tomography""], [""optical co...","[""Optical Coherence Tomography""]","[""optical coherence tomography""]",[optic coher tomographi]

In [16]:
# for names in data.head(5)['unique_names'].dropna():
#     print(names)  # Update the set with unique names
all_modalities = [modality for sublist in data['unique_names'].dropna() for modality in sublist]
all_modalities

['systol',
 'medic',
 'bp',
 'blood',
 'diastol',
 'pressur',
 'mri',
 'text',
 'nil',
 'audio',
 'fluorid',
 'claim',
 'dentalrel',
 'dental',
 'sealant',
 'topic',
 'gene',
 'express',
 'profil',
 'scale',
 'likert',
 'selfreport',
 'xray',
 'comput',
 'miccai',
 'tomographi',
 'mri',
 'scan',
 'magnet',
 'reson',
 'imag',
 'structur',
 't2weight',
 'mri',
 'weight',
 'diffusionweight',
 't1weight',
 't2',
 'genet',
 'data',
 'sampl',
 'blood',
 'hematolog',
 'mood',
 'energi',
 'physiolog',
 'cancer',
 'tomographi',
 'comput',
 'therapi',
 'prostat',
 'radiat',
 'treatment',
 'mri',
 'magnet',
 'reson',
 'imag',
 'function',
 'audio',
 'methyl',
 'imag',
 'text',
 'dna',
 'vision',
 'feedback',
 'kinesthet',
 'modal',
 'intent',
 'profil',
 'brain',
 'transcript',
 'gene',
 'express',
 'medic',
 'text',
 'imag',
 'freedom',
 'knee',
 'degre',
 '6',
 'robot',
 'of',
 'system',
 'intern',
 'kinemat',
 'tibial',
 'test',
 'rotat',
 'type',
 'microrna',
 'fluid',
 'cerebrospin',
 'level',
 'csf',
 'express',
 'mirna',
 'gene',
 'express',
 'mri',
 'state',
 'wholebrain',
 'volum',
 'matter',
 'function',
 'connect',
 'rest',
 'grey',
 'audio',
 'proteom',
 'data',
 'imag',
 'descript',
 'text',
 'brain',
 'connect',
 'function',
 'imag',
 'imag',
 'cardiolog',
 'mri',
 'ct',
 'numer',
 'text',
 'psycholog',
 'magnet',
 'fmri',
 'reson',
 'data',
 'imag',
 'function',
 'tensor',
 'microstructur',
 'mri',
 'brain',
 'modal',
 'dti',
 'imag',
 'macrostructur',
 'diffus',
 'medic',
 'none',
 '3d',
 'ultrasound',
 'imag',
 'mri',
 'imag',
 'inform',
 'data',
 'tempor',
 'ultrasound',
 'fmri',
 'eeg',
 'magnet',
 'oxygenationleveldepend',
 'bold',
 'blood',
 'rate',
 'reson',
 'stimulu',
 'imag',
 'pain',
 'function',
 'signal',
 'temperatur',
 'depend',
 'bloodoxygenlevel',
 'data',
 'function',
 'signal',
 'connect',
 'spect',
 'imag',
 'mri',
 'ct',
 'true',
 'neuroanatom',
 't1weighted_magnetic_resonance_imag',
 'matur',
 'map',
 'medic',
 'therapi',
 'data',
 'imag',
 'dose',
 '2d',
 'radiat',
 '3d',
 'respons',
 'immunoglobulin',
 'plasma',
 'a',
 'antibodi',
 'institut',
 'school',
 'western',
 'biophys',
 'scienc',
 'on',
 'ontario',
 'univers',
 'health',
 'null',
 'medic',
 'centr',
 'fmri',
 'dentistri',
 'of',
 'research',
 'london',
 'psychiatri',
 'depart',
 'canada',
 'and',
 'lawson',
 'medicin',
 'schulich',
 'electrophysiolog',
 'signal',
 'phase',
 'thorac',
 'genom',
 'audio',
 'magnet',
 'reson',
 'computer',
 'imag',
 'text',
 'tomographi',
 'text',
 'imag',
 'chemic',
 'descriptor',
 'molecular',
 'featur',
 'continu',
 'mri',
 'magnet',
 'fmri',
 'reson',
 'imag',
 'function',
 'structur',
 'mri',
 'metabol',
 'fluorodeoxyglucos',
 'glucos',
 'fdgpet',
 'emiss',
 'imag',
 'positron',
 'tomographi',
 '',
 'depart',
 'vision',
 'vicorob',
 'and',
 'medic',
 'comput',
 'analysi',
 'robot',
 'hospit',
 'of',
 'lab',
 'imag',
 'radiolog',
 'children',
 'in',
 'to',
 'direct',
 'intent',
 'move',
 'neural',
 'a',
 'featur',
 '30t',
 'w',
 't2weight',
 'mri',
 'and',
 'multibvalu',
 'dw',
 'imag',
 'map',
 'sequenc',
 'weight',
 'diffusionweight',
 'coeffici',
 'appar',
 'diffus',
 't2',
 'echocardiographi',
 'medic',
 'clinic',
 'imag',
 'ye',
 'mri',
 'no',
 'ct',
 'imag',
 'echocardiogram',
 'state',
 'mental',
 'gaze',
 'cue',
 'robot',
 'humanoid',
 'imag',
 'histopatholog',
 'data',
 'breathbybreath',
 'timeseri',
 'epidemiolog',
 'genom',
 'rnaseq',
 'spectroscopybas',
 'magnet',
 'chromatographi',
 'coupl',
 'nuclear',
 'with',
 'analysi',
 'reson',
 'proteom',
 'mass',
 'spectrometri',
 'liquid',
 'proton',
 'target',
 'metabolom',
 'movement',
 'acoust',
 'lip',
 'tongu',
 'genet',
 'text',
 'imag',
 'sensit',
 'betacel',
 'insulin',
 'function',
 'mirna',
 'afm',
 'scan',
 'nanoscaleresolut',
 'tap',
 'atom',
 'subreson',
 'microscopi',
 'forc',
 'autom',
 'coher',
 'sap',
 'standard',
 'optic',
 'perimetri',
 'oct',
 'tomographi',
 'registri',
 'text',
 'clinic',
 'medic',
 'mr',
 'imag',
 'angiographi',
 'proteom',
 'tomographi',
 'ct',
 'motor',
 'magnet',
 'network',
 'accuraci',
 'reson',
 'sensori',
 'imag',
 'function',
 'propriocept',
 'reach',
 'variat',
 'copynumb',
 'cell',
 'protein',
 'data',
 'morphometri',
 'gene',
 'express',
 'microarray',
 'text',
 'radiotherapi',
 'imag',
 'count',
 'biochemistri',
 'blood_biochemistri',
 'modal',
 'cell',
 'blood',
 'null',
 'descript',
 'biolog',
 'data',
 'valu',
 'imag',
 'text',
 't1',
 'mri',
 'enhanc',
 'contrast',
 't2flair',
 'vision',
 'algorithm',
 'comput',
 'facial',
 'video',
 'medic',
 'data',
 'clinic',
 'imag',
 'text',
 'health',
 'record',
 'electron',
 'express',
 'transcript',
 'microarray',
 'histolog',
 'molecular',
 'eye',
 'neuroimag',
 'psychometr',
 'movement',
 'test',
 'spect',
 'measur',
 'clinic',
 'imag',
 'medic',
 'electroencephalogram',
 'claim',
 'procedur',
 'methyl',
 'dna',
 'lht',
 'sd',
 'msb',
 'spinal',
 'jcb',
 'rjh',
 'nk',
 'dbm',
 'xdf',
 'af',
 'surgeri',
 'jft',
 'imag',
 'ww',
 'injuri',
 'center',
 'and',
 'brain',
 'neurolog',
 'mri',
 'eeg',
 'medic',
 'electroencephalographi',
 'valu',
 'imag',
 'kurtosi',
 't2weight',
 'magnet',
 'reson',
 'imag',
 'appar',
 'coeffici',
 'diffus',
 'best',
 'glycosyl',
 'stent',
 'medic',
 'creatinin',
 'modal',
 'therapi',
 'dbp',
 'serum',
 'sbp',
 'hemoglobin',
 'genet',
 'neurolog',
 'intraop',
 'ultrasound',
 'mri',
 'movement',
 'complex',
 'robot',
 'light',
 'rob',
 'effect',
 'integr',
 'sound',
 'discuss',
 'interview',
 'questionnair',
 'focu',
 'group',
 'text',
 'dataset',
 'imput',
 'origin',
 'electron',
 '',
 'dermoscop',
 'imag',
 'mri',
 'questionnair',
 'physiolog',
 'ct',
 'data',
 'electrocardiogram',
 'text',
 'neurolog',
 'statu',
 'mri',
 'urin',
 'text',
 'mirna',
 'fingerprint',
 'mri',
 'modal',
 'magnet',
 'reson',
 'clinic',
 'imag',
 'function',
 'symptom',
 'connect',
 'neurolog',
 'disord',
 'imag',
 'movement',
 'text',
 'true',
 'phenotyp',
 'ontolog',
 'hpo',
 'text',
 'term',
 'secretom',
 'semin',
 'protein',
 'proteom',
 'plasma',
 'transcriptom',
 'demograph',
 'occup',
 'text',
 'clinic',
 '',
 'yale',
 'name',
 'and',
 'univers',
 'medic',
 'brigham',
 'hospit',
 'center',
 'women',
 'descript',
 'cedarssinai',
 'pallidu',
 'respons',
 'field',
 'fire',
 'modal',
 'electrophysiolog',
 'interna',
 'rate',
 'singl',
 'globu',
 'unit',
 'neural',
 'potenti',
 'local',
 'medic',
 'data',
 'clinic',
 'imag',
 'text',
 'registri',
 'map',
 'heat',
 'data',
 'text',
 'leveldepend',
 'magnet',
 'bold',
 'blood',
 'fmri',
 'reson',
 'oxygen',
 'imag',
 'function',
 'signal',
 'mr',
 'mri',
 'imag',
 'pet',
 'ct',
 'monocyt',
 'peripher',
 'blood',
 'whole',
 'sampl',
 'express',
 'mirna',
 'text',
 'methyl',
 'dna',
 '',
 'genom',
 'imag',
 'perform',
 'motor',
 'and',
 'upperlimb',
 'propriocept',
 'mri',
 'brain',
 'data',
 'imag',
 'shift',
 'iu',
 'measur',
 'record',
 'health',
 'electron',
 'test',
 'laboratori',
 'mri',
 'ultrasound',
 'imag',
 'patholog',
 'digit',
 'comput',
 'tomographi',
 'clinic',
 'imag',
 'text',
 '',
 'patholog',
 '',
 'imag',
 'data',
 'mri',
 'imag',
 't1weight',
 'mri',
 'data',
 'cytometri',
 'singlecel',
 'home',
 'care',
 'assist',
 'client',
 'gait',
 'unsteadi',
 'devic',
 'imag',
 '',
 'genom',
 'data',
 'clinic',
 'mutat',
 'true',
 'null',
 'clinic',
 'imag',
 'text',
 'transcript',
 'rnaseq',
 'histolog',
 'tag',
 'audio',
 'numer',
 'modal',
 'imag',
 'text',
 'null',
 'machinebas',
 'video',
 'imag',
 'languag',
 'natur',
 'narr',
 'rule',
 'review',
 'process',
 'clinic',
 'note',
 'knowledgebas',
 'chart',
 'brain',
 'fmri',
 'modal',
 'imag',
 'magnet',
 'brain',
 'thick',
 'reson',
 'volum',
 'imag',
 'cortic',
 't1weight',
 't2weight',
 'text',
 'bibliometr',
 'heart',
 'and',
 'state',
 'mental',
 'respiratori',
 'time',
 'sign',
 'alter',
 'rate',
 'refil',
 'vital',
 'age',
 'temperatur',
 'capillari',
 'tomographi',
 'comput',
 'scan',
 'ct',
 'serial',
 'time',
 'ptinr',
 'prothrombin',
 'valu',
 'intern',
 'ratio',
 'measur',
 'normal',
 'gene',
 'express',
 'rnaseq',
 'mrna',
 'medic',
 'comput',
 'tomographi',
 'eeg',
 'data',
 'clinic',
 'imag',
 'pet',
 'volumetr',
 'mri',
 'biomark',
 'neuropsycholog',
 'fluid',
 'cerebrospin',
 'imag',
 'test',
 'text',
 'data',
 'imag',
 'spect',
 'clinic',
 'imag',
 'mr',
 'mri',
 'imag',
 'gene',
 'express',
 'drug',
 'respons',
 'biolog',
 'genom',
 'thermal',
 'thermogram',
 'imag',
 'mri',
 'behavior',
 'brain',
 'questionnair',
 'function',
 'measur',
 'tomographi',
 'comput',
 'scan',
 'ct',
 'genet',
 'genom',
 'patholog',
 'genom',
 '',
 'da',
 'view',
 'reconstruct',
 'biplanar',
 'radiograph',
 '3d',
 'vinci',
 'biolog',
 'clinic',
 'motion',
 'hand',
 'spectrotempor',
 'characterist',
 'photograph',
 'video',
 'dialogu',
 'text',
 'median',
 'nerv',
 'pneumat',
 'electr',
 'stimul',
 'text',
 'clinic',
 'dualenergi',
 'comput',
 'absorptiometri',
 'chest',
 'tomographi',
 'xray',
 'text',
 'imag',
 'variabl',
 '68',
 'medic',
 'modal',
 'null',
 'variables_us',
 'demograph',
 'count',
 'rnaseq',
 '1',
 'modal',
 'microrna',
 'patholog',
 'molecular',
 'text',
 'imag',
 'administr',
 'clinic',
 'pet',
 'comput',
 'ct',
 'emiss',
 'positron',
 'tomographi',
 'slide',
 'histolog',
 'immunogenet',
 'imag',
 'whole',
 'text',
 'diagnosi',
 'variabl',
 'node',
 'clinic',
 'lymph',
 'age',
 'at',
 'volumetr',
 'planar',
 'medic',
 'threedimension',
 'twodimension',
 'imag',
 '3d',
 '2d',
 'genet',
 'contact',
 'text',
 'investig',
 'cancer',
 'prostat',
 'abdomin',
 'imag',
 'reaction',
 'motion',
 'ground',
 'modal',
 'forc',
 'pet',
 'fdgpet',
 'analyt',
 'healthcar',
 'artifici',
 'intellig',
 'mrna',
 'blood',
 'microarray',
 'muscl',
 'health',
 'data',
 '',
 '',
 'nmr',
 'and',
 'brain',
 'extract',
 'dilcmsm',
 'metabolom',
 'fdg',
 'pet',
 'amyloid',
 'adc',
 'mri',
 'magnet',
 'teu',
 'imag',
 'enhanc',
 'tempor',
 'reson',
 'coeffici',
 'appar',
 'diffus',
 'ultrasound',
 'text',
 'biomark',
 'digit',
 'petct',
 'multiscal',
 'medic',
 'imag',
 '3d',
 'input',
 'administr',
 'databas',
 'true',
 'comput',
 'dosevolum',
 'ct',
 'imag',
 'histogram',
 'dvh',
 'tomographi',
 'text',
 'note',
 'bill',
 'lab',
 'imag',
 'clinic',
 'test',
 'text',
 'code',
 'patholog',
 'franc',
 'null',
 'text',
 'imag',
 'mirna',
 'threedimension',
 'saliva',
 'numer',
 'review',
 'rate',
 'text',
 'written',
 'ecg',
 'medicin',
 'nuclear',
 'cardiovascular',
 'imag',
 'name',
 'nutrit',
 'electrocardiograph',
 'pni',
 'modal',
 'laboratori',
 'nlr',
 'prognost',
 'indic',
 'echocardiograph',
 'data',
 'assess',
 'neutrophiltolymphocyt',
 'ratio',
 'pwave',
 'index',
 '',
 'comput',
 'tomographi',
 'ct',
 'text',
 't1postcontrast',
 'invers',
 'attenu',
 'flair',
 't1precontrast',
 'fluid',
 'recoveri',
 'social',
 'behavior',
 'econom',
 'factor',
 'psycholog',
 '3d',
 'loci',
 'genom',
 ...]

In [46]:
output_file_path = 'data-modalities-updated.csv'
data.to_csv(output_file_path, index=False)

In [55]:
import pandas as pd
from collections import Counter

# Load the updated data
# file_path = 'data-modalities-updated.csv'
# data = pd.read_csv(file_path)

# Flatten the list of modalities
# all_modalities = [modality for sublist in data['unique_names'].dropna() for modality in eval(sublist)]
all_modalities = [modality for sublist in data['unique_names'].dropna() for modality in sublist]
# Count frequencies
modality_counts = Counter(all_modalities)

# Find the top 10 most common modalities
top_10_modalities = modality_counts.most_common(50)

# Convert to DataFrame for better readability
top_10_df = pd.DataFrame(top_10_modalities, columns=['Modality', 'Count'])

# Display the top 10 modalities
print(top_10_df)

# Optionally, save the results to a CSV file
top_10_file_path = 'top_10_modalities.csv'
top_10_df.to_csv(top_10_file_path, index=False)

print(f"Top 10 modalities saved to {top_10_file_path}")

                      Modality  Count
0                         imag    309
1                         text    266
2                          mri    205
3                       clinic     98
4                           ct     72
5                   ultrasound     67
6            comput tomographi     66
7                          eeg     61
8            magnet reson imag     60
9                                  55
10                  medic imag     51
11                        fmri     46
12                       video     46
13                       genom     41
14                     ct scan     40
15                         ecg     36
16                       audio     35
17                 clinic data     31
18                machin learn     28
19                         pet     26
20      electron health record     26
21        comput tomographi ct     26
22                       medic     25
23                gene express     25
24                   demograph     25
25                        xray     22
26                        null     22
27                  modal imag     21
28                  modal text     20
29                       robot     19
30  function magnet reson imag     19
31                    patholog     18
32                function mri     18
33                   metabolom     18
34                         age     18
35                   imag data     17
36                    radiolog     17
37                     proteom     16
38                   neuroimag     16
39                       numer     15
40                      cognit     15
41                       genet     15
42       magnet reson imag mri     15
43       electron medic record     15
44                     ct imag     14
45                  brain imag     14
46               histopatholog     14
47            echocardiographi     13
48                      speech     13
49                transcriptom     13
Top 10 modalities saved to top_10_modalities.csv

In [50]:
top_10_file_path

'top_10_modalities.csv'

In [22]:
import pandas as pd

# Data USA and Canada (modalities)
modalities_data = {
    'Modality': ['MRI', 'CT Scans', 'Genomics', 'fMRI', 'Ultrasound', 'EEG'],
    'Papers': [87, 56, 33, 21, 19, 19],
}

# Total number of papers
total_papers = 909

# Calculate percentage
modalities_data['Percentage'] = [(x / total_papers) * 100 for x in modalities_data['Papers']]

# Create DataFrame
df = pd.DataFrame(modalities_data)

df

     Modality  Papers  Percentage
0         MRI      87    9.570957
1    CT Scans      56    6.160616
2    Genomics      33    3.630363
3        fMRI      21    2.310231
4  Ultrasound      19    2.090209
5         EEG      19    2.090209

In [23]:
import pandas as pd
file_path = './data-uk.csv'  # Replace with your actual file path
data = pd.read_csv(file_path)
data

,pid,countries,x,modalities,modalities2
0,28756487,"[""Canada"", ""France"", ""United Kingdom""]","[""anatomical"", ""functional""], [""voice-sensitiv...","[""anatomical"", ""functional""]","[""voice-sensitive cortex"", ""functional voice a..."
1,29043544,"[""Canada"", ""Poland"", ""United Kingdom""]","[""Transcranial Doppler (TCD)"", ""Intracranial p...","[""Transcranial Doppler (TCD)"", ""Intracranial p...","[""Transcranial Doppler"", ""Intracranial pressur..."
2,29274736,"[""Canada"", ""Mexico"", ""United Kingdom""]","[""Tissue Density Estimates"", ""Cortical Thickne...","[""Tissue Density Estimates"", ""Cortical Thickne...","[""magnetic resonance images""]"
3,29335008,"[""Australia"", ""Canada"", ""United Kingdom""]","[""16S"", ""Shotgun metagenomics""], [""16S rRNA ge...","[""16S"", ""Shotgun metagenomics""]","[""16S rRNA gene"", ""shotgun metagenomics""]"
4,29340580,"[""Canada"", ""Denmark"", ""Russia"", ""South Korea"",...","[""Blood Samples""], [""Hematological""]","[""Blood Samples""]","[""Hematological""]"
...,...,...,...,...,...
256,37829182,"[""Australia"", ""Canada"", ""China"", ""Colombia"", ""...",NaN,"[""Medical Imaging"", ""Electronic Health Records""]",NaN
257,34694234,"[""Canada"", ""United Kingdom"", ""United States""]",NaN,"[""Clinical""]",NaN
258,31919503,"[""Canada"", ""Turkey"", ""United Kingdom"", ""United...",NaN,NaN,NaN
259,31926806,"[""Australia"", ""Brazil"", ""Canada"", ""Germany"", ""...",NaN,"[null, null, null, null, null]",NaN
260,38542033,"[""Canada"", ""Netherlands"", ""Spain"", ""United Kin...",NaN,"[""medical""]",NaN

In [27]:
# New data for Canada and UK
modalities_data_uk = {
    'Modality': ['MRI', 'Genomics', 'EEG', 'CT Scans', 'fMRI'],
    'Papers': [24, 16, 11, 9, 5],
}

# Total number of papers for Canada and UK
total_papers_uk = 267

# Calculate percentage
modalities_data_uk['Percentage'] = [(x / total_papers_uk) * 100 for x in modalities_data_uk['Papers']]

# Create DataFrame
df_uk = pd.DataFrame(modalities_data_uk)

df_uk

   Modality  Papers  Percentage
0       MRI      24    8.988764
1  Genomics      16    5.992509
2       EEG      11    4.119850
3  CT Scans       9    3.370787
4      fMRI       5    1.872659

In [36]:
import pandas as pd
file_path = './data-china.csv'  # Replace with your actual file path
data = pd.read_csv(file_path)
data

,pid,countries,x,modalities,modalities2
0,28651909,"[""Canada"", ""China""]","[""Computerized Cambridge Neurocognitive Test A...","[""Computerized Cambridge Neurocognitive Test A...","[""cognitive tests""]"
1,28869436,"[""Canada"", ""China""]","[""Lower Limbs Rehabilitation Robot""], [""Robot""...","[""Lower Limbs Rehabilitation Robot""]","[""Robot"", ""Device""]"
2,29098645,"[""Canada"", ""China"", ""Netherlands""]","[""Cognitive features""], [""Cognitive features""]","[""Cognitive features""]","[""Cognitive features""]"
3,29268169,"[""Canada"", ""China"", ""France"", ""Poland"", ""Unite...","[""MICCAI""], [""X-ray"", ""Computed Tomography""]","[""MICCAI""]","[""X-ray"", ""Computed Tomography""]"
4,29356346,"[""Canada"", ""China""]","[""Audiogram"", ""Initial Hearing Level"", ""Time E...","[""Audiogram"", ""Initial Hearing Level"", ""Time E...","[""Audiogram"", ""Hearing level""]"
...,...,...,...,...,...
232,38842257,"[""Canada"", ""China"", ""Germany"", ""Israel"", ""Neth...","[""Serum metabolites"", ""Magnetic resonance ente...","[""Serum metabolites"", ""Magnetic resonance ente...","[""Serum metabolites""]"
233,38850215,"[""Canada"", ""China"", ""Japan""]","[""MRI""], [""Structural connectivity data""]","[""MRI""]","[""Structural connectivity data""]"
234,38951965,"[""Canada"", ""China""]","[""Medical""], [""Image"", ""Text""]","[""Medical""]","[""Image"", ""Text""]"
235,39013848,"[""Australia"", ""Canada"", ""China"", ""Germany"", ""I...",NaN,"[""Magnetic Resonance"", ""Brain Imaging""]",NaN
236,37829182,"[""Australia"", ""Canada"", ""China"", ""Colombia"", ""...",NaN,"[""Medical Imaging"", ""Electronic Health Records""]",NaN

In [34]:
# Data provided
data = {
    'Technology': ['MRI', 'CT scans', 'fMRI', 'Genomics', 'EEG'],
    'Count': [29, 10, 7, 6, 5]
}

# Creating a DataFrame
import pandas as pd

df = pd.DataFrame(data)

# Calculate the total count
total_count = 237  # Given total

# Calculate percentages
df['Percentage'] = (df['Count'] / total_count) * 100

# Display the DataFrame with percentages
print(df)

  Technology  Count  Percentage
0        MRI     29   12.236287
1   CT scans     10    4.219409
2       fMRI      7    2.953586
3   Genomics      6    2.531646
4        EEG      5    2.109705

In [44]:
import pandas as pd
file_path = './data-ger.csv'  # Replace with your actual file path
data = pd.read_csv(file_path)
data

,pid,countries,x,modalities,modalities2
0,28968847,"[""Canada"", ""Germany"", ""United States""]","[""MRI""], [""MRI""]","[""MRI""]","[""MRI""]"
1,28981875,"[""Canada"", ""Germany"", ""Turkey"", ""United States""]","[""Nil""], [""Text"", ""Audio""]","[""Nil""]","[""Text"", ""Audio""]"
2,29272464,"[""Canada"", ""Czechia"", ""Germany"", ""Turkey"", ""Un...","[""Structural magnetic resonance imaging scans ...","[""Structural magnetic resonance imaging scans ...","[""MRI scans""]"
3,29454222,"[""Canada"", ""Czechia"", ""Germany"", ""Turkey""]","[""Magnetic Resonance Imaging"", ""Lipids and bod...","[""Magnetic Resonance Imaging"", ""Lipids and bod...","[""structural MRI"", ""fasting lipids"", ""body mas..."
4,29539639,"[""Australia"", ""Austria"", ""Canada"", ""Denmark"", ...","[""DNA methylation""], [""text"", ""image"", ""audio""]","[""DNA methylation""]","[""text"", ""image"", ""audio""]"
...,...,...,...,...,...
204,38842593,"[""Canada"", ""Germany""]","[""Metabolomics""], [""Metabolomic"", ""Xenobiotic""]","[""Metabolomics""]","[""Metabolomic"", ""Xenobiotic""]"
205,38848770,"[""Canada"", ""Germany""]","[""Computed Tomography""], [""Image data""]","[""Computed Tomography""]","[""Image data""]"
206,38926357,"[""Canada"", ""Germany""]","[""Histopathology images"", ""Whole genome sequen...","[""Histopathology images"", ""Whole genome sequen...","[""Histopathology images""]"
207,39013848,"[""Australia"", ""Canada"", ""China"", ""Germany"", ""I...",NaN,"[""Magnetic Resonance"", ""Brain Imaging""]",NaN
208,31926806,"[""Australia"", ""Brazil"", ""Canada"", ""Germany"", ""...",NaN,"[null, null, null, null, null]",NaN

In [52]:
# Data provided
data = {
    'Technology': ['MRI', 'CT scans', 'fMRI', 'PET', 'EEG'],
    'Count': [35, 16, 23, 6, 9]
}
# Creating a DataFrame
import pandas as pd

df = pd.DataFrame(data)

# Calculate the total count
total_count = 209  # Given total

# Calculate percentages
df['Percentage'] = (df['Count'] / total_count) * 100

# Display the DataFrame with percentages
print(df)

  Technology  Count  Percentage
0        MRI     35   16.746411
1   CT scans     16    7.655502
2       fMRI     23   11.004785
3        PET      6    2.870813
4        EEG      9    4.306220

In [53]:
import pandas as pd
file_path = './data-ca.csv'  # Replace with your actual file path
data = pd.read_csv(file_path)
data

,pid,countries,x,modalities,modalities2
0,28601499,"[""Australia"", ""Canada""]","[""fMRI""], [""fMRI""]","[""fMRI""]","[""fMRI""]"
1,28651909,"[""Canada"", ""China""]","[""Computerized Cambridge Neurocognitive Test A...","[""Computerized Cambridge Neurocognitive Test A...","[""cognitive tests""]"
2,28756487,"[""Canada"", ""France"", ""United Kingdom""]","[""anatomical"", ""functional""], [""voice-sensitiv...","[""anatomical"", ""functional""]","[""voice-sensitive cortex"", ""functional voice a..."
3,28771699,"[""Brazil"", ""Canada"", ""Israel""]","[""Checkerboard DNA-DNA hybridisation""], [""DNA-...","[""Checkerboard DNA-DNA hybridisation""]","[""DNA-DNA hybridisation""]"
4,28853237,"[""Canada"", ""Russia""]","[""Optical Coherence Tomography""], [""optical co...","[""Optical Coherence Tomography""]","[""optical coherence tomography""]"
...,...,...,...,...,...
2678,37829182,"[""Australia"", ""Canada"", ""China"", ""Colombia"", ""...",NaN,"[""Medical Imaging"", ""Electronic Health Records""]",NaN
2679,36280681,"[""Canada"", ""Saudi Arabia"", ""United States""]",NaN,"[""Ultrasound"", ""Clinical""]",NaN
2680,31919503,"[""Canada"", ""Turkey"", ""United Kingdom"", ""United...",NaN,NaN,NaN
2681,38290583,"[""Brazil"", ""Canada"", ""Norway""]",NaN,NaN,NaN
2682,37546399,"[""Canada"", ""France""]",NaN,NaN,NaN

In [56]:
# Data provided
data = {
    'Technology': ['MRI', 'CT scans', 'Ultrasound', 'EEG', 'Genomics'],
    'Count': [363, 177, 88, 77, 69]
}

# Creating a DataFrame
import pandas as pd

df = pd.DataFrame(data)

# Calculate the total count
total_count = 2683  # Given total

# Calculate percentages
df['Percentage'] = (df['Count'] / total_count) * 100

# Display the DataFrame with percentages
print(df)

   Technology  Count  Percentage
0         MRI    363   13.529631
1    CT scans    177    6.597093
2  Ultrasound     88    3.279911
3         EEG     77    2.869922
4    Genomics     69    2.571748

In [57]:
! pip install matplotlib seaborn pandas

Requirement already satisfied: matplotlib in /opt/homebrew/anaconda3/lib/python3.12/site-packages (3.8.4)
Requirement already satisfied: seaborn in /opt/homebrew/anaconda3/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.21 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)