In [1]:
! pip install lxml
! pip install pandas
! pip install bs4

Requirement already satisfied: lxml in /opt/homebrew/anaconda3/lib/python3.12/site-packages (5.2.1)
^C
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/bin/pip", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 79, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 236, in _main
    self.handle_pip_version_check(options)
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 177, in handle_pip_version_check
    session = self._build_session(
              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 122, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/network/session.py", line 342, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 184, in <genexpr>
    matches = (
              ^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 626, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    yield from finder.find(location)
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find
    for dist, info_location in self._find_impl(location):
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl
    raw_name = get_dist_name(dist)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name
    name = cast(Any, dist).name
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/importlib/metadata/__init__.py", line 457, in name
    return self.metadata['Name']
           ^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/importlib/metadata/__init__.py", line 452, in metadata
    return _adapters.Message(email.message_from_string(text))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/importlib/metadata/_adapters.py", line 41, in __new__
    def __new__(cls, orig: email.message.Message):

KeyboardInterrupt
Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: bs4 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from beautifulsoup4->bs4) (2.5)

In [ ]:
import os

# Path to the original XML file
file_path = './data/a.xml'
temp_file_path = './data/a_modified.xml'

# DTD content to insert after the XML declaration
dtd_content = '''<!DOCTYPE PubmedArticleSet [
<!ENTITY quote "&#34;">
<!ENTITY apos "&#39;">
<!ENTITY amp "&#38;">
<!ENTITY lt "&#60;">
<!ENTITY gt "&#62;">
]>'''

# Open the original file for reading
with open(file_path, 'r', encoding='utf-8') as original_file:
    # Read the first line
    first_line = original_file.readline().strip()

    # Check if the first line contains the XML declaration
    if first_line.startswith('<?xml'):
        # Create a temporary file for writing
        with open(temp_file_path, 'w', encoding='utf-8') as temp_file:
            # Write the XML declaration and DTD to the temporary file
            temp_file.write(f"{first_line}\n{dtd_content}\n")

            # Copy the rest of the original file to the temporary file
            chunk_size = 1024 * 1024  # 1MB chunks
            while True:
                chunk = original_file.read(chunk_size)
                if not chunk:
                    break
                temp_file.write(chunk)

        # Replace the original file with the modified temporary file
        os.replace(temp_file_path, file_path)
    else:
        # If the first line is not an XML declaration, handle it accordingly
        print("The file does not start with an XML declaration. Unable to add DTD.")

print("Successfully replaced the first line with XML declaration and DTD in the same file.")

Successfully replaced the first line with XML declaration and DTD in the same file.

In [ ]:
from lxml import etree
import pandas as pd
import html

# Function to decode HTML entities in text


def decode_html_entities(text):
    return html.unescape(text) if text else ''

# Function to parse each PubmedArticle element


def parse_pubmed_article(element):
    data = {}

    # Extract data from MedlineCitation
    medline_citation = element.find('MedlineCitation')
    if medline_citation is not None:
        data['PMID'] = medline_citation.findtext('PMID')

        data['MedlineCitationOwner'] = medline_citation.get('Owner', '')
        data['MedlineCitationStatus'] = medline_citation.get('Status', '')
        data['MedlineCitationVersionID'] = medline_citation.get(
            'VersionID', '')
        data['MedlineCitationVersionDate'] = medline_citation.get(
            'VersionDate', '')
        data['MedlineCitationIndexingMethod'] = medline_citation.get(
            'IndexingMethod', '')

        date_completed = medline_citation.find('DateCompleted')
        if date_completed is not None:
            data['DateCompleted'] = {
                'Year': date_completed.findtext('Year'),
                'Month': date_completed.findtext('Month'),
                'Day': date_completed.findtext('Day')
            }

        date_revised = medline_citation.find('DateRevised')
        if date_revised is not None:
            data['DateRevised'] = {
                'Year': date_revised.findtext('Year'),
                'Month': date_revised.findtext('Month'),
                'Day': date_revised.findtext('Day')
            }

        article = medline_citation.find('Article')
        if article is not None:
            data['ArticlePubModel'] = article.get('PubModel', '')

            journal = article.find('Journal')
            if journal is not None:
                data['JournalISSN'] = journal.findtext('ISSN')
                data['JournalTitle'] = journal.findtext('Title')
                data['JournalISOAbbreviation'] = journal.findtext(
                    'ISOAbbreviation')

            data['ArticleTitle'] = decode_html_entities(
                article.findtext('ArticleTitle'))
            data['Language'] = article.findtext('Language')

            pagination = article.find('Pagination')
            if pagination is not None:
                data['StartPage'] = pagination.findtext('StartPage')
                data['EndPage'] = pagination.findtext('EndPage')
                data['MedlinePgn'] = pagination.findtext('MedlinePgn')

            abstract = article.find('Abstract')
            if abstract is not None:
                abstract_texts = abstract.findall('AbstractText')
                data['Abstract'] = [{'Label': text.get('Label', ''),
                                     'NlmCategory': text.get('NlmCategory', ''),
                                     'Text': decode_html_entities(text.text)}
                                    for text in abstract_texts]

            authors = []
            for author_elem in article.findall('AuthorList/Author'):
                author = {
                    'LastName': author_elem.findtext('LastName'),
                    'ForeName': author_elem.findtext('ForeName'),
                    'Initials': author_elem.findtext('Initials'),
                    'Affiliation': []
                }
                # Extract affiliations for each author
                affiliations = author_elem.findall(
                    'AffiliationInfo/Affiliation')
                for affiliation_elem in affiliations:
                    author['Affiliation'].append(
                        decode_html_entities(affiliation_elem.text))
                authors.append(author)
            data['Authors'] = authors

            data['DataBankList'] = []
            databanks = article.findall('DataBankList/DataBank')
            for databank in databanks:
                data_bank = {
                    'DataBankName': databank.findtext('DataBankName'),
                    'AccessionNumberList': [accession.text for accession in databank.findall('AccessionNumberList/AccessionNumber')]
                }
                data['DataBankList'].append(data_bank)

            data['GrantList'] = []
            grants = article.findall('GrantList/Grant')
            for grant in grants:
                grant_data = {
                    'GrantID': grant.findtext('GrantID'),
                    'Acronym': grant.findtext('Acronym'),
                    'Agency': grant.findtext('Agency'),
                    'Country': grant.findtext('Country')
                }
                data['GrantList'].append(grant_data)

            publication_types = article.findall(
                'PublicationTypeList/PublicationType')
            data['PublicationTypeList'] = [
                ptype.text for ptype in publication_types]

            vernacular_title = article.find('VernacularTitle')
            if vernacular_title is not None:
                data['VernacularTitle'] = decode_html_entities(
                    vernacular_title.text)

            article_dates = article.findall('ArticleDate')
            data['ArticleDates'] = [{
                'Year': date.findtext('Year'),
                'Month': date.findtext('Month'),
                'Day': date.findtext('Day'),
                'DateType': date.get('DateType', '')
            } for date in article_dates]

        # Extract data from PubmedData
        pubmed_data = element.find('PubmedData')
        if pubmed_data is not None:
            data['PublicationStatus'] = pubmed_data.findtext(
                'PublicationStatus')

            article_ids = pubmed_data.findall('ArticleIdList/ArticleId')
            data['ArticleIds'] = [{
                'IdType': article_id.get('IdType', ''),
                'Value': article_id.text
            } for article_id in article_ids]

            history = pubmed_data.findall('History/PubMedPubDate')
            data['History'] = [{
                'PubStatus': date.get('PubStatus', ''),
                'Year': date.findtext('Year'),
                'Month': date.findtext('Month'),
                'Day': date.findtext('Day'),
                'Hour': date.findtext('Hour'),
                'Minute': date.findtext('Minute'),
                'Second': date.findtext('Second')
            } for date in history]

            objects = pubmed_data.findall('ObjectList/Object')
            data['Objects'] = [{
                'ObjectType': obj.get('Type', ''),
                'Params': {param.get('Name'): param.text for param in obj.findall('Param')}
            } for obj in objects]

    return data


# Initialize a list to hold parsed data
parsed_data = []

# Parse the XML file using iterparse for large files
parser = etree.iterparse('./data/pubmed_ml_ai_results.xml', events=('end',),
                         tag='PubmedArticle', encoding='utf-8', recover=True)

for event, elem in parser:
    article_data = parse_pubmed_article(elem)
    parsed_data.append(article_data)
    elem.clear()  # Clear the element to save memory

# Create a DataFrame from parsed data
df = pd.DataFrame(parsed_data)

# Print the DataFrame
print(df)

            PMID MedlineCitationOwner MedlineCitationStatus  \
0       17379690                  NLM    PubMed-not-MEDLINE
1       20585802                  NLM               MEDLINE
2       26254699                  NLM               MEDLINE
3       26394433                  NLM               MEDLINE
4       26409750                  NLM               MEDLINE
...          ...                  ...                   ...
203226  39017971                  NLM             Publisher
203227  39018014                  NLM             Publisher
203228  39018022                  NLM             Publisher
203229  39018040                  NLM             Publisher
203230  39018100                  NLM             Publisher

       MedlineCitationVersionID MedlineCitationVersionDate  \
0
1
2
3
4
...                         ...                        ...
203226
203227
203228
203229
203230

       MedlineCitationIndexingMethod  \
0
1                          Automated
2
3
4
...                              ...
203226                     Automated
203227                     Automated
203228                     Automated
203229                     Automated
203230                     Automated

                                         DateRevised   ArticlePubModel  \
0       {'Year': '2020', 'Month': '05', 'Day': '19'}             Print
1       {'Year': '2021', 'Month': '10', 'Day': '20'}  Print-Electronic
2       {'Year': '2019', 'Month': '11', 'Day': '01'}  Print-Electronic
3       {'Year': '2019', 'Month': '05', 'Day': '20'}  Print-Electronic
4       {'Year': '2019', 'Month': '11', 'Day': '01'}  Print-Electronic
...                                              ...               ...
203226  {'Year': '2024', 'Month': '07', 'Day': '17'}  Print-Electronic
203227  {'Year': '2024', 'Month': '07', 'Day': '17'}  Print-Electronic
203228  {'Year': '2024', 'Month': '07', 'Day': '17'}  Print-Electronic
203229  {'Year': '2024', 'Month': '07', 'Day': '17'}  Print-Electronic
203230  {'Year': '2024', 'Month': '07', 'Day': '17'}        Electronic

       JournalISSN                                       JournalTitle  ...  \
0        1367-4811                   Bioinformatics (Oxford, England)  ...
1        1435-2451                   Langenbeck's archives of surgery  ...
2        1873-2860                Artificial intelligence in medicine  ...
3        1557-9964  IEEE/ACM transactions on computational biology...  ...
4        1873-2860                Artificial intelligence in medicine  ...
...            ...                                                ...  ...
203226   1534-4681                        Annals of surgical oncology  ...
203227   1460-2156                     Brain : a journal of neurology  ...
203228   1464-3677  International journal for quality in health ca...  ...
203229   2380-6591                                    JAMA cardiology  ...
203230   2291-5222                           JMIR mHealth and uHealth  ...

       DataBankList GrantList  \
0                []        []
1                []        []
2                []        []
3                []        []
4                []        []
...             ...       ...
203226           []        []
203227           []        []
203228           []        []
203229           []        []
203230           []        []

                                      PublicationTypeList  \
0            [Journal Article, Retraction of Publication]
1                                       [Letter, Comment]
2                   [Historical Article, Journal Article]
3       [Journal Article, Research Support, Non-U.S. G...
4                                       [Journal Article]
...                                                   ...
203226                                           [Letter]
203227                                  [Journal Article]
203228                                  [Journal Article]
203229                                  [Journal Article]
203230                                  [Journal Article]

                                             ArticleDates PublicationStatus  \
0                                                      []          ppublish
1       [{'Year': '2010', 'Month': '06', 'Day': '29', ...          ppublish
2       [{'Year': '2015', 'Month': '07', 'Day': '02', ...          ppublish
3       [{'Year': '2015', 'Month': '09', 'Day': '18', ...          ppublish
4       [{'Year': '2015', 'Month': '09', 'Day': '12', ...          ppublish
...                                                   ...               ...
203226  [{'Year': '2024', 'Month': '07', 'Day': '17', ...      aheadofprint
203227  [{'Year': '2024', 'Month': '07', 'Day': '17', ...      aheadofprint
203228  [{'Year': '2024', 'Month': '07', 'Day': '17', ...      aheadofprint
203229  [{'Year': '2024', 'Month': '07', 'Day': '17', ...      aheadofprint
203230  [{'Year': '2024', 'Month': '07', 'Day': '17', ...          epublish

                                               ArticleIds  \
0       [{'IdType': 'pubmed', 'Value': '17379690'}, {'...
1       [{'IdType': 'pubmed', 'Value': '20585802'}, {'...
2       [{'IdType': 'pubmed', 'Value': '26254699'}, {'...
3       [{'IdType': 'pubmed', 'Value': '26394433'}, {'...
4       [{'IdType': 'pubmed', 'Value': '26409750'}, {'...
...                                                   ...
203226  [{'IdType': 'pubmed', 'Value': '39017971'}, {'...
203227  [{'IdType': 'pubmed', 'Value': '39018014'}, {'...
203228  [{'IdType': 'pubmed', 'Value': '39018022'}, {'...
203229  [{'IdType': 'pubmed', 'Value': '39018040'}, {'...
203230  [{'IdType': 'pubmed', 'Value': '39018100'}, {'...

                                                  History Objects  \
0       [{'PubStatus': 'received', 'Year': '2007', 'Mo...      []
1       [{'PubStatus': 'received', 'Year': '2010', 'Mo...      []
2       [{'PubStatus': 'received', 'Year': '2014', 'Mo...      []
3       [{'PubStatus': 'pubmed', 'Year': '2015', 'Mont...      []
4       [{'PubStatus': 'received', 'Year': '2015', 'Mo...      []
...                                                   ...     ...
203226  [{'PubStatus': 'medline', 'Year': '2024', 'Mon...      []
203227  [{'PubStatus': 'medline', 'Year': '2024', 'Mon...      []
203228  [{'PubStatus': 'medline', 'Year': '2024', 'Mon...      []
203229  [{'PubStatus': 'medline', 'Year': '2024', 'Mon...      []
203230  [{'PubStatus': 'medline', 'Year': '2024', 'Mon...      []

                                       DateCompleted VernacularTitle
0                                                NaN             NaN
1       {'Year': '2019', 'Month': '10', 'Day': '21'}             NaN
2       {'Year': '2019', 'Month': '11', 'Day': '01'}             NaN
3       {'Year': '2019', 'Month': '05', 'Day': '20'}             NaN
4       {'Year': '2019', 'Month': '11', 'Day': '01'}             NaN
...                                              ...             ...
203226                                           NaN             NaN
203227                                           NaN             NaN
203228                                           NaN             NaN
203229                                           NaN             NaN
203230                                           NaN             NaN

[203231 rows x 28 columns]

In [ ]:
parsed_data[2]

{'PMID': '26254699',
 'MedlineCitationOwner': 'NLM',
 'MedlineCitationStatus': 'MEDLINE',
 'MedlineCitationVersionID': '',
 'MedlineCitationVersionDate': '',
 'MedlineCitationIndexingMethod': '',
 'DateCompleted': {'Year': '2019', 'Month': '11', 'Day': '01'},
 'DateRevised': {'Year': '2019', 'Month': '11', 'Day': '01'},
 'ArticlePubModel': 'Print-Electronic',
 'JournalISSN': '1873-2860',
 'JournalTitle': 'Artificial intelligence in medicine',
 'JournalISOAbbreviation': 'Artif Intell Med',
 'ArticleTitle': 'Origins of the Arden Syntax.',
 'Language': 'eng',
 'StartPage': '7',
 'EndPage': '9',
 'MedlinePgn': '7-9',
 'Abstract': [{'Label': '',
   'NlmCategory': '',
   'Text': "The Arden Syntax originated in the 1980's, when several knowledge-based systems began to show promise, but researchers recognized the burden of recreating these systems at every institution. Derived initially from Health Evaluation through Logical Processing (HELP) and the Regenstrief Medical Record System (RMRS), the Arden Syntax defines medical logic that can be encoded as independent rules, such as reminders and alerts, with the hope of creating a public library of rules. It was first vetted at an informatics retreat held in 1989 at Columbia University's Arden Homestead. The syntax was intended to be readable by clinician experts but to provide powerful array processing, which was derived largely a programming language called APL. The syntax was improved and implemented by a number of researchers and vendors in the early 1990's and was initially adopted by the consensus standards organization, the American Society for Testing and Materials."}],
 'Authors': [{'LastName': 'Hripcsak',
   'ForeName': 'George',
   'Initials': 'G',
   'Affiliation': ['Department of Biomedical Informatics, Columbia University, 622 W 168th Street, PH20, New York, NY 10032, USA; Medical Informatics Services, NewYork-Presbyterian Hospital, 622 W 168th Street, PH20, New York, NY 10032, USA. Electronic address: hripcsak@columbia.edu.']},
  {'LastName': 'Wigertz',
   'ForeName': 'Ove B',
   'Initials': 'OB',
   'Affiliation': ['Department of Medical Informatics, Linköping University, 58183 Linköping, Sweden.']},
  {'LastName': 'Clayton',
   'ForeName': 'Paul D',
   'Initials': 'PD',
   'Affiliation': ['Department of Biomedical Informatics, Columbia University, 622 W 168th Street, PH20, New York, NY 10032, USA; Department of Biomedical Informatics, University of Utah, 421 Wakara Way, Ste 140, Salt Lake City, UT 84108, USA.']}],
 'DataBankList': [],
 'GrantList': [],
 'PublicationTypeList': ['Historical Article', 'Journal Article'],
 'ArticleDates': [{'Year': '2015',
   'Month': '07',
   'Day': '02',
   'DateType': 'Electronic'}],
 'PublicationStatus': 'ppublish',
 'ArticleIds': [{'IdType': 'pubmed', 'Value': '26254699'},
  {'IdType': 'doi', 'Value': '10.1016/j.artmed.2015.05.006'},
  {'IdType': 'pii', 'Value': 'S0933-3657(15)00064-0'}],
 'History': [{'PubStatus': 'received',
   'Year': '2014',
   'Month': '12',
   'Day': '8',
   'Hour': None,
   'Minute': None,
   'Second': None},
  {'PubStatus': 'revised',
   'Year': '2015',
   'Month': '5',
   'Day': '10',
   'Hour': None,
   'Minute': None,
   'Second': None},
  {'PubStatus': 'accepted',
   'Year': '2015',
   'Month': '5',
   'Day': '10',
   'Hour': None,
   'Minute': None,
   'Second': None},
  {'PubStatus': 'pubmed',
   'Year': '2015',
   'Month': '8',
   'Day': '10',
   'Hour': '6',
   'Minute': '0',
   'Second': None},
  {'PubStatus': 'medline',
   'Year': '2019',
   'Month': '11',
   'Day': '2',
   'Hour': '6',
   'Minute': '0',
   'Second': None},
  {'PubStatus': 'entrez',
   'Year': '2015',
   'Month': '8',
   'Day': '10',
   'Hour': '6',
   'Minute': '0',
   'Second': None}],
 'Objects': []}

In [ ]:
# Example PubMed IDs to filter
pubmed_ids_to_filter = ['37045921', '37016152',
                        '37720336', '38083058', '34891618', '32750906']

# Filter the DataFrame based on PubMed IDs
filtered_df = df[df['PMID'].isin(pubmed_ids_to_filter)]

# Print the filtered DataFrame
filtered_df

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateRevised,ArticlePubModel,JournalISSN,JournalTitle,...,DataBankList,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,DateCompleted,VernacularTitle
42216,32750906,NLM,MEDLINE,,,Automated,"{'Year': '2021', 'Month': '09', 'Day': '24'}",Print-Electronic,2168-2208,IEEE journal of biomedical and health informatics,...,[],[],"[Journal Article, Research Support, Non-U.S. G...","[{'Year': '2021', 'Month': '03', 'Day': '05', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '32750906'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2020', 'Mont...",[],"{'Year': '2021', 'Month': '09', 'Day': '24'}",NaN
85429,34891618,NLM,MEDLINE,,,Automated,"{'Year': '2021', 'Month': '12', 'Day': '29'}",Print,2694-0604,Annual International Conference of the IEEE En...,...,[],[],"[Journal Article, Research Support, Non-U.S. G...",[],ppublish,"[{'IdType': 'pubmed', 'Value': '34891618'}, {'...","[{'PubStatus': 'entrez', 'Year': '2021', 'Mont...",[],"{'Year': '2021', 'Month': '12', 'Day': '29'}",NaN
140437,37016152,NLM,PubMed-not-MEDLINE,,,Automated,"{'Year': '2023', 'Month': '04', 'Day': '11'}",Electronic,2398-6352,NPJ digital medicine,...,[],[],[Journal Article],"[{'Year': '2023', 'Month': '04', 'Day': '04', ...",epublish,"[{'IdType': 'pubmed', 'Value': '37016152'}, {'...","[{'PubStatus': 'received', 'Year': '2022', 'Mo...",[],NaN,NaN
160951,37720336,NLM,PubMed-not-MEDLINE,,,Automated,"{'Year': '2023', 'Month': '09', 'Day': '20'}",Electronic-eCollection,2666-3899,"Patterns (New York, N.Y.)",...,[],[],[Journal Article],"[{'Year': '2023', 'Month': '08', 'Day': '03', ...",epublish,"[{'IdType': 'pubmed', 'Value': '37720336'}, {'...","[{'PubStatus': 'received', 'Year': '2022', 'Mo...",[],NaN,NaN
172145,38083058,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '01', 'Day': '26'}",Print,2694-0604,Annual International Conference of the IEEE En...,...,[],[],"[Journal Article, Research Support, Non-U.S. G...",[],ppublish,"[{'IdType': 'pubmed', 'Value': '38083058'}, {'...","[{'PubStatus': 'medline', 'Year': '2023', 'Mon...",[],"{'Year': '2023', 'Month': '12', 'Day': '16'}",NaN

In [ ]:
df

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateRevised,ArticlePubModel,JournalISSN,JournalTitle,...,DataBankList,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,DateCompleted,VernacularTitle
0,17379690,NLM,PubMed-not-MEDLINE,,,,"{'Year': '2020', 'Month': '05', 'Day': '19'}",Print,1367-4811,"Bioinformatics (Oxford, England)",...,[],[],"[Journal Article, Retraction of Publication]",[],ppublish,"[{'IdType': 'pubmed', 'Value': '17379690'}, {'...","[{'PubStatus': 'received', 'Year': '2007', 'Mo...",[],NaN,NaN
1,20585802,NLM,MEDLINE,,,Automated,"{'Year': '2021', 'Month': '10', 'Day': '20'}",Print-Electronic,1435-2451,Langenbeck's archives of surgery,...,[],[],"[Letter, Comment]","[{'Year': '2010', 'Month': '06', 'Day': '29', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '20585802'}, {'...","[{'PubStatus': 'received', 'Year': '2010', 'Mo...",[],"{'Year': '2019', 'Month': '10', 'Day': '21'}",NaN
2,26254699,NLM,MEDLINE,,,,"{'Year': '2019', 'Month': '11', 'Day': '01'}",Print-Electronic,1873-2860,Artificial intelligence in medicine,...,[],[],"[Historical Article, Journal Article]","[{'Year': '2015', 'Month': '07', 'Day': '02', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '26254699'}, {'...","[{'PubStatus': 'received', 'Year': '2014', 'Mo...",[],"{'Year': '2019', 'Month': '11', 'Day': '01'}",NaN
3,26394433,NLM,MEDLINE,,,,"{'Year': '2019', 'Month': '05', 'Day': '20'}",Print-Electronic,1557-9964,IEEE/ACM transactions on computational biology...,...,[],[],"[Journal Article, Research Support, Non-U.S. G...","[{'Year': '2015', 'Month': '09', 'Day': '18', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '26394433'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2015', 'Mont...",[],"{'Year': '2019', 'Month': '05', 'Day': '20'}",NaN
4,26409750,NLM,MEDLINE,,,,"{'Year': '2019', 'Month': '11', 'Day': '01'}",Print-Electronic,1873-2860,Artificial intelligence in medicine,...,[],[],[Journal Article],"[{'Year': '2015', 'Month': '09', 'Day': '12', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '26409750'}, {'...","[{'PubStatus': 'received', 'Year': '2015', 'Mo...",[],"{'Year': '2019', 'Month': '11', 'Day': '01'}",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203226,39017971,NLM,Publisher,,,Automated,"{'Year': '2024', 'Month': '07', 'Day': '17'}",Print-Electronic,1534-4681,Annals of surgical oncology,...,[],[],[Letter],"[{'Year': '2024', 'Month': '07', 'Day': '17', ...",aheadofprint,"[{'IdType': 'pubmed', 'Value': '39017971'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],NaN,NaN
203227,39018014,NLM,Publisher,,,Automated,"{'Year': '2024', 'Month': '07', 'Day': '17'}",Print-Electronic,1460-2156,Brain : a journal of neurology,...,[],[],[Journal Article],"[{'Year': '2024', 'Month': '07', 'Day': '17', ...",aheadofprint,"[{'IdType': 'pubmed', 'Value': '39018014'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],NaN,NaN
203228,39018022,NLM,Publisher,,,Automated,"{'Year': '2024', 'Month': '07', 'Day': '17'}",Print-Electronic,1464-3677,International journal for quality in health ca...,...,[],[],[Journal Article],"[{'Year': '2024', 'Month': '07', 'Day': '17', ...",aheadofprint,"[{'IdType': 'pubmed', 'Value': '39018022'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],NaN,NaN
203229,39018040,NLM,Publisher,,,Automated,"{'Year': '2024', 'Month': '07', 'Day': '17'}",Print-Electronic,2380-6591,JAMA cardiology,...,[],[],[Journal Article],"[{'Year': '2024', 'Month': '07', 'Day': '17', ...",aheadofprint,"[{'IdType': 'pubmed', 'Value': '39018040'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],NaN,NaN
203230,39018100,NLM,Publisher,,,Automated,"{'Year': '2024', 'Month': '07', 'Day': '17'}",Electronic,2291-5222,JMIR mHealth and uHealth,...,[],[],[Journal Article],"[{'Year': '2024', 'Month': '07', 'Day': '17', ...",epublish,"[{'IdType': 'pubmed', 'Value': '39018100'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],NaN,NaN

In [ ]:
# Initialize a list to hold parsed data
parsed_data_2025 = []

# Parse the XML file using iterparse for large files
parser_2025 = etree.iterparse('./data/pubmed_ml_ai_uid_add_2025.text', events=('end',),
                              tag='PubmedArticle', encoding='utf-8', recover=True)

for event, elem in parser_2025:
    article_data = parse_pubmed_article(elem)
    parsed_data_2025.append(article_data)
    elem.clear()  # Clear the element to save memory

# Create a DataFrame from parsed data
df_2025 = pd.DataFrame(parsed_data_2025)

df_2025

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,DataBankList,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle
0,33874846,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '07', 'Day': '19'}","{'Year': '2024', 'Month': '07', 'Day': '19'}",Print-Electronic,1752-6116,...,[],[],[Editorial],"[{'Year': '2021', 'Month': '04', 'Day': '20', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '33874846'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],NaN,NaN
1,34137113,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '05', 'Day': '09'}","{'Year': '2024', 'Month': '08', 'Day': '26'}",Print-Electronic,1522-2586,...,[],"[{'GrantID': 'DPI2017-86696-R', 'Acronym': Non...","[Journal Article, Research Support, Non-U.S. G...","[{'Year': '2021', 'Month': '06', 'Day': '16', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '34137113'}, {'...","[{'PubStatus': 'revised', 'Year': '2021', 'Mon...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': '', 'T...",NaN
2,34779775,NLM,MEDLINE,,,Curated,"{'Year': '2024', 'Month': '10', 'Day': '01'}","{'Year': '2024', 'Month': '11', 'Day': '05'}",Print-Electronic,1018-9068,...,[],[],"[Journal Article, Observational Study]","[{'Year': '2021', 'Month': '04', 'Day': '15', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '34779775'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': 'OBJECTIVE', 'NlmCategory': 'OBJECT...",NaN
3,34792285,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '05', 'Day': '17'}","{'Year': '2024', 'Month': '05', 'Day': '17'}",Print-Electronic,1471-1842,...,[],"[{'GrantID': None, 'Acronym': None, 'Agency': ...",[Journal Article],"[{'Year': '2021', 'Month': '11', 'Day': '18', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '34792285'}, {'...","[{'PubStatus': 'revised', 'Year': '2021', 'Mon...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN
4,34847753,NLM,In-Process,,,,NaN,"{'Year': '2025', 'Month': '03', 'Day': '15'}",Print-Electronic,2041-3033,...,[],[],"[Journal Article, Retracted Publication]","[{'Year': '2021', 'Month': '12', 'Day': '01', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '34847753'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2021', 'Mont...",[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53796,40455017,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,0023-1207,...,[],[],"[English Abstract, Journal Article]",[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455017'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': 'OBJECTIVE', 'NlmCategory': 'OBJECT...",Prognosticheskaya model' i kal'kulyator otsenk...
53797,40455151,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455151'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Vir...",NaN
53798,40455152,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455152'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Und...",NaN
53799,40455154,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455154'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN
53800,40455159,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455159'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN

In [ ]:
filtered_df_2025 = df_2025[~df_2025['PMID'].isin(df['PMID'])]
filtered_df_2025

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,DataBankList,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle
7,35108088,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '10', 'Day': '17'}","{'Year': '2025', 'Month': '04', 'Day': '30'}",Print-Electronic,2167-647X,...,[],[],"[Journal Article, Research Support, Non-U.S. G...","[{'Year': '2022', 'Month': '02', 'Day': '02', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35108088'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Tra...",NaN
8,35143339,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '12', 'Day': '16'}","{'Year': '2025', 'Month': '04', 'Day': '30'}",Print-Electronic,2167-647X,...,[],[],[Journal Article],"[{'Year': '2022', 'Month': '02', 'Day': '10', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35143339'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Dee...",NaN
11,35271383,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '12', 'Day': '16'}","{'Year': '2025', 'Month': '04', 'Day': '30'}",Print-Electronic,2167-647X,...,[],[],"[Journal Article, Research Support, Non-U.S. G...","[{'Year': '2022', 'Month': '03', 'Day': '10', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35271383'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Net...",NaN
15,35385378,NLM,MEDLINE,,,Curated,"{'Year': '2024', 'Month': '10', 'Day': '23'}","{'Year': '2024', 'Month': '11', 'Day': '14'}",Print-Electronic,1949-3614,...,[],[],"[Journal Article, Controlled Clinical Trial]","[{'Year': '2022', 'Month': '05', 'Day': '05', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35385378'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN
16,35486562,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '08', 'Day': '08'}","{'Year': '2025', 'Month': '01', 'Day': '07'}",Print-Electronic,1557-9964,...,[],"[{'GrantID': 'U01 AG024904', 'Acronym': 'AG', ...","[Journal Article, Research Support, U.S. Gov't...","[{'Year': '2024', 'Month': '08', 'Day': '08', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35486562'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Alz...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53796,40455017,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,0023-1207,...,[],[],"[English Abstract, Journal Article]",[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455017'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': 'OBJECTIVE', 'NlmCategory': 'OBJECT...",Prognosticheskaya model' i kal'kulyator otsenk...
53797,40455151,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455151'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Vir...",NaN
53798,40455152,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455152'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Und...",NaN
53799,40455154,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455154'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN
53800,40455159,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455159'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN

In [ ]:
filtered_df_2025.to_csv('data_2025.csv', index=False)

In [ ]:
# Extract authors' affiliations
affiliations = []
for idx, row in df.iterrows():
    for author in row['Authors']:
        for affiliation in author['Affiliation']:
            affiliations.append({
                'PMID': row['PMID'],
                'LastName': author['LastName'],
                'ForeName': author['ForeName'],
                'Initials': author['Initials'],
                'Affiliation': affiliation
            })

# Create a DataFrame for affiliations
affiliations_df = pd.DataFrame(affiliations)

In [ ]:
affiliations_df

,PMID,LastName,ForeName,Initials,Affiliation
0,35108088,Dai,Fei,F,School of Big Data and Intelligent Engineering...
1,35108088,Cao,Pengfei,P,School of Big Data and Intelligent Engineering...
2,35108088,Huang,Penggui,P,School of Big Data and Intelligent Engineering...
3,35108088,Mo,Qi,Q,"School of Software, Yunnan University, Kunming..."
4,35108088,Huang,Bi,B,School of Big Data and Intelligent Engineering...
...,...,...,...,...,...
361934,40455159,Sharma,Amita,A,"Bioclues.org, Pune, India."
361935,40455159,Valadi,Jayaraman K,JK,"Department of Computer Science, FLAME Universi..."
361936,40455159,Valadi,Jayaraman K,JK,"Bioclues.org, Pune, India."
361937,40455159,Suravajhala,Prashanth,P,"Bioclues.org, Pune, India."
361938,40455159,Chatterjee,Sreemoyee,S,"Department of Biotechnology, IIS (Deemed to be..."

In [ ]:
unique_affiliations_df = affiliations_df.drop_duplicates(subset=[
                                                         'Affiliation'])

In [ ]:
unique_affiliations_df

,PMID,LastName,ForeName,Initials,Affiliation
0,35108088,Dai,Fei,F,School of Big Data and Intelligent Engineering...
3,35108088,Mo,Qi,Q,"School of Software, Yunnan University, Kunming..."
5,35143339,Gurusamy,Rajalakshmi,R,"Department of Information Technology, Sethu In..."
7,35271383,Mara,Alexandru Cristian,AC,Department of Electronics and Information Syst...
10,35385378,Abidin,Nihan,N,Clinic of Physical Medicine and Rehabilitation...
...,...,...,...,...,...
361930,40455154,Acharya,Vishal,V,Academy of Scientific and Innovative Research ...
361931,40455159,Bhargava,Harshita,H,"Department of Computer Science and IT, IIS (De..."
361932,40455159,Bhargava,Harshita,H,"Bioclues.org, Pune, India."
361935,40455159,Valadi,Jayaraman K,JK,"Department of Computer Science, FLAME Universi..."
361938,40455159,Chatterjee,Sreemoyee,S,"Department of Biotechnology, IIS (Deemed to be..."

In [ ]:
! pip install langchain
! pip install langchain-community

Requirement already satisfied: langchain in /opt/homebrew/anaconda3/lib/python3.12/site-packages (0.2.9)
Requirement already satisfied: PyYAML>=5.3 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (2.0.30)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (3.9.5)
Requirement already satisfied: langchain-core<0.3.0,>=0.2.20 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (0.2.21)
Requirement already satisfied: langchain-text-splitters<0.3.0,>=0.2.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (0.2.2)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (0.1.91)
Requirement already satisfied: numpy<2.0.0,>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (1.26.4)
Requirement already satisfied: pydantic<3,>=1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (2.8.2)
Requirement already satisfied: requests<3,>=2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (2.32.2)
Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain) (8.2.2)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.9.3)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-core<0.3.0,>=0.2.20->langchain) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-core<0.3.0,>=0.2.20->langchain) (23.2)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (3.10.6)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1->langchain) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1->langchain) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1->langchain) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain) (2024.6.2)
Requirement already satisfied: jsonpointer>=1.9 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.20->langchain) (2.1)
Collecting langchain-community
  Downloading langchain_community-0.2.7-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: PyYAML>=5.3 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (2.0.30)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (3.9.5)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: langchain<0.3.0,>=0.2.7 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (0.2.9)
Requirement already satisfied: langchain-core<0.3.0,>=0.2.12 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (0.2.21)
Requirement already satisfied: langsmith<0.2.0,>=0.1.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (0.1.91)
Requirement already satisfied: numpy<2.0.0,>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (1.26.4)
Requirement already satisfied: requests<3,>=2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (2.32.2)
Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-community) (8.2.2)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.9.3)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading marshmallow-3.21.3-py3-none-any.whl.metadata (7.1 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: langchain-text-splitters<0.3.0,>=0.2.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain<0.3.0,>=0.2.7->langchain-community) (0.2.2)
Requirement already satisfied: pydantic<3,>=1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain<0.3.0,>=0.2.7->langchain-community) (2.8.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-core<0.3.0,>=0.2.12->langchain-community) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langchain-core<0.3.0,>=0.2.12->langchain-community) (23.2)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from langsmith<0.2.0,>=0.1.0->langchain-community) (3.10.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain-community) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain-community) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain-community) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from requests<3,>=2->langchain-community) (2024.6.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from SQLAlchemy<3,>=1.4->langchain-community) (4.11.0)
Requirement already satisfied: jsonpointer>=1.9 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.12->langchain-community) (2.1)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1->langchain<0.3.0,>=0.2.7->langchain-community) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1->langchain<0.3.0,>=0.2.7->langchain-community) (2.20.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community) (1.0.0)
Downloading langchain_community-0.2.7-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 15.2 MB/s eta 0:00:00a 0:00:01
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading marshmallow-3.21.3-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 3.1 MB/s eta 0:00:00
Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Installing collected packages: typing-inspect, marshmallow, dataclasses-json, langchain-community
Successfully installed dataclasses-json-0.6.7 langchain-community-0.2.7 marshmallow-3.21.3 typing-inspect-0.9.0

In [ ]:
unique_affiliations_df.iloc[1]["Affiliation"]

'Department of biostatistics, Faculty of Medical Sciences, Tarbiat Modares university, Tehran, Iran.'

In [ ]:
from langchain_community.llms import Ollama

llm = Ollama(model="llama3")

# Define the prompt text
prompt_text = """
Given this affiliation: 

- {affiliation}

PLEASE GIVE ME ONLY THE NAME OF THE CORRESPONDING COUNTRY. PLEASE REFRAIN FROM USING ABBREVIATIONS FOR COUNTRY NAMES. If you are unable to identify the country, please return "NONE".
"""

# Initialize a list to store the results
countries = []

# Ensure we only process the first 100 rows
num_rows_to_process = min(len(unique_affiliations_df), 20000)

# Iterate over the first 100 rows
for index in range(num_rows_to_process):
    # Get the affiliation item from the current row
    item = unique_affiliations_df.iloc[index]["Affiliation"]
    # Format the prompt with the current affiliation
    prompt_with_item = prompt_text.format(affiliation=item)
    # Invoke the LLM
    country_name = llm.invoke(prompt_with_item, max_tokens=100)
    # Append the country name to the results list
    countries.append({"Affiliation": item, "Country": country_name})

# Print the results
for i, country in enumerate(countries):
    print(f"Row {i+1}: {country}")

Row 1: {'Affiliation': 'Department of biophysics, Faculty of Basic Sciences, Tarbiat Modares University, Tehran, Iran.', 'Country': 'Iran'}
Row 2: {'Affiliation': 'Department of biostatistics, Faculty of Medical Sciences, Tarbiat Modares university, Tehran, Iran.', 'Country': 'Iran'}
Row 3: {'Affiliation': ', Bangkhae, Bangkok, 10160, Thailand. wviroj@yahoo.com.', 'Country': 'Thailand'}
Row 4: {'Affiliation': 'Department of Biomedical Informatics, Columbia University, 622 W 168th Street, PH20, New York, NY 10032, USA; Medical Informatics Services, NewYork-Presbyterian Hospital, 622 W 168th Street, PH20, New York, NY 10032, USA. Electronic address: hripcsak@columbia.edu.', 'Country': 'United States'}
Row 5: {'Affiliation': 'Department of Medical Informatics, Linköping University, 58183 Linköping, Sweden.', 'Country': 'Sweden'}
Row 6: {'Affiliation': 'Department of Biomedical Informatics, Columbia University, 622 W 168th Street, PH20, New York, NY 10032, USA; Department of Biomedical Informatics, University of Utah, 421 Wakara Way, Ste 140, Salt Lake City, UT 84108, USA.', 'Country': 'United States'}
Row 7: {'Affiliation': 'Center for Communication and Information Technology, University Hospital Erlangen, Glückstraße 11, 91054 Erlangen, Germany; Department of Medical Informatics, Biometrics and Epidemiology, Chair of Medical Informatics, Friedrich-Alexander-University Erlangen-Nuremberg, Wetterkreuz 13, 91058 Erlangen-Tennenlohe, Germany. Electronic address: stefan.kraus@uk-erlangen.de.', 'Country': 'Germany'}
Row 8: {'Affiliation': 'Center for Communication and Information Technology, University Hospital Erlangen, Glückstraße 11, 91054 Erlangen, Germany. Electronic address: martin.enders@uk-erlangen.de.', 'Country': 'Germany'}
Row 9: {'Affiliation': 'Center for Communication and Information Technology, University Hospital Erlangen, Glückstraße 11, 91054 Erlangen, Germany; Department of Medical Informatics, Biometrics and Epidemiology, Chair of Medical Informatics, Friedrich-Alexander-University Erlangen-Nuremberg, Wetterkreuz 13, 91058 Erlangen-Tennenlohe, Germany. Electronic address: ulli.prokosch@imi.med.uni-erlangen.de.', 'Country': 'Germany'}
Row 10: {'Affiliation': 'Department of Anaesthesiology, University Hospital Erlangen, Krankenhausstraße 12, 91054 Erlangen, Germany. Electronic address: ixchel.castellanos@kfa.imed.uni-erlangen.de.', 'Country': 'Germany'}
Row 11: {'Affiliation': 'Department of Computer Science, Chair of Computer Science 6 (Data Management), Martensstraße 3, 91058 Erlangen, Germany. Electronic address: richard.lenz@fau.de.', 'Country': 'Germany'}
Row 12: {'Affiliation': 'Department of Medical Informatics, Biometrics and Epidemiology, Chair of Medical Informatics, Friedrich-Alexander-University Erlangen-Nuremberg, Wetterkreuz 13, 91058 Erlangen-Tennenlohe, Germany. Electronic address: martin.sedlmayr@fau.de.', 'Country': 'Germany'}
Row 13: {'Affiliation': 'Department of Anaesthesiology, University Hospital Erlangen, Krankenhausstr. 12, 91054 Erlangen, Germany. Electronic address: ixchel.castellanos@kfa.imed.uni-erlangen.de.', 'Country': 'Germany'}
Row 14: {'Affiliation': 'Center for Communication and Information Technology, University Hospital Erlangen, Glückstr. 11, 91054 Erlangen, Germany; Department of Medical Informatics, Biometrics and Epidemiology, Chair of Medical Informatics, Friedrich-Alexander-University Erlangen-Nuremberg, Wetterkreuz 13, 91058 Erlangen, Germany.', 'Country': 'Germany'}
Row 15: {'Affiliation': 'Department of Medical Informatics, Biometrics and Epidemiology, Chair of Medical Informatics, Friedrich-Alexander-University Erlangen-Nuremberg, Wetterkreuz 13, 91058 Erlangen, Germany.', 'Country': 'Germany'}
Row 16: {'Affiliation': 'Bern University of Applied Sciences, Institute for Medical Informatics, Höheweg 80, CH-2502 Biel, Switzerland.', 'Country': 'Switzerland'}
Row 17: {'Affiliation': "Children's Hospital and Pediatric Institute, Cleveland Clinic, 9500 Euclid Avenue, Cleveland, OH 44195, USA. Electronic address: anandv@ccf.org.", 'Country': 'United States'}
Row 18: {'Affiliation': 'Pediatric and Adolescent Comparative Effectiveness Research, Indiana University, Riley Child Development Center, 705 Riley Hospital Drive, Room 5837, Indianapolis, IN 46202, USA; Regenstrief Institute, Inc., 410 West 10th Street, Suite 2000, Indianapolis, IN 46202-3012, USA.', 'Country': 'United States'}
Row 19: {'Affiliation': "Regenstrief Institute, Inc., 410 West 10th Street, Suite 2000, Indianapolis, IN 46202-3012, USA; Children's Health Services Research, Indiana University, 410 West 10th Street, Suite 1000, Indianapolis, IN 46202-3012, USA.", 'Country': 'United States'}
Row 20: {'Affiliation': "Children's Health Services Research, Indiana University, 410 West 10th Street, Suite 1000, Indianapolis, IN 46202-3012, USA.", 'Country': 'United States'}
Row 21: {'Affiliation': 'Section for Medical Expert and Knowledge-Based Systems, Center for Medical Statistics, Informatics, and Intelligent Systems, Medical University of Vienna, Spitalgasse 23, A-1090 Vienna, Austria. Electronic address: jeroen.debruin@meduniwien.ac.at.', 'Country': 'Austria'}
Row 22: {'Affiliation': 'Section for Medical Expert and Knowledge-Based Systems, Center for Medical Statistics, Informatics, and Intelligent Systems, Medical University of Vienna, Spitalgasse 23, A-1090 Vienna, Austria.', 'Country': 'Austria'}
Row 23: {'Affiliation': 'Institute for Social Medicine, Center for Public Health, Medical University of Vienna, Kinderspitalgasse 15, A-1090 Vienna, Austria.', 'Country': 'Austria'}
Row 24: {'Affiliation': 'Department of Internal Medicine III, Vienna General Hospital, Waehringer Guertel 18-20, A-1090 Vienna, Austria.', 'Country': 'Austria'}
Row 25: {'Affiliation': 'Department of Internal Medicine I, Vienna General Hospital, Waehringer Guertel 18-20, A-1090 Vienna, Austria.', 'Country': 'Austria'}
Row 26: {'Affiliation': 'Krankenhaus Rudolfstiftung, Department of Internal Medicine I, Juchgasse 25, A-1030 Vienna, Austria.', 'Country': 'Austria'}
Row 27: {'Affiliation': 'Hospital of the Brothers of St. John of God, Kajetanerplatz 1, A-5010 Salzburg, Austria; Special Institute for Preventive Cardiology and Nutrition (SIPCAN), Guggenbichlerstraße 8/15, A-5026 Salzburg, Austria.', 'Country': 'Austria'}
Row 28: {'Affiliation': 'Department of Computer Engineering, Kyung Hee University, Seocheon-dong, Giheung-gu, Yongin-si 446-701, Gyeonggi-do, Republic of Korea. Electronic address: maqbool.hussain@oslab.khu.ac.kr.', 'Country': 'South Korea'}
Row 29: {'Affiliation': 'Department of Computer Engineering, Kyung Hee University, Seocheon-dong, Giheung-gu, Yongin-si 446-701, Gyeonggi-do, Republic of Korea. Electronic address: muhammad.afzal@oslab.khu.ac.kr.', 'Country': 'South Korea'}
Row 30: {'Affiliation': 'Department of Computer Engineering, Kyung Hee University, Seocheon-dong, Giheung-gu, Yongin-si 446-701, Gyeonggi-do, Republic of Korea. Electronic address: taqdir.ali@oslab.khu.ac.kr.', 'Country': 'South Korea'}
Row 31: {'Affiliation': 'Department of Computer Engineering, Kyung Hee University, Seocheon-dong, Giheung-gu, Yongin-si 446-701, Gyeonggi-do, Republic of Korea. Electronic address: rahmanali@oslab.khu.ac.kr.', 'Country': 'South Korea'}
Row 32: {'Affiliation': 'Department of Computer Engineering, Kyung Hee University, Seocheon-dong, Giheung-gu, Yongin-si 446-701, Gyeonggi-do, Republic of Korea. Electronic address: wajahat.alikhan@oslab.khu.ac.kr.', 'Country': 'South Korea'}
Row 33: {'Affiliation': 'Department of Radiation Oncology, Shaukat Khanum Memorial Cancer Hospital and Research Centre, 7A Block R-3, M.A. Johar Town, Lahore 54782, Pakistan. Electronic address: arifj@skm.org.pk.', 'Country': 'Pakistan'}
Row 34: {'Affiliation': 'Department of Computer Engineering, Kyung Hee University, Seocheon-dong, Giheung-gu, Yongin-si 446-701, Gyeonggi-do, Republic of Korea. Electronic address: sylee@oslab.khu.ac.kr.', 'Country': 'South Korea'}
Row 35: {'Affiliation': 'Computing and Information Systems, University of Tasmania, Hobart 7001, Tasmania, Australia. Electronic address: byeong.Kang@utas.edu.au.', 'Country': 'Australia'}
Row 36: {'Affiliation': 'Department of Computer Science, COMSATS Institute of Information Technology, Park Road, Islamabad 45550, Pakistan. Electronic address: khalid.latif@comsats.edu.pk.', 'Country': 'Pakistan'}
Row 37: {'Affiliation': 'Department of Medical Informatics, Biometrics and Epidemiology, Chair of Medical Informatics, Friedrich-Alexander-University Erlangen-Nuremberg, Wetterkreuz 13, 91058 Erlangen-Tennenlohe, Germany.', 'Country': 'Germany'}
Row 38: {'Affiliation': 'Department of Anaesthesiology, University Hospital Erlangen, Krankenhausstraße 12, 91054 Erlangen, Germany.', 'Country': 'Germany'}
Row 39: {'Affiliation': 'Center for Communication and Information Technology, University Hospital Erlangen, Glückstraße 11, 91054 Erlangen, Germany; Department of Medical Informatics, Biometrics and Epidemiology, Chair of Medical Informatics, Friedrich-Alexander-University Erlangen-Nuremberg, Wetterkreuz 13, 91058 Erlangen-Tennenlohe, Germany.', 'Country': 'Germany'}
Row 40: {'Affiliation': 'Functional Neurosurgery Research Center, Shahid Beheshti University of Medical Sciences, Tehran, Iran - parisa.azimi@gmail.com.', 'Country': 'Iran'}
Row 41: {'Affiliation': 'Functional Neurosurgery Research Center, Shahid Beheshti University of Medical Sciences, Tehran, Iran.', 'Country': 'Iran'}
Row 42: {'Affiliation': 'Section for Medical Expert and Knowledge-Based Systems, Center for Medical Statistics, Informatics, and Intelligent Systems, Medical University of Vienna, Spitalgasse 23, A-1090 Vienna, Austria; IT Systems & Communications, Medical University of Vienna, Spitalgasse 23, A-1090 Vienna, Austria.', 'Country': 'Austria'}
Row 43: {'Affiliation': 'Department of Medical Informatics, Henri Mondor Hospital, Assistance Publique Hôpitaux de Paris, 51 av. Du Mal de Lattre, 94010 Creteil, France. Electronic address: harry.karadimas@hmn.aphp.fr.', 'Country': 'France'}
Row 44: {'Affiliation': 'Department of Medical Informatics, Henri Mondor Hospital, Assistance Publique Hôpitaux de Paris, 51 av. Du Mal de Lattre, 94010 Creteil, France.', 'Country': 'France'}
Row 45: {'Affiliation': 'Faculty of Medicine, University Paris-Est, 8, rue du Général Sarrail, 94010 Creteil, France.', 'Country': 'France'}
Row 46: {'Affiliation': 'Department of Computer Science and Electrical Engineering, University of Maryland, Baltimore County, 1000 Hilltop Circle, Baltimore, MD, 21250, USA. demge1@umbc.edu.', 'Country': 'United States'}
Row 47: {'Affiliation': 'SIGnal processing and MAchine learning (SIGMA) lab, ESPCI ParisTech, 10, rue Vauquelin, 75231, Paris Cedex 05, France.', 'Country': 'France'}
Row 48: {'Affiliation': 'Department of Computer Science and Electrical Engineering, University of Maryland, Baltimore County, 1000 Hilltop Circle, Baltimore, MD, 21250, USA.', 'Country': 'United States'}
Row 49: {'Affiliation': 'Department of Pathogen Biology and Experimental Teaching Centre of Preventive Medicine, Key Laboratory of Prevention and Control for Emerging Infectious Diseases of Guangdong Higher Institutes, Key Laboratory for Tropical Disease Research of Guangdong Province, School of Public Health, Southern Medical University, Guangzhou, China.', 'Country': 'China'}
Row 50: {'Affiliation': 'Department of Parasitology, Zhongshan School of Medicine, Sun Yat-sen University, Guangzhou, 510080, Guangdong Province, China.', 'Country': 'China'}
Row 51: {'Affiliation': 'Department of Parasitology, College of Medicine, National Cheng Kung University, Tainan 701, Taiwan.', 'Country': 'Taiwan'}
Row 52: {'Affiliation': 'Department of Entomology, Pennsylvania State University, 501 ASI Building, University Park, PA 16802, USA.', 'Country': 'United States'}
Row 53: {'Affiliation': 'Department of Pathogen Biology and Experimental Teaching Centre of Preventive Medicine, Key Laboratory of Prevention and Control for Emerging Infectious Diseases of Guangdong Higher Institutes, Key Laboratory for Tropical Disease Research of Guangdong Province, School of Public Health, Southern Medical University, Guangzhou, China. Electronic address: lih@smu.edu.cn.', 'Country': 'China'}
Row 54: {'Affiliation': 'Department of Urology, University of California Irvine Health, Orange, California.', 'Country': 'United States'}
Row 55: {'Affiliation': 'University of Washington School of Medicine, Seattle, USA.', 'Country': 'United States'}
Row 56: {'Affiliation': "Seattle Children's Hospital, Seattle, USA.", 'Country': 'United States'}
Row 57: {'Affiliation': 'University of Washington, Department of Industrial and Systems Engineering, Seattle, USA.', 'Country': 'United States'}
Row 58: {'Affiliation': 'University of Washington, Department of Radiology, Seattle, USA.', 'Country': 'United States'}
Row 59: {'Affiliation': 'University of Washington, Department of Neurology, Seattle, USA.', 'Country': 'United States'}
Row 60: {'Affiliation': 'University of Minnesota Medical School, Minneapolis, USA.', 'Country': 'United States'}
Row 61: {'Affiliation': 'University of Texas Health and Science Center, San Antonio, USA.', 'Country': 'United States'}
Row 62: {'Affiliation': '1 Intelligent Systems Group, University of the Basque Country UPV/EHU, Spain.', 'Country': 'Spain'}
Row 63: {'Affiliation': '2 Unit of Assisted Reproduction, Osakidetza - Basque Public Health Service, Spain.', 'Country': 'Spain'}
Row 64: {'Affiliation': '3 Basque Center for Applied Mathematics BCAM, Spain.', 'Country': 'Spain'}
Row 65: {'Affiliation': 'Laboratory for Intelligent Imaging and Neural Computing, Columbia University, New York, NY, 10027, USA. stefan.haufe@tu-berlin.de.', 'Country': 'United States'}
Row 66: {'Affiliation': 'Machine Learning Department, Technische Universität Berlin, 10587, Berlin, Germany. stefan.haufe@tu-berlin.de.', 'Country': 'Germany'}
Row 67: {'Affiliation': 'Department of Neurophysiology and Pathophysiology, University Medical Center Hamburg-Eppendorf, 20246, Hamburg, Germany.', 'Country': 'Germany'}
Row 68: {'Affiliation': 'Department of Radiation Oncology.', 'Country': 'Based on the department name "Department of Radiation Oncology", I am unable to identify a specific country. Therefore, my answer is:\n\nNONE'}
Row 69: {'Affiliation': 'Neurological Surgery, Mount Sinai Health System.', 'Country': 'United States'}
Row 70: {'Affiliation': 'Department of Neurosurgery, New York University Langone Medical Center, New York City, NY.', 'Country': 'United States'}
Row 71: {'Affiliation': 'Department of Radiation Medicine, Georgetown University Medical Center, Washington, DC.', 'Country': 'United States'}
Row 72: {'Affiliation': 'Department of Neurological Surgery, The University of North Carolina at Chapel Hill, Chapel Hill, NC.', 'Country': 'United States'}
Row 73: {'Affiliation': 'Department of Preventive Medicine, The Catholic University of Korea, 222 Banpo-daero, Seocho-gu, Seoul 06591, Republic of Korea.', 'Country': 'South Korea'}
Row 74: {'Affiliation': 'Digital Team, Zuelligpharma Korea SSK, 92 Hangang-daero, Yongsan-gu, Seoul 04386, Republic of Korea.', 'Country': 'South Korea'}
Row 75: {'Affiliation': 'National Health Insurance Corporation Ilsan Hospital, 100 Ilsan-ro, Ilsandong-gu, Goyang-si, Gyeonggi-do 10444, Republic of Korea.', 'Country': 'South Korea'}
Row 76: {'Affiliation': 'KoreaExpert Inc., 21 Yangpyeong-ro 22-gil, Yeongdeungpo-gu, Seoul 07205, Republic of Korea.', 'Country': 'South Korea'}
Row 77: {'Affiliation': 'Department of Preventive Medicine, The Catholic University of Korea, 222 Banpo-daero, Seocho-gu, Seoul 06591, Republic of Korea. Electronic address: sikimmd@gmail.com.', 'Country': 'South Korea'}
Row 78: {'Affiliation': 'United Nations Population Division, New York.', 'Country': 'United States'}
Row 79: {'Affiliation': 'Department of Sociology, Centre of Family and Population Research, National University of Singapore, Singapore.', 'Country': 'Singapore'}
Row 80: {'Affiliation': 'National Research Council of Italy, Italy.', 'Country': 'Italy'}
Row 81: {'Affiliation': 'Rulex Inc, USA.', 'Country': 'United States'}
Row 82: {'Affiliation': 'Italian Institute of Technology, Italy.', 'Country': 'Italy'}
Row 83: {'Affiliation': '1 Department of Anesthesia and Perioperative Care, UCSF, San Francisco General Hospital, San Francisco, CA, USA.', 'Country': 'United States'}
Row 84: {'Affiliation': '2 Brain and Spinal Injury Center, San Francisco, CA, USA.', 'Country': 'United States'}
Row 85: {'Affiliation': '3 Department of Neurosurgery, University of California San Francisco, San Francisco, CA, USA.', 'Country': 'United States'}
Row 86: {'Affiliation': '4 Division of Biostatistics, School of Public Health, University of California Berkeley, Berkeley, CA, USA.', 'Country': 'United States'}
Row 87: {'Affiliation': 'AVRDC - The World Vegetable Center, Shanhua, Tainan, Taiwan, China.', 'Country': 'Taiwan'}
Row 88: {'Affiliation': 'Department of Urology, University of California, Irvine.', 'Country': 'United States'}
Row 89: {'Affiliation': 'Department of Surgery, University of California, Irvine.', 'Country': 'United States'}
Row 90: {'Affiliation': 'Departamento de Psicología Cognitiva, Social y Organizacional, University of La Laguna, Tenerife, Spain.', 'Country': 'Spain'}
Row 91: {'Affiliation': 'Departamento de Didáctica e Investigación Educativa, University of La Laguna, Tenerife, Spain.', 'Country': 'Spain'}
Row 92: {'Affiliation': 'Department of Psychology, Université catholique de Louvain, Louvain-la-Neuve, Belgium.', 'Country': 'Belgium'}
Row 93: {'Affiliation': 'Universidad Europea de Madrid, Spain.', 'Country': 'Spain'}
Row 94: {'Affiliation': 'Stockholm University, Sweden.', 'Country': 'Sweden'}
Row 95: {'Affiliation': 'KTH Royal Institute of Technology, Sweden.', 'Country': 'Sweden'}
Row 96: {'Affiliation': 'University of Helsinki, Finland.', 'Country': 'Finland'}
Row 97: {'Affiliation': 'Tung Wah College, Hong Kong.', 'Country': 'Hong Kong'}
Row 98: {'Affiliation': 'The University of Hong Kong, Hong Kong.', 'Country': 'China'}
Row 99: {'Affiliation': 'Universidade Nova de Lisboa, Portugal.', 'Country': 'Portugal'}
Row 100: {'Affiliation': 'INESC-ID, Portugal.', 'Country': 'Portugal'}
Row 101: {'Affiliation': 'APDP ERC, Portugal.', 'Country': 'Portugal'}
Row 102: {'Affiliation': 'a The Oliver Zangwill Centre for Neuropsychological Rehabilitation , Cambridgeshire Community Services (NHS) Trust , Ely Cambridgeshire , UK.', 'Country': 'United Kingdom'}
Row 103: {'Affiliation': 'b School of Psychology , University of Surrey , Guildford , UK.', 'Country': 'United Kingdom'}
Row 104: {'Affiliation': 'c Royal Hospital for Neuro-disability , London , UK.', 'Country': 'United Kingdom'}
Row 105: {'Affiliation': 'd Department of Clinical Psychology and The Acquired Brain Injury Rehabilitation Affiliation, Faculty of Medicine and Health , University of East Anglia , Norwich , UK.', 'Country': 'United Kingdom'}
Row 106: {'Affiliation': 'School of Computer Science and Engineering, Lovely Professional University, Chaheru, Punjab, India. divyaanand.y@gmail.com.', 'Country': 'India'}
Row 107: {'Affiliation': 'School of Computer Applications, Lovely Professional University, Chaheru, Punjab, India.', 'Country': 'India'}
Row 108: {'Affiliation': 'School of Biosciences, Lovely Professional University, Chaheru, Punjab, India.', 'Country': 'India'}
Row 109: {'Affiliation': 'Instituto Tecnológico de Tijuana, Mexico.', 'Country': 'Mexico'}
Row 110: {'Affiliation': 'a Department of Electrical and Electronics Engineering, School of Engineering , Nazarbayev University , Astana , Kazakhstan.', 'Country': 'Kazakhstan'}
Row 111: {'Affiliation': 'b School of Mechanical, Materials and Mechatronic Engineering , University of Wollongong , NSW , Wollongong, Australia.', 'Country': 'Australia'}

In [ ]:
df = pd.DataFrame(countries)
df.to_csv('./data/countries_affiliation_20k.csv', index=False)

In [ ]:
unique_affiliations_df

,PMID,LastName,ForeName,Initials,Affiliation
0,17379690,Mehdi,Poursheikhali Asgary,PA,"Department of biophysics, Faculty of Basic Sci..."
2,17379690,Anoshirvan,Kazemnejad,K,"Department of biostatistics, Faculty of Medica..."
4,20585802,Wiwanitkit,Viroj,V,", Bangkhae, Bangkok, 10160, Thailand. wviroj@y..."
5,26254699,Hripcsak,George,G,"Department of Biomedical Informatics, Columbia..."
6,26254699,Wigertz,Ove B,OB,"Department of Medical Informatics, Linköping U..."
...,...,...,...,...,...
1587872,39018040,Kroon,Jeffrey,J,Laboratory of Angiogenesis and Vascular Metabo...
1587873,39018040,Planken,R Nils,RN,"Department of Radiology and Nuclear Medicine, ..."
1587882,39018100,Anmella,Gerard,G,"Bipolar and Depressive Disorders Unit, Departm..."
1587885,39018100,Anmella,Gerard,G,"Departament de Medicina, Facultat de Medicina ..."
1587921,39018100,Whalley,Heather C,HC,"Generation Scotland, Institute for Genetics an..."

In [ ]:
canada_affiliations_df = unique_affiliations_df[unique_affiliations_df['Affiliation'].str.contains(
    'Canada', case=False, na=False)]

In [ ]:
len(unique_affiliations_df)

681447

In [ ]:
canada_affiliations_df

,PMID,LastName,ForeName,Initials,Affiliation
532,28350526,Lindsay,Sally,S,a Department of Occupational Science and Occup...
533,28350526,Lam,Ashley,A,"b Health Sciences, McMaster University , Hamil..."
692,28444633,Shahnazian,Danesh,D,"Department of Psychology, University of Victor..."
693,28444633,Holroyd,Clay B,CB,"Department of Psychology, University of Victor..."
866,28550657,Hollis,Geoff,G,"Department of Psychology, University of Albert..."
...,...,...,...,...,...
1587140,39013867,Ding,Jun,J,"School of Computer Science, McGill University,..."
1587141,39013867,Ding,Jun,J,"Mila-Quebec AI Institute, 6666 Rue Saint-Urbai..."
1587419,39015068,Wolter,Nikolaus E,NE,Department of Otolaryngology- Head and Neck Su...
1587460,39015268,Choudhary,Ruhi,R,Department of Chemical Engineering and Applied...
1587713,39016161,Burns,Catherine,C,"Department of Systems Design Engineering, Univ..."

In [ ]:
! pip install pycountry
! pip install pandas geopy geonamescache

Requirement already satisfied: pycountry in /opt/homebrew/anaconda3/lib/python3.12/site-packages (24.6.1)
Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.12/site-packages (2.2.2)
Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geonamescache
  Downloading geonamescache-2.0.0-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.4/125.4 kB 2.0 MB/s eta 0:00:00 0:00:01
Downloading geonamescache-2.0.0-py3-none-any.whl (26.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 5.7 MB/s eta 0:00:0000:0100:01m
Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 2.0 MB/s eta 0:00:00
Installing collected packages: geonamescache, geographiclib, geopy
Successfully installed geographiclib-2.0 geonamescache-2.0.0 geopy-2.4.1

In [ ]:
gc.get_countries()

NameError: name 'gc' is not defined

In [ ]:
import re
import geonamescache

gc = geonamescache.GeonamesCache()

# Get country names from geonamescache
countries = gc.get_countries()
country_names = {country['name'] for country in countries.values()}

# Get US states from geonamescache
us_states = gc.get_us_states()
us_state_names = {state['name'] for state in us_states.values()}

# Get city names from geonamescache and map to their countries
cities = gc.get_cities()
city_country_map = {
    city['name']: countries[city['countrycode']]['name'] for city in cities.values()}

# Define a mapping for common variations
country_variations = {
    "México": "Mexico",
    "Brasil": "Brazil",
    "Türkiye": "Turkey",
    "USA": "United States",
    "U.S.A.": "United States",
    "America": "United States",
    "United States of America": "United States",
    "UK": "United Kingdom",
    "U.K.": "United Kingdom",
    "England": "United Kingdom",
    "Scotland": "United Kingdom",
    "Wales": "United Kingdom",
    "Northern Ireland": "United Kingdom",
    "South Korea": "Korea, Republic of",
    "UAE": "United Arab Emirates",
    "Italia": "Italy",
    "Republic of Korea": "Korea, Republic of",
    "Korea": "Korea, Republic of",
    "North Korea": "Korea, Democratic People's Republic of",
    "Russia": "Russian Federation",
    "Iran": "Islamic Republic of Iran",
}

# Function to extract countries from the affiliation text


def extract_countries(affiliation):
    found_countries = set()

    # Check for country names
    for country in country_names:
        if re.search(r'\b' + re.escape(country) + r'\b', affiliation, re.IGNORECASE):
            found_countries.add(country)

    # Check for country variations
    if len(found_countries) == 0:
        for variation, standard_country in country_variations.items():
            if re.search(r'\b' + re.escape(variation) + r'\b', affiliation, re.IGNORECASE):
                found_countries.add(standard_country)

    # Check for US states
    if len(found_countries) == 0:
        for state in us_state_names:
            if re.search(r'\b' + re.escape(state) + r'\b', affiliation, re.IGNORECASE):
                found_countries.add("United States")
                break

    # Check for city names and map to countries
    if len(found_countries) == 0:
        for city, country in city_country_map.items():
            if re.search(r'\b' + re.escape(city) + r'\b', affiliation, re.IGNORECASE):
                found_countries.add(country)
                break

    return found_countries


# Example DataFrame usage (assuming unique_affiliations_df exists)
unique_affiliations_df['tag_countries'] = unique_affiliations_df['Affiliation'].apply(
    extract_countries)

/var/folders/gx/4hmfp0zd12bblv6znjwbmv600000gn/T/ipykernel_56137/1539185840.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_affiliations_df['tag_countries'] = unique_affiliations_df['Affiliation'].apply(

In [ ]:
unique_affiliations_df.to_csv(
    './data/countries_affiliation_search_approach_2025.csv', index=False)

In [ ]:
unique_affiliations_df

,PMID,LastName,ForeName,Initials,Affiliation,tag_countries
0,35108088,Dai,Fei,F,School of Big Data and Intelligent Engineering...,{China}
3,35108088,Mo,Qi,Q,"School of Software, Yunnan University, Kunming...",{China}
5,35143339,Gurusamy,Rajalakshmi,R,"Department of Information Technology, Sethu In...",{India}
7,35271383,Mara,Alexandru Cristian,AC,Department of Electronics and Information Syst...,{Belgium}
10,35385378,Abidin,Nihan,N,Clinic of Physical Medicine and Rehabilitation...,{Turkey}
...,...,...,...,...,...,...
361930,40455154,Acharya,Vishal,V,Academy of Scientific and Innovative Research ...,{India}
361931,40455159,Bhargava,Harshita,H,"Department of Computer Science and IT, IIS (De...",{India}
361932,40455159,Bhargava,Harshita,H,"Bioclues.org, Pune, India.",{India}
361935,40455159,Valadi,Jayaraman K,JK,"Department of Computer Science, FLAME Universi...",{India}
361938,40455159,Chatterjee,Sreemoyee,S,"Department of Biotechnology, IIS (Deemed to be...",{India}

In [ ]:
grouped_by_pmid = unique_affiliations_df.groupby(
    'PMID')['tag_countries'].apply(list).reset_index(name='tags')
grouped_by_pmid

           PMID                                         tags
0      35108088                           [{China}, {China}]
1      35143339                                    [{India}]
2      35271383                                  [{Belgium}]
3      35385378                                   [{Turkey}]
4      35534328         [{China}, {China}, {China}, {China}]
...         ...                                          ...
39779  40454687  [{China}, {China}, {China, Macao}, {China}]
39780  40455017                         [{Russia}, {Russia}]
39781  40455151                 [{India}, {France}, {India}]
39782  40455154                  [{India}, {India}, {India}]
39783  40455159         [{India}, {India}, {India}, {India}]

[39784 rows x 2 columns]

In [ ]:
df_with_country = pd.merge(
    filtered_df_2025, grouped_by_pmid, on='PMID', how='left')
df_with_country

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle,tags
0,35108088,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '10', 'Day': '17'}","{'Year': '2025', 'Month': '04', 'Day': '30'}",Print-Electronic,2167-647X,...,[],"[Journal Article, Research Support, Non-U.S. G...","[{'Year': '2022', 'Month': '02', 'Day': '02', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35108088'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Tra...",NaN,"[{China}, {China}]"
1,35143339,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '12', 'Day': '16'}","{'Year': '2025', 'Month': '04', 'Day': '30'}",Print-Electronic,2167-647X,...,[],[Journal Article],"[{'Year': '2022', 'Month': '02', 'Day': '10', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35143339'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Dee...",NaN,[{India}]
2,35271383,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '12', 'Day': '16'}","{'Year': '2025', 'Month': '04', 'Day': '30'}",Print-Electronic,2167-647X,...,[],"[Journal Article, Research Support, Non-U.S. G...","[{'Year': '2022', 'Month': '03', 'Day': '10', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35271383'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Net...",NaN,[{Belgium}]
3,35385378,NLM,MEDLINE,,,Curated,"{'Year': '2024', 'Month': '10', 'Day': '23'}","{'Year': '2024', 'Month': '11', 'Day': '14'}",Print-Electronic,1949-3614,...,[],"[Journal Article, Controlled Clinical Trial]","[{'Year': '2022', 'Month': '05', 'Day': '05', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35385378'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN,[{Turkey}]
4,35486562,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '08', 'Day': '08'}","{'Year': '2025', 'Month': '01', 'Day': '07'}",Print-Electronic,1557-9964,...,"[{'GrantID': 'U01 AG024904', 'Acronym': 'AG', ...","[Journal Article, Research Support, U.S. Gov't...","[{'Year': '2024', 'Month': '08', 'Day': '08', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '35486562'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Alz...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42649,40455017,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,0023-1207,...,[],"[English Abstract, Journal Article]",[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455017'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': 'OBJECTIVE', 'NlmCategory': 'OBJECT...",Prognosticheskaya model' i kal'kulyator otsenk...,"[{Russia}, {Russia}]"
42650,40455151,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455151'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Vir...",NaN,"[{India}, {France}, {India}]"
42651,40455152,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455152'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Und...",NaN,NaN
42652,40455154,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455154'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN,"[{India}, {India}, {India}]"
42653,40455159,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '06', 'Day': '02'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print,1940-6029,...,[],[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40455159'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN,"[{India}, {India}, {India}, {India}]"

In [ ]:
df_with_country.to_csv(
    './data/countries_affiliation_df_with_country.csv', index=False)

In [ ]:
# type(df_with_country.iloc[0]['tags'])
canada_df = df_with_country[df_with_country['tags'].apply(
    lambda x: isinstance(x, list) and {'Canada'} in x)]
canada_df

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle,tags
99,37310046,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '10', 'Day': '25'}","{'Year': '2024', 'Month': '10', 'Day': '25'}",Print-Electronic,1521-4095,...,"[{'GrantID': 'K99 AG065495', 'Acronym': 'AG', ...",[Journal Article],"[{'Year': '2023', 'Month': '07', 'Day': '19', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '37310046'}, {'...","[{'PubStatus': 'revised', 'Year': '2023', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Sof...",NaN,"[{United States}, {United States}, {United Sta..."
227,38019000,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '01', 'Day': '09'}","{'Year': '2025', 'Month': '01', 'Day': '09'}",Print-Electronic,1746-1553,...,"[{'GrantID': 'RGPIN-2018-04151', 'Acronym': No...",[Journal Article],"[{'Year': '2023', 'Month': '11', 'Day': '29', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38019000'}, {'...","[{'PubStatus': 'received', 'Year': '2022', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{Canada}, {Canada}, {Canada}, {Canada}]"
268,38190258,NLM,MEDLINE,,,Curated,"{'Year': '2025', 'Month': '01', 'Day': '15'}","{'Year': '2025', 'Month': '05', 'Day': '13'}",Print-Electronic,1949-3614,...,[],"[Journal Article, Randomized Controlled Trial]","[{'Year': '2024', 'Month': '01', 'Day': '08', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38190258'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Chi...",NaN,[{Canada}]
297,38263349,NLM,MEDLINE,,,Automated,"{'Year': '2024', 'Month': '10', 'Day': '08'}","{'Year': '2025', 'Month': '02', 'Day': '20'}",Print-Electronic,1543-0154,...,[],[Editorial],"[{'Year': '2024', 'Month': '01', 'Day': '23', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38263349'}, {'...","[{'PubStatus': 'accepted', 'Year': '2024', 'Mo...",[],NaN,NaN,"[{Canada}, {Canada}, {Canada}, {Canada}, {Cana..."
325,38326673,NLM,MEDLINE,,,Curated,"{'Year': '2025', 'Month': '02', 'Day': '03'}","{'Year': '2025', 'Month': '05', 'Day': '27'}",Print-Electronic,1532-7558,...,"[{'GrantID': 'RG 5144A6/1', 'Acronym': None, '...","[Journal Article, Randomized Controlled Trial]","[{'Year': '2024', 'Month': '02', 'Day': '07', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38326673'}, {'...","[{'PubStatus': 'accepted', 'Year': '2024', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{United States}, {United States}, {United Sta..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42512,40435158,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '05', 'Day': '28'}","{'Year': '2025', 'Month': '05', 'Day': '31'}",Electronic-eCollection,1932-6203,...,[],[Journal Article],"[{'Year': '2025', 'Month': '05', 'Day': '28', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40435158'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'PURPOSE', 'NlmCategory': 'OBJECTIV...",NaN,"[{Canada}, {Canada}, {Canada}]"
42557,40440093,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '05', 'Day': '29'}","{'Year': '2025', 'Month': '06', 'Day': '01'}",Print,2047-217X,...,"[{'GrantID': '01ZZ2004', 'Acronym': None, 'Age...",[Journal Article],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40440093'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Uns...",NaN,"[{United States}, {Russia}, {United States}, {..."
42560,40440289,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '05', 'Day': '29'}","{'Year': '2025', 'Month': '06', 'Day': '01'}",Electronic-eCollection,1932-6203,...,[],[Journal Article],"[{'Year': '2025', 'Month': '05', 'Day': '29', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40440289'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Cla...",NaN,[{Canada}]
42620,40448324,NLM,MEDLINE,,,Automated,"{'Year': '2025', 'Month': '05', 'Day': '31'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print-Electronic,2331-2165,...,[],[Journal Article],"[{'Year': '2025', 'Month': '05', 'Day': '30', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '40448324'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Spe...",NaN,"[{Canada}, {Canada}]"
42628,40452951,NLM,PubMed-not-MEDLINE,,,,NaN,"{'Year': '2025', 'Month': '06', 'Day': '02'}",Electronic-eCollection,1662-5188,...,[],[Journal Article],"[{'Year': '2025', 'Month': '05', 'Day': '16', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40452951'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{United States}, {Canada}, {Canada}, {France}..."

In [ ]:
canada_df.to_csv(
    './data/countries_affiliation_df_canada_2025.csv', index=False)

In [ ]:
import pandas as pd

# Replace 'your_file.csv' with the path to your CSV file
canada_df = pd.read_csv('./data/countries_affiliation_df_canada_2025.csv')

# Display the first few rows
canada_df

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle,tags
0,37310046,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '10', 'Day': '25'}","{'Year': '2024', 'Month': '10', 'Day': '25'}",Print-Electronic,1521-4095,...,"[{'GrantID': 'K99 AG065495', 'Acronym': 'AG', ...",['Journal Article'],"[{'Year': '2023', 'Month': '07', 'Day': '19', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '37310046'}, {'...","[{'PubStatus': 'revised', 'Year': '2023', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Sof...",NaN,"[{'United States'}, {'United States'}, {'Unite..."
1,38019000,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '01', 'Day': '09'}","{'Year': '2025', 'Month': '01', 'Day': '09'}",Print-Electronic,1746-1553,...,"[{'GrantID': 'RGPIN-2018-04151', 'Acronym': No...",['Journal Article'],"[{'Year': '2023', 'Month': '11', 'Day': '29', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38019000'}, {'...","[{'PubStatus': 'received', 'Year': '2022', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'}]"
2,38190258,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2025', 'Month': '01', 'Day': '15'}","{'Year': '2025', 'Month': '05', 'Day': '13'}",Print-Electronic,1949-3614,...,[],"['Journal Article', 'Randomized Controlled Tri...","[{'Year': '2024', 'Month': '01', 'Day': '08', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38190258'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Chi...",NaN,[{'Canada'}]
3,38263349,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '10', 'Day': '08'}","{'Year': '2025', 'Month': '02', 'Day': '20'}",Print-Electronic,1543-0154,...,[],['Editorial'],"[{'Year': '2024', 'Month': '01', 'Day': '23', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38263349'}, {'...","[{'PubStatus': 'accepted', 'Year': '2024', 'Mo...",[],NaN,NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'..."
4,38326673,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2025', 'Month': '02', 'Day': '03'}","{'Year': '2025', 'Month': '05', 'Day': '27'}",Print-Electronic,1532-7558,...,"[{'GrantID': 'RG 5144A6/1', 'Acronym': None, '...","['Journal Article', 'Randomized Controlled Tri...","[{'Year': '2024', 'Month': '02', 'Day': '07', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38326673'}, {'...","[{'PubStatus': 'accepted', 'Year': '2024', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{'United States'}, {'United States'}, {'Unite..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,40435158,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '28'}","{'Year': '2025', 'Month': '05', 'Day': '31'}",Electronic-eCollection,1932-6203,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '28', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40435158'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'PURPOSE', 'NlmCategory': 'OBJECTIV...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}]"
1477,40440093,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '29'}","{'Year': '2025', 'Month': '06', 'Day': '01'}",Print,2047-217X,...,"[{'GrantID': '01ZZ2004', 'Acronym': None, 'Age...",['Journal Article'],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40440093'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Uns...",NaN,"[{'United States'}, {'Russia'}, {'United State..."
1478,40440289,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '29'}","{'Year': '2025', 'Month': '06', 'Day': '01'}",Electronic-eCollection,1932-6203,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '29', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40440289'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Cla...",NaN,[{'Canada'}]
1479,40448324,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '31'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print-Electronic,2331-2165,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '30', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '40448324'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Spe...",NaN,"[{'Canada'}, {'Canada'}]"
1480,40452951,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '06', 'Day': '02'}",Electronic-eCollection,1662-5188,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '16', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40452951'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{'United States'}, {'Canada'}, {'Canada'}, {'..."

In [ ]:
import pandas as pd

# Replace 'your_file.csv' with the path to your CSV file
gpt_canada_df_2025 = pd.read_csv(
    './data/Patient_Level_Data_Extracted_2025.csv')

# Display the first few rows
gpt_canada_df_2025

          PMID    PLD                                           Modality
0     37310046  False                                                NaN
1     38019000  False                                                NaN
2     38190258  False                                                NaN
3     38326673   True  "Clinical", "Sensor", "Behavioral", "Demographic"
4     38357879   True     Clinical + Sensorimotor (wearable exoskeleton)
...        ...    ...                                                ...
1425  40435158  False                                                NaN
1426  40440093  False                                                NaN
1427  40440289  False                                                NaN
1428  40448324  False                                                NaN
1429  40314028  False           Other (AI-generated educational content)

[1430 rows x 3 columns]

In [ ]:
merged_df = pd.merge(canada_df, gpt_canada_df_2025, on='PMID', how='left')

filtered_df = merged_df[merged_df["PLD"] == True]
filtered_df

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,ArticleDates,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle,tags,PLD,Modality
4,38326673,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2025', 'Month': '02', 'Day': '03'}","{'Year': '2025', 'Month': '05', 'Day': '27'}",Print-Electronic,1532-7558,...,"[{'Year': '2024', 'Month': '02', 'Day': '07', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38326673'}, {'...","[{'PubStatus': 'accepted', 'Year': '2024', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{'United States'}, {'United States'}, {'Unite...",True,"""Clinical"", ""Sensor"", ""Behavioral"", ""Demographic"""
5,38357879,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '12', 'Day': '10'}","{'Year': '2025', 'Month': '01', 'Day': '03'}",Print-Electronic,1464-5165,...,"[{'Year': '2024', 'Month': '02', 'Day': '15', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38357879'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': 'PURPOSE', 'NlmCategory': 'UNASSIGN...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'...",True,Clinical + Sensorimotor (wearable exoskeleton)
7,38383805,NLM,MEDLINE,NaN,NaN,Manual,"{'Year': '2025', 'Month': '03', 'Day': '13'}","{'Year': '2025', 'Month': '03', 'Day': '13'}",Print-Electronic,2948-2933,...,"[{'Year': '2024', 'Month': '02', 'Day': '21', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38383805'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN,"[{'Canada'}, {'United States'}, {'United State...",True,"""Imaging"", ""Clinical"""
8,38405768,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '05', 'Day': '30'}",Electronic,NaN,...,"[{'Year': '2024', 'Month': '09', 'Day': '17', ...",epublish,"[{'IdType': 'pubmed', 'Value': '38405768'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2024', 'Mont...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Bip...",NaN,"[{'United States'}, {'United States'}, {'Unite...",True,"""Genomic"", ""Clinical (Phenotype)"""
10,38512435,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '09', 'Day': '17'}","{'Year': '2024', 'Month': '09', 'Day': '17'}",Print-Electronic,2662-4737,...,"[{'Year': '2024', 'Month': '03', 'Day': '21', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38512435'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Man...",NaN,"[{'Canada'}, {'Switzerland'}, {'Korea, Republi...",True,"""Clinical"", ""Pet"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,40270591,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '04', 'Day': '25'}",Electronic-eCollection,2296-889X,...,"[{'Year': '2025', 'Month': '04', 'Day': '09', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40270591'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Thi...",NaN,"[{'Canada'}, {'Canada'}, {'Norway'}, {'Germany'}]",True,Metabolomics + Genomics + XAI (Down syndrome b...
1455,40270958,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '04', 'Day': '24'}","{'Year': '2025', 'Month': '04', 'Day': '25'}",Electronic-eCollection,1664-3224,...,"[{'Year': '2025', 'Month': '04', 'Day': '09', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40270958'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{'Brazil'}, {'Brazil'}, {'Brazil'}, {'Brazil'...",True,Transcriptomic + ML (blood interferome signatu...
1473,40407404,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '23'}","{'Year': '2025', 'Month': '05', 'Day': '26'}",Print-Electronic,1526-2359,...,"[{'Year': '2025', 'Month': '05', 'Day': '23', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '40407404'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Int...",NaN,"[{'Turkey'}, {'Turkey'}, {'Turkey'}, {'Canada'}]",True,Survey/Textual (oncology patient views)
1476,40432773,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '05', 'Day': '30'}",Electronic-eCollection,2666-6758,...,"[{'Year': '2025', 'Month': '02', 'Day': '25', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40432773'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Pat...",NaN,"[{'China'}, {'China'}, {'China'}, {'China'}, {...",True,Neurophysiology (thalamic firing + connectivity)
1481,40452951,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '06', 'Day': '02'}",Electronic-eCollection,1662-5188,...,"[{'Year': '2025', 'Month': '05', 'Day': '16', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40452951'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{'United States'}, {'Canada'}, {'Canada'}, {'...",True,Imaging + Clinical + XAI

In [ ]:
# Normalize tag entries (case-insensitive comparison)
def extract_normalized_countries(tag_str):
    if pd.isna(tag_str):
        return set()
    cleaned = tag_str.replace("{", "").replace(
        "}", "").replace("'", "").replace('"', "").replace("[", "").replace(
        "]", "")
    parts = [p.strip().lower()
             for p in cleaned.split(",") if p.strip()]
    return set(parts)


# Apply normalization
filtered_df["UniqueCountries"] = filtered_df["tags"].apply(
    extract_normalized_countries)

# Define conditions
only_canada = filtered_df[filtered_df["UniqueCountries"] == {"canada"}]
collaborative = filtered_df[(filtered_df["UniqueCountries"].apply(lambda x: "canada" in x)) &
                            (filtered_df["UniqueCountries"].apply(lambda x: len(x) > 1))]

# Count results
summary = pd.DataFrame({
    "Category": ["Only Canada", "Collaborative (Canada + Others)"],
    "Count": [len(only_canada), len(collaborative)]
})

summary

/var/folders/gx/4hmfp0zd12bblv6znjwbmv600000gn/T/ipykernel_59767/966200597.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["UniqueCountries"] = filtered_df["tags"].apply(

                          Category  Count
0                      Only Canada    133
1  Collaborative (Canada + Others)    284

In [ ]:
only_canada

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle,tags,PLD,Modality,UniqueCountries
5,38357879,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '12', 'Day': '10'}","{'Year': '2025', 'Month': '01', 'Day': '03'}",Print-Electronic,1464-5165,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38357879'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': 'PURPOSE', 'NlmCategory': 'UNASSIGN...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'...",True,Clinical + Sensorimotor (wearable exoskeleton),{canada}
14,38627132,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '10', 'Day': '19'}","{'Year': '2025', 'Month': '03', 'Day': '20'}",Print-Electronic,1878-4046,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38627132'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"[{'Label': 'RATIONALE', 'NlmCategory': '', 'Te...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'}]",True,"""Imaging"", ""Clinical"", ""Demographic"", CT images",{canada}
15,38647191,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '22'}","{'Year': '2024', 'Month': '07', 'Day': '22'}",Print-Electronic,1522-2594,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38647191'}, {'...","[{'PubStatus': 'revised', 'Year': '2024', 'Mon...",[],"[{'Label': 'PURPOSE', 'NlmCategory': 'OBJECTIV...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'...",True,"""Clinical"", ""Sensor"", ""Demographic"", ""Cognitiv...",{canada}
29,38905892,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '23'}","{'Year': '2024', 'Month': '07', 'Day': '23'}",Print-Electronic,1879-0534,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38905892'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'BAC...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}]",True,Imaging (knee MRI segmentation),{canada}
39,38981593,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '19'}","{'Year': '2024', 'Month': '07', 'Day': '19'}",Electronic,1361-6560,...,epublish,"[{'IdType': 'pubmed', 'Value': '38981593'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Obj...",NaN,"[{'Canada'}, {'Canada'}]",True,Imaging (MRI + CT for GAN-based CT synthesis),{canada}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,40091888,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '03', 'Day': '18'}",Electronic-eCollection,2054-3581,...,epublish,"[{'IdType': 'pubmed', 'Value': '40091888'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'UNASS...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}]",True,Clinical + Imaging + Tabular (kidney transplan...,{canada}
1427,40103927,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '03', 'Day': '20'}",Electronic-eCollection,1663-4365,...,epublish,"[{'IdType': 'pubmed', 'Value': '40103927'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'UNASS...",NaN,"[{'Canada'}, {'Canada'}]",True,"Clinical (multi-modal biomarkers, cognitive)",{canada}
1438,40160858,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '04', 'Day': '02'}",Electronic-eCollection,2001-0370,...,epublish,"[{'IdType': 'pubmed', 'Value': '40160858'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Und...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'...",True,Clinical + Imaging (metabolomics + XAI in hear...,{canada}
1445,40182983,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '04', 'Day': '05'}",Electronic-eCollection,2666-9145,...,epublish,"[{'IdType': 'pubmed', 'Value': '40182983'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': 'OBJECTIVE', 'NlmCategory': 'UNASSI...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'}]",True,Imaging (fundus photos) + Clinical,{canada}
1453,40270567,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '04', 'Day': '25'}",Electronic-eCollection,1662-5161,...,epublish,"[{'IdType': 'pubmed', 'Value': '40270567'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{'Canada'}, {'Canada'}]",True,Sensor + Clinical (BCI-powered power mobility ...,{canada}

In [ ]:
collaborative

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle,tags,PLD,Modality,UniqueCountries
4,38326673,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2025', 'Month': '02', 'Day': '03'}","{'Year': '2025', 'Month': '05', 'Day': '27'}",Print-Electronic,1532-7558,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38326673'}, {'...","[{'PubStatus': 'accepted', 'Year': '2024', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{'United States'}, {'United States'}, {'Unite...",True,"""Clinical"", ""Sensor"", ""Behavioral"", ""Demographic""","{united states, canada}"
7,38383805,NLM,MEDLINE,NaN,NaN,Manual,"{'Year': '2025', 'Month': '03', 'Day': '13'}","{'Year': '2025', 'Month': '03', 'Day': '13'}",Print-Electronic,2948-2933,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38383805'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'The...",NaN,"[{'Canada'}, {'United States'}, {'United State...",True,"""Imaging"", ""Clinical""","{united states, canada}"
8,38405768,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '05', 'Day': '30'}",Electronic,NaN,...,epublish,"[{'IdType': 'pubmed', 'Value': '38405768'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2024', 'Mont...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Bip...",NaN,"[{'United States'}, {'United States'}, {'Unite...",True,"""Genomic"", ""Clinical (Phenotype)""","{united states, greece, republic of, sweden, s..."
10,38512435,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '09', 'Day': '17'}","{'Year': '2024', 'Month': '09', 'Day': '17'}",Print-Electronic,2662-4737,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38512435'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Man...",NaN,"[{'Canada'}, {'Switzerland'}, {'Korea, Republi...",True,"""Clinical"", ""Pet""","{hungary, canada, switzerland, republic of, de..."
18,38789645,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '19'}","{'Year': '2024', 'Month': '07', 'Day': '27'}",Print-Electronic,1546-170X,...,ppublish,"[{'IdType': 'pubmed', 'Value': '38789645'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Pre...",NaN,"[{'Netherlands'}, {'Netherlands'}, {'Switzerla...",True,"""Imaging (Histopathology Whole-Slide Images)"",...","{australia, canada, switzerland, united kingdo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,40270591,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '04', 'Day': '25'}",Electronic-eCollection,2296-889X,...,epublish,"[{'IdType': 'pubmed', 'Value': '40270591'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Thi...",NaN,"[{'Canada'}, {'Canada'}, {'Norway'}, {'Germany'}]",True,Metabolomics + Genomics + XAI (Down syndrome b...,"{norway, canada, germany}"
1455,40270958,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '04', 'Day': '24'}","{'Year': '2025', 'Month': '04', 'Day': '25'}",Electronic-eCollection,1664-3224,...,epublish,"[{'IdType': 'pubmed', 'Value': '40270958'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{'Brazil'}, {'Brazil'}, {'Brazil'}, {'Brazil'...",True,Transcriptomic + ML (blood interferome signatu...,"{united states, brazil, canada}"
1473,40407404,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '23'}","{'Year': '2025', 'Month': '05', 'Day': '26'}",Print-Electronic,1526-2359,...,ppublish,"[{'IdType': 'pubmed', 'Value': '40407404'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Int...",NaN,"[{'Turkey'}, {'Turkey'}, {'Turkey'}, {'Canada'}]",True,Survey/Textual (oncology patient views),"{turkey, canada}"
1476,40432773,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '05', 'Day': '30'}",Electronic-eCollection,2666-6758,...,epublish,"[{'IdType': 'pubmed', 'Value': '40432773'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Pat...",NaN,"[{'China'}, {'China'}, {'China'}, {'China'}, {...",True,Neurophysiology (thalamic firing + connectivity),"{china, belgium, canada}"
1481,40452951,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '06', 'Day': '02'}",Electronic-eCollection,1662-5188,...,epublish,"[{'IdType': 'pubmed', 'Value': '40452951'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{'United States'}, {'Canada'}, {'Canada'}, {'...",True,Imaging + Clinical + XAI,"{united states, canada, france}"

In [ ]:
import pandas as pd

# Replace 'your_file.csv' with the path to your CSV file
data_canada_map_modalities = pd.read_csv(
    './data-canada-map-modalities.csv')

# Display the first few rows
data_canada_map_modalities

          pid                                combined_modalities
0    28987903  {"[\"Cardiac Images (MR sequences)\"]","[\"MR\...
1    29065782      {"[\"Clinical\"]","Medicine\"]","[\"Surgery"}
2    29071211  {"[\"Myelin","[\"Myelin Maps","T1-weighted MRI...
3    29084099  {"Executive Function\"]","[\"Robotics","[\"Sen...
4    29169029  {CT,"CT images","[\"Electron Microscopy","MRI\...
..        ...                                                ...
972  38962394  {"[{\"Modality_Name\": \"Speech\"}, {\"Modalit...
973  38977181  {"Medical\"]","[\"Sociodemographic","[\"Text\"]"}
974  38980984  {"accelerometry\"]","Accelerometry\"]","[\"ele...
975  38987512  {"[\"3D spinal ultrasonographs\"]","[\"Ultraso...
976  39001096  {"[\"Heart Rate Variability\"]","[\"RR interva...

[977 rows x 2 columns]

In [ ]:
canada_df = canada_df[~canada_df['PublicationTypeList'].str.contains(
    'Editorial', na=False)]

canada_df

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateCompleted,DateRevised,ArticlePubModel,JournalISSN,...,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,Abstract,VernacularTitle,tags
0,37310046,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '10', 'Day': '25'}","{'Year': '2024', 'Month': '10', 'Day': '25'}",Print-Electronic,1521-4095,...,"[{'GrantID': 'K99 AG065495', 'Acronym': 'AG', ...",['Journal Article'],"[{'Year': '2023', 'Month': '07', 'Day': '19', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '37310046'}, {'...","[{'PubStatus': 'revised', 'Year': '2023', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Sof...",NaN,"[{'United States'}, {'United States'}, {'Unite..."
1,38019000,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '01', 'Day': '09'}","{'Year': '2025', 'Month': '01', 'Day': '09'}",Print-Electronic,1746-1553,...,"[{'GrantID': 'RGPIN-2018-04151', 'Acronym': No...",['Journal Article'],"[{'Year': '2023', 'Month': '11', 'Day': '29', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38019000'}, {'...","[{'PubStatus': 'received', 'Year': '2022', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'}]"
2,38190258,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2025', 'Month': '01', 'Day': '15'}","{'Year': '2025', 'Month': '05', 'Day': '13'}",Print-Electronic,1949-3614,...,[],"['Journal Article', 'Randomized Controlled Tri...","[{'Year': '2024', 'Month': '01', 'Day': '08', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38190258'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Chi...",NaN,[{'Canada'}]
4,38326673,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2025', 'Month': '02', 'Day': '03'}","{'Year': '2025', 'Month': '05', 'Day': '27'}",Print-Electronic,1532-7558,...,"[{'GrantID': 'RG 5144A6/1', 'Acronym': None, '...","['Journal Article', 'Randomized Controlled Tri...","[{'Year': '2024', 'Month': '02', 'Day': '07', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38326673'}, {'...","[{'PubStatus': 'accepted', 'Year': '2024', 'Mo...",[],"[{'Label': 'BACKGROUND', 'NlmCategory': 'BACKG...",NaN,"[{'United States'}, {'United States'}, {'Unite..."
5,38357879,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '12', 'Day': '10'}","{'Year': '2025', 'Month': '01', 'Day': '03'}",Print-Electronic,1464-5165,...,[],['Journal Article'],"[{'Year': '2024', 'Month': '02', 'Day': '15', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '38357879'}, {'...","[{'PubStatus': 'medline', 'Year': '2024', 'Mon...",[],"[{'Label': 'PURPOSE', 'NlmCategory': 'UNASSIGN...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}, {'Canada'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,40435158,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '28'}","{'Year': '2025', 'Month': '05', 'Day': '31'}",Electronic-eCollection,1932-6203,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '28', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40435158'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'PURPOSE', 'NlmCategory': 'OBJECTIV...",NaN,"[{'Canada'}, {'Canada'}, {'Canada'}]"
1477,40440093,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '29'}","{'Year': '2025', 'Month': '06', 'Day': '01'}",Print,2047-217X,...,"[{'GrantID': '01ZZ2004', 'Acronym': None, 'Age...",['Journal Article'],[],ppublish,"[{'IdType': 'pubmed', 'Value': '40440093'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': 'Uns...",NaN,"[{'United States'}, {'Russia'}, {'United State..."
1478,40440289,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '29'}","{'Year': '2025', 'Month': '06', 'Day': '01'}",Electronic-eCollection,1932-6203,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '29', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40440289'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Cla...",NaN,[{'Canada'}]
1479,40448324,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2025', 'Month': '05', 'Day': '31'}","{'Year': '2025', 'Month': '06', 'Day': '02'}",Print-Electronic,2331-2165,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '30', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '40448324'}, {'...","[{'PubStatus': 'medline', 'Year': '2025', 'Mon...",[],"[{'Label': '', 'NlmCategory': '', 'Text': ""Spe...",NaN,"[{'Canada'}, {'Canada'}]"
1480,40452951,NLM,PubMed-not-MEDLINE,NaN,NaN,NaN,NaN,"{'Year': '2025', 'Month': '06', 'Day': '02'}",Electronic-eCollection,1662-5188,...,[],['Journal Article'],"[{'Year': '2025', 'Month': '05', 'Day': '16', ...",epublish,"[{'IdType': 'pubmed', 'Value': '40452951'}, {'...","[{'PubStatus': 'received', 'Year': '2025', 'Mo...",[],"[{'Label': 'INTRODUCTION', 'NlmCategory': 'UNA...",NaN,"[{'United States'}, {'Canada'}, {'Canada'}, {'..."

In [ ]:
import pandas as pd
import ast

# Read the CSV file
# file_path = './data/countries_affiliation_df_canada.csv'  # Replace with your actual file path
# canada_df = pd.read_csv(file_path)

# Convert JSON-like strings to proper Python objects
columns_to_convert = ['DateRevised', 'Abstract', 'Authors',
                      'ArticleIds', 'History', 'tags', 'ArticleDates']

for column in columns_to_convert:
    canada_df[column] = canada_df[column].apply(
        lambda x: ast.literal_eval(x) if pd.notna(x) else x)

# Display the DataFrame
print(canada_df.dtypes)
print(canada_df.head())

PMID                               int64
MedlineCitationOwner              object
MedlineCitationStatus             object
MedlineCitationVersionID         float64
MedlineCitationVersionDate        object
MedlineCitationIndexingMethod     object
DateRevised                       object
ArticlePubModel                   object
JournalISSN                       object
JournalTitle                      object
JournalISOAbbreviation            object
ArticleTitle                      object
Language                          object
StartPage                         object
EndPage                           object
MedlinePgn                        object
Abstract                          object
Authors                           object
DataBankList                      object
GrantList                         object
PublicationTypeList               object
ArticleDates                      object
PublicationStatus                 object
ArticleIds                        object
History                           object
Objects                           object
DateCompleted                     object
VernacularTitle                   object
tags                              object
dtype: object
       PMID MedlineCitationOwner MedlineCitationStatus  \
0  28350526                  NLM               MEDLINE
1  28444633                  NLM               MEDLINE
2  28550657                  NLM               MEDLINE
3  28589480                  NLM               MEDLINE
4  28596271                  NLM               MEDLINE

   MedlineCitationVersionID MedlineCitationVersionDate  \
0                       NaN                        NaN
1                       NaN                        NaN
2                       NaN                        NaN
3                       NaN                        NaN
4                       NaN                        NaN

  MedlineCitationIndexingMethod                                   DateRevised  \
0                           NaN  {'Year': '2018', 'Month': '10', 'Day': '29'}
1                       Curated  {'Year': '2019', 'Month': '12', 'Day': '10'}
2                       Curated  {'Year': '2019', 'Month': '02', 'Day': '15'}
3                       Curated  {'Year': '2019', 'Month': '12', 'Day': '10'}
4                           NaN  {'Year': '2019', 'Month': '10', 'Day': '25'}

    ArticlePubModel JournalISSN  \
0  Print-Electronic   1748-3115
1             Print   1531-5320
2             Print   1554-3528
3             Print   1573-3602
4  Print-Electronic   1522-1601

                                        JournalTitle  ...  \
0  Disability and rehabilitation. Assistive techn...  ...
1                      Psychonomic bulletin & review  ...
2                          Behavior research methods  ...
3                        Journal of gambling studies  ...
4  Journal of applied physiology (Bethesda, Md. :...  ...

                                           GrantList  \
0                                                 []
1  [{'GrantID': 'Discovery Grant (312409-05)', 'A...
2                                                 []
3  [{'GrantID': '3441', 'Acronym': None, 'Agency'...
4                                                 []

                                 PublicationTypeList  \
0  ['Journal Article', 'Observational Study', "Re...
1  ['Journal Article', "Research Support, Non-U.S...
2                                ['Journal Article']
3                                ['Journal Article']
4  ['Clinical Trial', 'Journal Article', "Researc...

                                        ArticleDates PublicationStatus  \
0  [{'Year': '2017', 'Month': '03', 'Day': '28', ...          ppublish
1                                                 []          ppublish
2                                                 []          ppublish
3                                                 []          ppublish
4  [{'Year': '2017', 'Month': '06', 'Day': '08', ...          ppublish

                                          ArticleIds  \
0  [{'IdType': 'pubmed', 'Value': '28350526'}, {'...
1  [{'IdType': 'pubmed', 'Value': '28444633'}, {'...
2  [{'IdType': 'pubmed', 'Value': '28550657'}, {'...
3  [{'IdType': 'pubmed', 'Value': '28589480'}, {'...
4  [{'IdType': 'pubmed', 'Value': '28596271'}, {'...

                                             History Objects  \
0  [{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...      []
1  [{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...      []
2  [{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...      []
3  [{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...      []
4  [{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...      []

                                  DateCompleted VernacularTitle  \
0  {'Year': '2018', 'Month': '10', 'Day': '29'}             NaN
1  {'Year': '2019', 'Month': '02', 'Day': '07'}             NaN
2  {'Year': '2019', 'Month': '02', 'Day': '11'}             NaN
3  {'Year': '2018', 'Month': '07', 'Day': '16'}             NaN
4  {'Year': '2019', 'Month': '10', 'Day': '25'}             NaN

                                       tags
0                      [{Canada}, {Canada}]
1                      [{Canada}, {Canada}]
2                                [{Canada}]
3  [{Canada}, {Canada}, {Canada}, {Canada}]
4  [{Canada}, {Brazil}, {Canada}, {Canada}]

[5 rows x 29 columns]

In [ ]:
type(canada_df.iloc[0]["PMID"])

numpy.int64

In [ ]:
from langchain_community.llms import Ollama
import json
import os
import datetime

llm = Ollama(model="llama3")

# Define the prompt text
prompt_text = """
Consider the following paper details: 
-  Title: 
   {Title}

- Abstract
  {Abstract}

- Affiliations: 
  {Affiliations}

GIVE ME A JSON object should include:
* Affiliation_countries_tags
* Centralized_or_Decentralized
* Is_Real_World_Data_Set
* Size_of_Data_Set
* AI_or_ML_Tools_In_The_Paper
* Governance_Mode
* Patient_Level_Data
* Type_of_Patient_Level_Data
* Clinical_Data_Type
* Is_Using_Survey_Data
* Is_Using_Questionnaire
* Federated_Learning_Techniques
* Privacy_Preserving_Techniques
* Data_Collection_Method
* Is_Using_Large_Language_Model
* Is_Using_Multimodal_Model
* Is_Using_Shared_Dataset
* Modalities

In your response, please do not use abbreviations for any fields. 
Ensure to return only the JSON result without any additional text or commentary.
JSON SHOULD ONLY CONTAIN THE ABOVE FIELD. 
Use "NIL" for any null or unspecified values.
"""

# Define the path for the results file
results_file_path = 'canada_review_results_2025.json'

# Load existing results if the file exists
if os.path.exists(results_file_path):
    with open(results_file_path, 'r') as file:
        existing_results = json.load(file)
else:
    existing_results = {}


# Initialize a list to store the results
canada_review = []

# Define the batch size for saving results
batch_size = 10

# Ensure we only process the first 100 rows
num_rows_to_process = min(len(canada_df), 1500)

# Iterate over the rows to process
for index in range(num_rows_to_process):
    row = canada_df.iloc[index]
    PMID = str(row["PMID"])
    
    # Skip processing if PMID already exists in the results
    if PMID in existing_results:
        print(f"Skipping PMID {PMID} as it already exists in the results.")
        continue

    Title = row["ArticleTitle"]
    Abstract = row["Abstract"]
    Affiliations = row["Authors"]
    
    # Format the prompt with the current details
    prompt_with_item = prompt_text.format(Affiliations=Affiliations, Abstract=Abstract, Title=Title)
    
    # Invoke the LLM
    res = llm.invoke(prompt_with_item, max_tokens=1)
    
    # Append the result to the list
    canada_review.append({"PMID": PMID, "llm_res": res})

    # Add the new result to the existing results dictionary
    existing_results[PMID] = res

    # Write to file after every batch_size rows
    if (index + 1) % batch_size == 0:
        with open(results_file_path, 'w') as file:
            json.dump(existing_results, file, indent=4)
        print(f"{datetime.datetime.now().time().strftime("%Y-%m-%d %H:%M:%S")} Saved results after processing {index + 1} rows.")

# Save any remaining results after the loop
if (num_rows_to_process % batch_size) != 0:
    with open(results_file_path, 'w') as file:
        json.dump(existing_results, file, indent=4)
    print(f"{datetime.datetime.now().time().strftime("%Y-%m-%d %H:%M:%S")} Saved final results after processing {num_rows_to_process} rows.")

# Print the results
for i, row in enumerate(canada_review):
    print(f"Row {i+1}: {row}")

Skipping PMID 37310046 as it already exists in the results.
Skipping PMID 38019000 as it already exists in the results.
Skipping PMID 38190258 as it already exists in the results.
Skipping PMID 38326673 as it already exists in the results.
Skipping PMID 38357879 as it already exists in the results.
Skipping PMID 38383805 as it already exists in the results.
Skipping PMID 38405768 as it already exists in the results.
Skipping PMID 38409223 as it already exists in the results.
Skipping PMID 38512435 as it already exists in the results.
Skipping PMID 38520646 as it already exists in the results.
Skipping PMID 38575195 as it already exists in the results.
Skipping PMID 38590142 as it already exists in the results.
Skipping PMID 38627132 as it already exists in the results.
Skipping PMID 38647191 as it already exists in the results.
Skipping PMID 38696699 as it already exists in the results.
Skipping PMID 38717330 as it already exists in the results.
Skipping PMID 38789645 as it already exists in the results.
Skipping PMID 38808752 as it already exists in the results.
Skipping PMID 38842169 as it already exists in the results.
Skipping PMID 38857570 as it already exists in the results.
1900-01-01 15:22:00 Saved results after processing 30 rows.
1900-01-01 15:27:13 Saved results after processing 40 rows.
1900-01-01 15:31:56 Saved results after processing 50 rows.
1900-01-01 15:36:54 Saved results after processing 60 rows.
1900-01-01 15:41:19 Saved results after processing 70 rows.
1900-01-01 15:45:52 Saved results after processing 80 rows.
1900-01-01 15:50:17 Saved results after processing 90 rows.
1900-01-01 15:55:13 Saved results after processing 100 rows.
1900-01-01 15:59:40 Saved results after processing 110 rows.
1900-01-01 16:05:28 Saved results after processing 120 rows.
1900-01-01 16:09:49 Saved results after processing 130 rows.
1900-01-01 16:14:32 Saved results after processing 140 rows.
1900-01-01 16:19:07 Saved results after processing 150 rows.
1900-01-01 16:24:44 Saved results after processing 160 rows.
1900-01-01 16:30:12 Saved results after processing 170 rows.
1900-01-01 16:34:56 Saved results after processing 180 rows.
1900-01-01 16:39:57 Saved results after processing 190 rows.
1900-01-01 16:45:33 Saved results after processing 200 rows.
1900-01-01 16:50:22 Saved results after processing 210 rows.
1900-01-01 16:56:28 Saved results after processing 220 rows.
1900-01-01 18:41:51 Saved results after processing 230 rows.
1900-01-01 18:51:12 Saved results after processing 240 rows.
1900-01-01 18:59:19 Saved results after processing 250 rows.
1900-01-01 19:09:58 Saved results after processing 260 rows.
1900-01-01 19:21:20 Saved results after processing 270 rows.
1900-01-01 19:32:30 Saved results after processing 280 rows.
1900-01-01 19:43:34 Saved results after processing 290 rows.
1900-01-01 19:48:40 Saved results after processing 300 rows.
1900-01-01 19:54:02 Saved results after processing 310 rows.
1900-01-01 19:59:04 Saved results after processing 320 rows.
1900-01-01 20:03:38 Saved results after processing 330 rows.
1900-01-01 20:08:03 Saved results after processing 340 rows.
1900-01-01 20:12:58 Saved results after processing 350 rows.
1900-01-01 20:17:55 Saved results after processing 360 rows.
1900-01-01 20:23:11 Saved results after processing 370 rows.
1900-01-01 20:27:13 Saved results after processing 380 rows.
1900-01-01 20:32:07 Saved results after processing 390 rows.
1900-01-01 20:37:05 Saved results after processing 400 rows.
1900-01-01 20:41:54 Saved results after processing 410 rows.
1900-01-01 20:46:52 Saved results after processing 420 rows.
1900-01-01 20:51:49 Saved results after processing 430 rows.
1900-01-01 20:56:57 Saved results after processing 440 rows.
1900-01-01 21:01:21 Saved results after processing 450 rows.
1900-01-01 21:05:42 Saved results after processing 460 rows.
1900-01-01 21:10:04 Saved results after processing 470 rows.
1900-01-01 21:14:33 Saved results after processing 480 rows.
1900-01-01 21:18:56 Saved results after processing 490 rows.
1900-01-01 21:23:17 Saved results after processing 500 rows.
1900-01-01 21:28:17 Saved results after processing 510 rows.
1900-01-01 21:33:02 Saved results after processing 520 rows.
1900-01-01 21:37:25 Saved results after processing 530 rows.
1900-01-01 21:42:24 Saved results after processing 540 rows.
1900-01-01 21:47:06 Saved results after processing 550 rows.
1900-01-01 21:51:56 Saved results after processing 560 rows.
1900-01-01 21:56:27 Saved results after processing 570 rows.
1900-01-01 22:01:39 Saved results after processing 580 rows.
1900-01-01 22:06:25 Saved results after processing 590 rows.
1900-01-01 22:11:12 Saved results after processing 600 rows.
1900-01-01 22:16:16 Saved results after processing 610 rows.
1900-01-01 22:21:16 Saved results after processing 620 rows.
1900-01-01 22:26:00 Saved results after processing 630 rows.
1900-01-01 22:30:13 Saved results after processing 640 rows.
1900-01-01 22:35:12 Saved results after processing 650 rows.
1900-01-01 22:41:07 Saved results after processing 660 rows.
1900-01-01 22:47:08 Saved results after processing 670 rows.
1900-01-01 22:52:33 Saved results after processing 680 rows.
1900-01-01 22:58:14 Saved results after processing 690 rows.
1900-01-01 23:03:47 Saved results after processing 700 rows.
1900-01-01 23:08:29 Saved results after processing 710 rows.
1900-01-01 23:13:00 Saved results after processing 720 rows.
1900-01-01 23:17:46 Saved results after processing 730 rows.
1900-01-01 23:23:14 Saved results after processing 740 rows.
1900-01-01 23:29:25 Saved results after processing 750 rows.
1900-01-01 23:35:03 Saved results after processing 760 rows.
1900-01-01 23:39:36 Saved results after processing 770 rows.
1900-01-01 23:44:05 Saved results after processing 780 rows.
1900-01-01 23:48:35 Saved results after processing 790 rows.
1900-01-01 23:53:47 Saved results after processing 800 rows.
1900-01-01 23:58:45 Saved results after processing 810 rows.
1900-01-01 00:03:32 Saved results after processing 820 rows.
1900-01-01 00:08:10 Saved results after processing 830 rows.
1900-01-01 00:12:46 Saved results after processing 840 rows.
1900-01-01 00:17:26 Saved results after processing 850 rows.
1900-01-01 00:22:10 Saved results after processing 860 rows.
1900-01-01 00:27:11 Saved results after processing 870 rows.
1900-01-01 00:32:02 Saved results after processing 880 rows.
1900-01-01 00:36:38 Saved results after processing 890 rows.
1900-01-01 00:41:27 Saved results after processing 900 rows.
1900-01-01 00:46:27 Saved results after processing 910 rows.
1900-01-01 00:50:48 Saved results after processing 920 rows.
1900-01-01 00:55:14 Saved results after processing 930 rows.
1900-01-01 01:00:08 Saved results after processing 940 rows.
1900-01-01 01:04:44 Saved results after processing 950 rows.
1900-01-01 01:09:59 Saved results after processing 960 rows.
1900-01-01 01:14:34 Saved results after processing 970 rows.
1900-01-01 01:19:53 Saved results after processing 980 rows.
1900-01-01 01:24:21 Saved results after processing 990 rows.
1900-01-01 01:28:57 Saved results after processing 1000 rows.
1900-01-01 01:33:48 Saved results after processing 1010 rows.
1900-01-01 01:38:35 Saved results after processing 1020 rows.
1900-01-01 01:43:01 Saved results after processing 1030 rows.
1900-01-01 01:47:51 Saved results after processing 1040 rows.
1900-01-01 01:52:44 Saved results after processing 1050 rows.
1900-01-01 01:57:19 Saved results after processing 1060 rows.
1900-01-01 02:02:02 Saved results after processing 1070 rows.
1900-01-01 02:07:06 Saved results after processing 1080 rows.
1900-01-01 02:11:51 Saved results after processing 1090 rows.
1900-01-01 02:16:58 Saved results after processing 1100 rows.
1900-01-01 02:21:44 Saved results after processing 1110 rows.
1900-01-01 02:26:30 Saved results after processing 1120 rows.
1900-01-01 02:31:18 Saved results after processing 1130 rows.
1900-01-01 02:35:47 Saved results after processing 1140 rows.
1900-01-01 02:40:18 Saved results after processing 1150 rows.
1900-01-01 02:45:29 Saved results after processing 1160 rows.
1900-01-01 02:50:28 Saved results after processing 1170 rows.
1900-01-01 02:55:31 Saved results after processing 1180 rows.
1900-01-01 03:00:03 Saved results after processing 1190 rows.
1900-01-01 03:04:25 Saved results after processing 1200 rows.
1900-01-01 03:09:51 Saved results after processing 1210 rows.
1900-01-01 03:14:48 Saved results after processing 1220 rows.
1900-01-01 03:19:35 Saved results after processing 1230 rows.
1900-01-01 03:23:59 Saved results after processing 1240 rows.
1900-01-01 03:28:50 Saved results after processing 1250 rows.
1900-01-01 03:33:42 Saved results after processing 1260 rows.
1900-01-01 03:38:42 Saved results after processing 1270 rows.
1900-01-01 03:43:22 Saved results after processing 1280 rows.
1900-01-01 03:47:54 Saved results after processing 1290 rows.
1900-01-01 03:52:37 Saved results after processing 1300 rows.
1900-01-01 03:56:49 Saved results after processing 1310 rows.
1900-01-01 04:01:38 Saved results after processing 1320 rows.
1900-01-01 04:06:17 Saved results after processing 1330 rows.
1900-01-01 04:10:51 Saved results after processing 1340 rows.
1900-01-01 04:15:17 Saved results after processing 1350 rows.
1900-01-01 04:20:04 Saved results after processing 1360 rows.
1900-01-01 04:25:04 Saved results after processing 1370 rows.
1900-01-01 04:29:24 Saved results after processing 1380 rows.
1900-01-01 04:34:21 Saved results after processing 1390 rows.
1900-01-01 04:39:11 Saved results after processing 1400 rows.
1900-01-01 04:44:15 Saved results after processing 1410 rows.
1900-01-01 04:48:20 Saved results after processing 1420 rows.
1900-01-01 04:52:35 Saved results after processing 1430 rows.
1900-01-01 04:53:06 Saved final results after processing 1431 rows.
Row 1: {'PMID': '38858261', 'llm_res': '{\n    "Affiliation_countries": ["USA", "Saudi Arabia", "Canada"],\n    "Centralized_or_Decentralized": NIL,\n    "Is_Real_World_Data_Set": true,\n    "Size_of_Data_Set": NIL,\n    "AI_or_ML_Tools_In_The_Paper": NIL,\n    "Governance_Mode": NIL,\n    "Patient_Level_Data": true,\n    "Type_of_Patient_Level_Data": NIL,\n    "Clinical_Data_Type": NIL,\n    "Is_Using_Survey_Data": NIL,\n    "Is_Using_Questionnaire": NIL,\n    "Federated_Learning_Techniques": NIL,\n    "Privacy_Preserving_Techniques": NIL,\n    "Data_Collection_Method": NIL,\n    "Is_Using_Large_Language_Model": NIL,\n    "Is_Using_Multimodal_Model": NIL,\n    "Is_Using_Shared_Dataset": NIL,\n    "Modalities": ["Medical Imaging"]\n}'}
Row 2: {'PMID': '38871841', 'llm_res': '{\n  "Affiliation_countries": ["Finland", "Canada", "Colombia", "Italy"],\n  "Centralized_or_Decentralized": "Centralized",\n  "Is_Real_World_Data_Set": "NIL",\n  "Size_of_Data_Set": "NIL",\n  "AI_or_ML_Tools_In_The_Paper": ["ChatGPT"],\n  "Governance_Mode": "NIL",\n  "Patient_Level_Data": true,\n  "Type_of_Patient_Level_Data": "nil",\n  "Clinical_Data_Type": "nil",\n  "Is_Using_Survey_Data": false,\n  "Is_Using_Questionnaire": "nil",\n  "Federated_Learning_Techniques": "NIL",\n  "Privacy_Preserving_Techniques": "NIL",\n  "Data_Collection_Method": "NIL",\n  "Is_Using_Large_Language_Model": true,\n  "Is_Using_Multimodal_Model": false,\n  "Is_Using_Shared_Dataset": "nil",\n  "Modalities": ["text"]\n}'}
Row 3: {'PMID': '38873702', 'llm_res': '{\n  "Affiliation_countries": ["China", "Canada"],\n  "Centralized_or_Decentralized": "Decentralized",\n  "Is_Real_World_Data_Set": true,\n  "Size_of_Data_Set": NIL,\n  "AI_or_ML_Tools_In_The_Paper": NIL,\n  "Governance_Mode": NIL,\n  "Patient_Level_Data": true,\n  "Type_of_Patient_Level_Data": ["Neonatal anthropometric measurements", "Biochemical markers"],\n  "Clinical_Data_Type": ["Skeletal health"],\n  "Is_Using_Survey_Data": false,\n  "Is_Using_Questionnaire": false,\n  "Federated_Learning_Techniques": NIL,\n  "Privacy_Preserving_Techniques": NIL,\n  "Data_Collection_Method": ["In vitro", "In vivo"],\n  "Is_Using_Large_Language_Model": false,\n  "Is_Using_Multimodal_Model": true,\n  "Is_Using_Shared_Dataset": false,\n  "Modalities": ["Ultrasonic"]\n}'}
Row 4: {'PMID': '38878395', 'llm_res': '{\n"Affiliation_countries_tags": ["Canada"],\n"Centralized_or_Decentralized": "Decentralized",\n"Is_Real_World_Data_Set": true,\n"Size_of_Data_Set": NIL,\n"AI_or_ML_Tools_In_The_Paper": NIL,\n"Governance_Mode": NIL,\n"Patient_Level_Data": false,\n"Type_of_Patient_Level_Data": NIL,\n"Clinical_Data_Type": NIL,\n"Is_Using_Survey_Data": false,\n"Is_Using_Questionnaire": false,\n"Federated_Learning_Techniques": NIL,\n"Privacy_Preserving_Techniques": NIL,\n"Data_Collection_Method": "NIL",\n"Is_Using_Large_Language_Model": false,\n"Is_Using_Multimodal_Model": true,\n"Is_Using_Shared_Dataset": true,\n"Modalities": ["Diffuse Optical Imaging"]\n}'}
Row 5: {'PMID': '38880121', 'llm_res': 'Here is the JSON object:\n\n{\n"Affiliation_countries_tags": ["Canada"],\n"Centralized_or_Decentralized": "Centralized",\n"Is_Real_World_Data_Set": "False",\n"Size_of_Data_Set": "NIL",\n"AI_or_ML_Tools_In_The_Paper": [],\n"Governance_Mode": "NIL",\n"Patient_Level_Data": "False",\n"Type_of_Patient_Level_Data": "NIL",\n"Clinical_Data_Type": "NIL",\n"Is_Using_Survey_Data": "True",\n"Is_Using_Questionnaire": "True",\n"Federated_Learning_Techniques": "NIL",\n"Privacy_Preserving_Techniques": "NIL",\n"Data_Collection_Method": "Online Survey",\n"Is_Using_Large_Language_Model": "False",\n"Is_Using_Multimodal_Model": "False",\n"Is_Using_Shared_Dataset": "False",\n"Modalities": ["Video"]\n}'}
Row 6: {'PMID': '38881045', 'llm_res': '{\n  "Affiliation_countries_tags": ["US", "CA"],\n  "Centralized_or_Decentralized": "Decentralized",\n  "Is_Real_World_Data_Set": true,\n  "Size_of_Data_Set": NIL,\n  "AI_or_ML_Tools_In_The_Paper": false,\n  "Governance_Mode": "NIL",\n  "Patient_Level_Data": true,\n  "Type_of_Patient_Level_Data": "NIL",\n  "Clinical_Data_Type": "NIL",\n  "Is_Using_Survey_Data": false,\n  "Is_Using_Questionnaire": NIL,\n  "Federated_Learning_Techniques": false,\n  "Privacy_Preserving_Techniques": true,\n  "Data_Collection_Method": "NIL",\n  "Is_Using_Large_Language_Model": false,\n  "Is_Using_Multimodal_Model": false,\n  "Is_Using_Shared_Dataset": NIL,\n  "Modalities": ["Text", "NIL"]\n}'}
Row 7: {'PMID': '38901097', 'llm_res': '{\n"Affiliation_countries_tags": ["Canada", "UK"],\n"Centralized_or_Decentralized": "Decentralized",\n"Is_Real_World_Data_Set": "NIL",\n"Size_of_Data_Set": "NIL",\n"AI_or_ML_Tools_In_The_Paper": NIL,\n"Governance_Mode": NIL,\n"Patient_Level_Data": NIL,\n"Type_of_Patient_Level_Data": NIL,\n"Clinical_Data_Type": NIL,\n"Is_Using_Survey_Data": "NIL",\n"Is_Using_Questionnaire": "NIL",\n"Federated_Learning_Techniques": NIL,\n"Privacy_Preserving_Techniques": NIL,\n"Data_Collection_Method": NIL,\n"Is_Using_Large_Language_Model": "NIL",\n"Is_Using_Multimodal_Model": "NIL",\n"Is_Using_Shared_Dataset": "NIL",\n"Modalities": NIL\n}'}
Row 8: {'PMID': '38905892', 'llm_res': '{\n"Affiliation_countries_tags": ["Canada", "Alberta"],\n"Centralized_or_Decentralized": "Decentralized",\n"Is_Real_World_Data_Set": true,\n"Size_of_Data_Set": NIL,\n"AI_or_ML_Tools_In_The_Paper": ["3D U-Net"],\n"Governance_Mode": NIL,\n"Patient_Level_Data": true,\n"type_of_patient_level_data": NIL,\n"Clinical_Data_Type": "MRI",\n"Is_Using_Survey_Data": false,\n"Is_Using_Questionnaire": false,\n"Federated_Learning_Techniques": NIL,\n"Privacy_Preserving_Techniques": NIL,\n"Data_Collection_Method": "Image intensity normalization, data augmentation",\n"Is_Using_Large_Language_Model": false,\n"Is_Using_Multimodal_Model": true,\n"Is_Using_Shared_Dataset": false,\n"Modalities": ["MRI"]\n}'}
Row 9: {'PMID': '38908306', 'llm_res': '{\n"Affiliation_countries_tags": ["China", "Canada"],\n"Centralized_or_Decentralized": "Centralized",\n"Is_Real_World_Data_Set": true,\n"Size_of_Data_Set": NIL,\n"AI_or_ML_Tools_In_The_Paper": ["Multimodal model", "GPT-4"],\n"Governance_Mode": NIL,\n"Patient_Level_Data": false,\n"Type_of_Patient_Level_Data": NIL,\n"Clinical_Data_Type": "Neurological disorder",\n"Is_Using_Survey_Data": false,\n"Is_Using_Questionnaire": false,\n"Federated_Learning_Techniques": NIL,\n"Privacy_Preserving_Techniques": NIL,\n"data_collection_method": NIL,\n"Is_Using_Large_Language_Model": true,\n"Is_Using_Multimodal_Model": true,\n"Is_Using_Shared_Dataset": false,\n"Modalities": ["Multimodal"]'}
Row 10: {'PMID': '38922721', 'llm_res': '{\n"Affiliation_countries_tags": ["USA", "Canada"],\n"Centralized_or_Decentralized": "Decentralized",\n"Is_Real_World_Data_Set": true,\n"Size_of_Data_Set": "Forty CT scans",\n"AI_or_ML_Tools_In_The_Paper": "Deep learning (DL)",\n"Governance_Mode": NIL,\n"Patient_Level_Data": false,\n"Type_of_Patient_Level_Data": NIL,\n"Clinical_Data_Type": NIL,\n"Is_Using_Survey_Data": false,\n"Is_Using_Questionnaire": false,\n"Federated_Learning_Techniques": NIL,\n"Privacy_Preserving_Techniques": NIL,\n"Data_Collection_Method": "Retrospective cohort study",\n"Is_Using_Large_Language_Model": false,\n"Is_Using_Multimodal_Model": false,\n"Is_Using_Shared_Dataset": false,\n"Modalities": ["CT scans"]\n}'}
Row 11: {'PMID': '38924864', 'llm_res': '{\n    "Affiliation_countries": ["Iran", "Canada"],\n    "Centralized_or_Decentralized": "Decentralized",\n    "Is_Real_World_Data_Set": true,\n    "Size_of_Data_Set": NIL,\n    "AI_or_ML_Tools_In_The_Paper": ["ConvLSTM"],\n    "Governance_Mode": NIL,\n    "Patient_Level_Data": false,\n    "Type_of_Patient_Level_Data": NIL,\n    "Clinical_Data_Type": NIL,\n    "Is_Using_Survey_Data": false,\n    "Is_Using_Questionnaire": false,\n    "Federated_Learning_Techniques": false,\n    "Privacy_Preserving_Techniques": NIL,\n    "Data_Collection_Method": NIL,\n    "Is_Using_Large_Language_Model": false,\n    "Is_Using_Multimodal_Model": true,\n    "Is_Using_Shared_Dataset": false,\n    "Modalities": ["Lung sound recordings"]\n}'}
Row 12: {'PMID': '38936223', 'llm_res': '{\n"Affiliation_countries_tags": ["Canada"],\n"Centralized_or_Decentralized": "Decentralized",\n"Is_Real_World_Data_Set": true,\n"Size_of_Data_Set": NIL,\n"AI_or_ML_Tools_In_The_Paper": ["Deep learning"],\n"Governance_Mode": NIL,\n"Patient_Level_Data": false,\n"Type_of_Patient_Level_Data": NIL,\n"Clinical_Data_Type": "Medical images",\n"Is_Using_Survey_Data": false,\n"Is_Using_Questionnaire": false,\n"Federated_Learning_Techniques": NIL,\n"Privacy_Preserving_Techniques": NIL,\n"Data_Collection_Method": ["Synthesis"],\n"Is_Using_Large_Language_Model": false,\n"Is_Using_Multimodal_Model": true,\n"Is_Using_Shared_Dataset": true,\n"Modalities": ["Medical images"]\n}'}
Row 13: {'PMID': '38946041', 'llm_res': '{\n  "Affiliation_countries_tags": ["United States", "Canada"],\n  "Centralized_or_Decentralized": "Decentralized",\n  "Is_Real_World_Data_Set": true,\n  "Size_of_Data_Set": "Small to Medium-sized",\n  "AI_or_ML_Tools_In_The_Paper": NIL,\n  "Governance_Mode": NIL,\n  "Patient_Level_Data": true,\n  "Type_of_Patient_Level_Data": "Clinical data",\n  "Clinical_Data_Type": ["scoliosis"],\n  "Is_Using_Survey_Data": false,\n  "Is_Using_Questionnaire": false,\n  "Federated_Learning_Techniques": NIL,\n  "Privacy_Preserving_Techniques": NIL,\n  "Data_Collection_Method": ["Retrospective review of prospectively collected data"],\n  "Is_Using_Large_Language_Model": false,\n  "Is_Using_Multimodal_Model": false,\n  "Is_Using_Shared_Dataset": false,\n  "Modalities": ["Image", "Radiograph"]\n}'}

In [ ]:
# all canadian papers related to AI and ML
canada_df

,PMID,MedlineCitationOwner,MedlineCitationStatus,MedlineCitationVersionID,MedlineCitationVersionDate,MedlineCitationIndexingMethod,DateRevised,ArticlePubModel,JournalISSN,JournalTitle,...,GrantList,PublicationTypeList,ArticleDates,PublicationStatus,ArticleIds,History,Objects,DateCompleted,VernacularTitle,tags
0,28350526,NLM,MEDLINE,NaN,NaN,NaN,"{'Year': '2018', 'Month': '10', 'Day': '29'}",Print-Electronic,1748-3115,Disability and rehabilitation. Assistive techn...,...,[],"['Journal Article', 'Observational Study', ""Re...","[{'Year': '2017', 'Month': '03', 'Day': '28', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '28350526'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...",[],"{'Year': '2018', 'Month': '10', 'Day': '29'}",NaN,"[{Canada}, {Canada}]"
1,28444633,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2019', 'Month': '12', 'Day': '10'}",Print,1531-5320,Psychonomic bulletin & review,...,"[{'GrantID': 'Discovery Grant (312409-05)', 'A...","['Journal Article', ""Research Support, Non-U.S...",[],ppublish,"[{'IdType': 'pubmed', 'Value': '28444633'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...",[],"{'Year': '2019', 'Month': '02', 'Day': '07'}",NaN,"[{Canada}, {Canada}]"
2,28550657,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2019', 'Month': '02', 'Day': '15'}",Print,1554-3528,Behavior research methods,...,[],['Journal Article'],[],ppublish,"[{'IdType': 'pubmed', 'Value': '28550657'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...",[],"{'Year': '2019', 'Month': '02', 'Day': '11'}",NaN,[{Canada}]
3,28589480,NLM,MEDLINE,NaN,NaN,Curated,"{'Year': '2019', 'Month': '12', 'Day': '10'}",Print,1573-3602,Journal of gambling studies,...,"[{'GrantID': '3441', 'Acronym': None, 'Agency'...",['Journal Article'],[],ppublish,"[{'IdType': 'pubmed', 'Value': '28589480'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...",[],"{'Year': '2018', 'Month': '07', 'Day': '16'}",NaN,"[{Canada}, {Canada}, {Canada}, {Canada}]"
4,28596271,NLM,MEDLINE,NaN,NaN,NaN,"{'Year': '2019', 'Month': '10', 'Day': '25'}",Print-Electronic,1522-1601,"Journal of applied physiology (Bethesda, Md. :...",...,[],"['Clinical Trial', 'Journal Article', ""Researc...","[{'Year': '2017', 'Month': '06', 'Day': '08', ...",ppublish,"[{'IdType': 'pubmed', 'Value': '28596271'}, {'...","[{'PubStatus': 'pubmed', 'Year': '2017', 'Mont...",[],"{'Year': '2019', 'Month': '10', 'Day': '25'}",NaN,"[{Canada}, {Brazil}, {Canada}, {Canada}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7751,39013736,NLM,Publisher,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '16'}",Print-Electronic,1878-4046,Academic radiology,...,[],['Journal Article'],"[{'Year': '2024', 'Month': '07', 'Day': '15', ...",aheadofprint,"[{'IdType': 'pubmed', 'Value': '39013736'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],NaN,NaN,"[{Canada}, {Canada}, {Canada}, {Canada}, {Cana..."
7752,39013848,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '16'}",Electronic,2041-1723,Nature communications,...,[],['Journal Article'],"[{'Year': '2024', 'Month': '07', 'Day': '17', ...",epublish,"[{'IdType': 'pubmed', 'Value': '39013848'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"{'Year': '2024', 'Month': '07', 'Day': '16'}",NaN,"[{Germany}, {Japan}, {Germany}, {United States..."
7753,39013867,NLM,MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '16'}",Electronic,2041-1723,Nature communications,...,"[{'GrantID': 'PJT-180505', 'Acronym': None, 'A...",['Journal Article'],"[{'Year': '2024', 'Month': '07', 'Day': '16', ...",epublish,"[{'IdType': 'pubmed', 'Value': '39013867'}, {'...","[{'PubStatus': 'received', 'Year': '2023', 'Mo...",[],"{'Year': '2024', 'Month': '07', 'Day': '16'}",NaN,"[{Canada}, {Canada}, {Canada}, {Canada}, {Cana..."
7754,39015068,NLM,Publisher,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '17'}",Print-Electronic,1097-6817,Otolaryngology--head and neck surgery : offici...,...,[],['Journal Article'],"[{'Year': '2024', 'Month': '07', 'Day': '17', ...",aheadofprint,"[{'IdType': 'pubmed', 'Value': '39015068'}, {'...","[{'PubStatus': 'revised', 'Year': '2024', 'Mon...",[],NaN,NaN,"[{United States}, {Canada}, {United States}, {..."
7755,39015268,NLM,PubMed-not-MEDLINE,NaN,NaN,Automated,"{'Year': '2024', 'Month': '07', 'Day': '17'}",Electronic-eCollection,1948-5875,ACS medicinal chemistry letters,...,[],['Journal Article'],"[{'Year': '2024', 'Month': '06', 'Day': '06', ...",epublish,"[{'IdType': 'pubmed', 'Value': '39015268'}, {'...","[{'PubStatus': 'received', 'Year': '2024', 'Mo...",[],NaN,NaN,[{Canada}]

In [ ]:
import json
import pandas as pd

# Load raw data
with open('canada_review_results_2025.json', 'r') as file:
    raw_data = json.load(file)

# Clean and parse each stringified JSON object
parsed_data = {}
for k, v in raw_data.items():
    # Replace invalid "NIL" with proper JSON null
    cleaned_str = v.replace('NIL', 'null')

    try:
        parsed_data[k] = json.loads(cleaned_str)
    except json.JSONDecodeError as e:
        print(f"Error decoding record {k}: {e}")
        parsed_data[k] = None  # or skip / log for review

# Filter out failed entries
parsed_data = {k: v for k, v in parsed_data.items() if v is not None}

# Convert to DataFrame
df = pd.DataFrame.from_dict(parsed_data, orient='index').reset_index()
df.rename(columns={'index': 'Record_ID'}, inplace=True)

# Display the first few rows
df.head()

Error decoding record 38383805: Expecting value: line 1 column 1 (char 0)
Error decoding record 38405768: Expecting ',' delimiter: line 7 column 22 (char 267)
Error decoding record 38512435: Expecting ',' delimiter: line 10 column 27 (char 413)
Error decoding record 38575195: Expecting ':' delimiter: line 3 column 11 (char 46)
Error decoding record 38647191: Expecting ',' delimiter: line 5 column 25 (char 157)
Error decoding record 38696699: Expecting ',' delimiter: line 3 column 35 (char 113)
Error decoding record 38789645: Expecting ',' delimiter: line 19 column 48 (char 808)
Error decoding record 38857570: Expecting ',' delimiter: line 19 column 32 (char 698)
Error decoding record 38871841: Expecting ',' delimiter: line 4 column 31 (char 152)
Error decoding record 38878395: Expecting ',' delimiter: line 15 column 29 (char 490)
Error decoding record 38880121: Expecting value: line 1 column 1 (char 0)
Error decoding record 38881045: Expecting ',' delimiter: line 7 column 24 (char 226)
Error decoding record 38901097: Expecting ',' delimiter: line 4 column 29 (char 127)
Error decoding record 38908306: Expecting ',' delimiter: line 19 column 29 (char 679)
Error decoding record 38951248: Expecting ',' delimiter: line 19 column 22 (char 850)
Error decoding record 38972258: Expecting property name enclosed in double quotes: line 5 column 24 (char 156)
Error decoding record 38981593: Expecting value: line 1 column 1 (char 0)
Error decoding record 38997146: Expecting ',' delimiter: line 5 column 25 (char 158)
Error decoding record 39009211: Expecting value: line 1 column 1 (char 0)
Error decoding record 39022175: Expecting ',' delimiter: line 19 column 24 (char 636)
Error decoding record 39024163: Expecting ',' delimiter: line 15 column 29 (char 503)
Error decoding record 39025402: Expecting value: line 1 column 1 (char 0)
Error decoding record 39026819: Expecting ',' delimiter: line 5 column 23 (char 152)
Error decoding record 39028670: Expecting ',' delimiter: line 7 column 24 (char 247)
Error decoding record 39030380: Expecting value: line 1 column 1 (char 0)
Error decoding record 39033326: Expecting value: line 4 column 27 (char 110)
Error decoding record 39034988: Expecting value: line 1 column 1 (char 0)
Error decoding record 39037754: Expecting value: line 1 column 1 (char 0)
Error decoding record 39037850: Expecting ',' delimiter: line 19 column 18 (char 623)
Error decoding record 39037993: Expecting ',' delimiter: line 3 column 35 (char 139)
Error decoding record 39039296: Expecting ',' delimiter: line 19 column 55 (char 764)
Error decoding record 39040582: Expecting value: line 1 column 1 (char 0)
Error decoding record 39045485: Expecting ',' delimiter: line 19 column 87 (char 872)
Error decoding record 39047027: Expecting value: line 1 column 1 (char 0)
Error decoding record 39047974: Expecting value: line 4 column 27 (char 110)
Error decoding record 39049285: Expecting ',' delimiter: line 9 column 33 (char 279)
Error decoding record 39051104: Expecting ',' delimiter: line 13 column 7 (char 273)
Error decoding record 39052314: Expecting ',' delimiter: line 4 column 33 (char 143)
Error decoding record 39052668: Expecting ',' delimiter: line 3 column 39 (char 214)
Error decoding record 39053116: Expecting value: line 1 column 1 (char 0)
Error decoding record 39053540: Expecting ',' delimiter: line 19 column 18 (char 643)
Error decoding record 39054361: Expecting ',' delimiter: line 5 column 23 (char 163)
Error decoding record 39059710: Expecting ',' delimiter: line 17 column 29 (char 532)
Error decoding record 39060305: Expecting ',' delimiter: line 4 column 31 (char 127)
Error decoding record 39061178: Expecting ',' delimiter: line 19 column 31 (char 765)
Error decoding record 39066637: Expecting ',' delimiter: line 19 column 27 (char 687)
Error decoding record 39067309: Expecting ',' delimiter: line 14 column 36 (char 655)
Error decoding record 39068830: Expecting ',' delimiter: line 5 column 25 (char 230)
Error decoding record 39069148: Expecting ',' delimiter: line 9 column 35 (char 365)
Error decoding record 39070129: Expecting ',' delimiter: line 5 column 29 (char 182)
Error decoding record 39075055: Expecting ',' delimiter: line 11 column 34 (char 394)
Error decoding record 39075133: Expecting property name enclosed in double quotes: line 6 column 24 (char 184)
Error decoding record 39076208: Expecting ',' delimiter: line 7 column 22 (char 264)
Error decoding record 39078880: Expecting ',' delimiter: line 19 column 18 (char 629)
Error decoding record 39079541: Expecting ',' delimiter: line 4 column 33 (char 131)
Error decoding record 39080159: Expecting ',' delimiter: line 7 column 22 (char 240)
Error decoding record 39082215: Expecting value: line 4 column 27 (char 127)
Error decoding record 39083765: Expecting ',' delimiter: line 5 column 23 (char 166)
Error decoding record 39084408: Expecting ',' delimiter: line 7 column 22 (char 249)
Error decoding record 39085375: Expecting ',' delimiter: line 4 column 29 (char 121)
Error decoding record 39085477: Expecting value: line 1 column 1 (char 0)
Error decoding record 39088324: Expecting ',' delimiter: line 5 column 23 (char 150)
Error decoding record 39090192: Expecting ',' delimiter: line 7 column 22 (char 249)
Error decoding record 39090573: Expecting value: line 1 column 1 (char 0)
Error decoding record 39092239: Expecting ',' delimiter: line 19 column 18 (char 629)
Error decoding record 39092497: Expecting ',' delimiter: line 19 column 51 (char 689)
Error decoding record 39094840: Expecting ',' delimiter: line 19 column 22 (char 753)
Error decoding record 39095975: Expecting ',' delimiter: line 3 column 35 (char 91)
Error decoding record 39096240: Expecting value: line 1 column 1 (char 0)
Error decoding record 39097076: Expecting ',' delimiter: line 19 column 51 (char 721)
Error decoding record 39097471: Expecting ',' delimiter: line 19 column 20 (char 708)
Error decoding record 39098369: Expecting ',' delimiter: line 19 column 23 (char 701)
Error decoding record 39101315: Expecting ',' delimiter: line 15 column 29 (char 511)
Error decoding record 39103509: Expecting value: line 1 column 1 (char 0)
Error decoding record 39103539: Expecting ',' delimiter: line 3 column 35 (char 122)
Error decoding record 39103943: Expecting ',' delimiter: line 5 column 23 (char 149)
Error decoding record 39104689: Expecting value: line 1 column 1 (char 0)
Error decoding record 39107243: Expecting ',' delimiter: line 7 column 22 (char 216)
Error decoding record 39111636: Expecting ',' delimiter: line 5 column 23 (char 151)
Error decoding record 39111972: Expecting ',' delimiter: line 20 column 56 (char 728)
Error decoding record 39112632: Expecting ',' delimiter: line 19 column 54 (char 734)
Error decoding record 39114779: Expecting value: line 4 column 27 (char 108)
Error decoding record 39116018: Expecting value: line 1 column 1 (char 0)
Error decoding record 39118320: Expecting value: line 4 column 27 (char 110)
Error decoding record 39118548: Expecting ',' delimiter: line 19 column 18 (char 620)
Error decoding record 39121797: Expecting ',' delimiter: line 7 column 22 (char 263)
Error decoding record 39122153: Expecting ',' delimiter: line 19 column 41 (char 702)
Error decoding record 39122422: Expecting value: line 1 column 1 (char 0)
Error decoding record 39123282: Expecting ',' delimiter: line 15 column 29 (char 518)
Error decoding record 39123865: Expecting ',' delimiter: line 4 column 29 (char 132)
Error decoding record 39124000: Expecting ',' delimiter: line 3 column 39 (char 98)
Error decoding record 39126706: Expecting ',' delimiter: line 15 column 29 (char 501)
Error decoding record 39126971: Expecting ',' delimiter: line 19 column 22 (char 707)
Error decoding record 39131324: Expecting value: line 4 column 27 (char 112)
Error decoding record 39132480: Expecting ',' delimiter: line 14 column 37 (char 479)
Error decoding record 39134725: Expecting ',' delimiter: line 4 column 29 (char 197)
Error decoding record 39135903: Expecting ',' delimiter: line 3 column 35 (char 88)
Error decoding record 39136673: Expecting ',' delimiter: line 19 column 88 (char 806)
Error decoding record 39137884: Expecting ',' delimiter: line 19 column 18 (char 633)
Error decoding record 39139542: Expecting value: line 1 column 1 (char 0)
Error decoding record 39140200: Expecting ',' delimiter: line 15 column 29 (char 502)
Error decoding record 39147042: Expecting value: line 1 column 1 (char 0)
Error decoding record 39147133: Expecting ',' delimiter: line 3 column 39 (char 167)
Error decoding record 39147830: Expecting ',' delimiter: line 7 column 24 (char 245)
Error decoding record 39148259: Expecting ',' delimiter: line 19 column 57 (char 687)
Error decoding record 39148930: Expecting ',' delimiter: line 7 column 22 (char 239)
Error decoding record 39148932: Expecting ',' delimiter: line 7 column 22 (char 259)
Error decoding record 39149460: Expecting ',' delimiter: line 19 column 49 (char 663)
Error decoding record 39151887: Expecting ',' delimiter: line 6 column 37 (char 452)
Error decoding record 39152127: Expecting value: line 4 column 27 (char 134)
Error decoding record 39152475: Expecting ',' delimiter: line 7 column 22 (char 244)
Error decoding record 39153834: Expecting ',' delimiter: line 7 column 22 (char 215)
Error decoding record 39153961: Expecting value: line 1 column 1 (char 0)
Error decoding record 39155454: Expecting ',' delimiter: line 7 column 22 (char 244)
Error decoding record 39155720: Expecting value: line 4 column 27 (char 117)
Error decoding record 39155722: Expecting ',' delimiter: line 3 column 35 (char 85)
Error decoding record 39158427: Expecting ',' delimiter: line 19 column 21 (char 616)
Error decoding record 39159584: Expecting ',' delimiter: line 19 column 32 (char 692)
Error decoding record 39160586: Expecting ',' delimiter: line 19 column 18 (char 637)
Error decoding record 39162740: Expecting ',' delimiter: line 20 column 18 (char 648)
Error decoding record 39164888: Expecting ',' delimiter: line 19 column 23 (char 658)
Error decoding record 39165097: Expecting ',' delimiter: line 19 column 73 (char 691)
Error decoding record 39165145: Expecting ',' delimiter: line 10 column 25 (char 328)
Error decoding record 39167442: Expecting property name enclosed in double quotes: line 5 column 40 (char 161)
Error decoding record 39168075: Expecting ',' delimiter: line 19 column 21 (char 708)
Error decoding record 39171102: Expecting ',' delimiter: line 19 column 61 (char 884)
Error decoding record 39172830: Expecting ',' delimiter: line 19 column 18 (char 747)
Error decoding record 39175366: Expecting value: line 1 column 1 (char 0)
Error decoding record 39176885: Expecting value: line 1 column 1 (char 0)
Error decoding record 39176892: Expecting ',' delimiter: line 19 column 30 (char 724)
Error decoding record 39176959: Expecting value: line 4 column 29 (char 127)
Error decoding record 39178224: Expecting ',' delimiter: line 3 column 35 (char 137)
Error decoding record 39178369: Expecting ',' delimiter: line 19 column 18 (char 632)
Error decoding record 39180117: Expecting value: line 1 column 1 (char 0)
Error decoding record 39180855: Expecting value: line 11 column 25 (char 381)
Error decoding record 39182418: Expecting ',' delimiter: line 19 column 31 (char 663)
Error decoding record 39182775: Expecting ',' delimiter: line 3 column 37 (char 77)
Error decoding record 39187013: Expecting value: line 1 column 1 (char 0)
Error decoding record 39187703: Expecting ',' delimiter: line 10 column 25 (char 374)
Error decoding record 39191563: Expecting ',' delimiter: line 19 column 51 (char 726)
Error decoding record 39191756: Expecting value: line 1 column 1 (char 0)
Error decoding record 39191772: Expecting ',' delimiter: line 7 column 24 (char 224)
Error decoding record 39194260: Expecting ',' delimiter: line 7 column 22 (char 297)
Error decoding record 39194400: Expecting ',' delimiter: line 9 column 37 (char 359)
Error decoding record 39196703: Expecting value: line 1 column 1 (char 0)
Error decoding record 39196959: Expecting value: line 1 column 1 (char 0)
Error decoding record 39197681: Expecting value: line 1 column 1 (char 0)
Error decoding record 39197760: Expecting value: line 1 column 1 (char 0)
Error decoding record 39198623: Expecting ',' delimiter: line 5 column 23 (char 147)
Error decoding record 39198655: Expecting ',' delimiter: line 15 column 29 (char 525)
Error decoding record 39201222: Expecting ',' delimiter: line 19 column 18 (char 640)
Error decoding record 39202209: Expecting ',' delimiter: line 19 column 76 (char 756)
Error decoding record 39203524: Expecting value: line 1 column 1 (char 0)
Error decoding record 39207351: Expecting ',' delimiter: line 3 column 35 (char 104)
Error decoding record 39208523: Expecting value: line 1 column 1 (char 0)
Error decoding record 39209988: Expecting ',' delimiter: line 19 column 152 (char 877)
Error decoding record 39211048: Expecting ',' delimiter: line 5 column 25 (char 178)
Error decoding record 39212671: Expecting ',' delimiter: line 19 column 29 (char 694)
Error decoding record 39212991: Expecting ',' delimiter: line 7 column 22 (char 349)
Error decoding record 39217446: Expecting ',' delimiter: line 10 column 25 (char 316)
Error decoding record 39217803: Expecting ',' delimiter: line 15 column 29 (char 631)
Error decoding record 39225775: Expecting ',' delimiter: line 11 column 25 (char 498)
Error decoding record 39227061: Expecting ',' delimiter: line 3 column 35 (char 98)
Error decoding record 39228995: Expecting value: line 1 column 1 (char 0)
Error decoding record 39230789: Expecting ',' delimiter: line 15 column 29 (char 521)
Error decoding record 39231549: Expecting ',' delimiter: line 7 column 22 (char 203)
Error decoding record 39232128: Expecting value: line 1 column 1 (char 0)
Error decoding record 39232812: Expecting ',' delimiter: line 3 column 35 (char 89)
Error decoding record 39233007: Expecting value: line 1 column 1 (char 0)
Error decoding record 39238140: Expecting ',' delimiter: line 10 column 25 (char 325)
Error decoding record 39239995: Expecting ',' delimiter: line 19 column 38 (char 962)
Error decoding record 39240565: Expecting ',' delimiter: line 7 column 22 (char 262)
Error decoding record 39244483: Expecting ',' delimiter: line 5 column 23 (char 154)
Error decoding record 39245713: Expecting ',' delimiter: line 19 column 18 (char 629)
Error decoding record 39246139: Expecting ',' delimiter: line 3 column 35 (char 160)
Error decoding record 39254193: Expecting ',' delimiter: line 19 column 18 (char 634)
Error decoding record 39254470: Expecting ',' delimiter: line 5 column 23 (char 150)
Error decoding record 39255470: Expecting value: line 1 column 1 (char 0)
Error decoding record 39256075: Expecting value: line 4 column 27 (char 119)
Error decoding record 39257289: Expecting ',' delimiter: line 19 column 23 (char 690)
Error decoding record 39260829: Expecting ',' delimiter: line 19 column 18 (char 783)
Error decoding record 39261226: Expecting ',' delimiter: line 19 column 44 (char 834)
Error decoding record 39261642: Expecting ',' delimiter: line 19 column 29 (char 669)
Error decoding record 39261740: Expecting ',' delimiter: line 7 column 22 (char 242)
Error decoding record 39261837: Expecting ',' delimiter: line 15 column 29 (char 500)
Error decoding record 39264706: Expecting ',' delimiter: line 19 column 18 (char 631)
Error decoding record 39265163: Expecting value: line 9 column 23 (char 296)
Error decoding record 39283190: Expecting value: line 4 column 27 (char 166)
Error decoding record 39283667: Expecting ',' delimiter: line 19 column 18 (char 649)
Error decoding record 39285176: Expecting ',' delimiter: line 3 column 35 (char 163)
Error decoding record 39285345: Expecting ',' delimiter: line 19 column 18 (char 624)
Error decoding record 39285373: Expecting ',' delimiter: line 19 column 18 (char 806)
Error decoding record 39286491: Expecting ',' delimiter: line 4 column 29 (char 138)
Error decoding record 39290307: Expecting ',' delimiter: line 7 column 22 (char 257)
Error decoding record 39290876: Expecting ',' delimiter: line 5 column 23 (char 239)
Error decoding record 39295471: Expecting value: line 1 column 1 (char 0)
Error decoding record 39295734: Expecting ',' delimiter: line 4 column 29 (char 116)
Error decoding record 39297189: Expecting ',' delimiter: line 19 column 18 (char 739)
Error decoding record 39302455: Expecting ',' delimiter: line 3 column 37 (char 124)
Error decoding record 39302582: Expecting value: line 1 column 1 (char 0)
Error decoding record 39303691: Expecting ',' delimiter: line 15 column 29 (char 494)
Error decoding record 39304672: Expecting value: line 1 column 1 (char 0)
Error decoding record 39306906: Expecting value: line 1 column 1 (char 0)
Error decoding record 39307095: Expecting value: line 1 column 1 (char 0)
Error decoding record 39311140: Expecting ',' delimiter: line 19 column 18 (char 678)
Error decoding record 39312500: Expecting property name enclosed in double quotes: line 5 column 24 (char 166)
Error decoding record 39312778: Expecting ',' delimiter: line 3 column 35 (char 139)
Error decoding record 39313595: Expecting ',' delimiter: line 9 column 33 (char 319)
Error decoding record 39315514: Expecting ',' delimiter: line 19 column 27 (char 683)
Error decoding record 39316160: Expecting ',' delimiter: line 19 column 38 (char 783)
Error decoding record 39319317: Expecting ',' delimiter: line 19 column 18 (char 639)
Error decoding record 39319335: Expecting ',' delimiter: line 15 column 29 (char 492)
Error decoding record 39321537: Expecting value: line 4 column 27 (char 110)
Error decoding record 39322490: Expecting value: line 1 column 1 (char 0)
Error decoding record 39324295: Expecting ',' delimiter: line 5 column 23 (char 147)
Error decoding record 39325010: Expecting ',' delimiter: line 9 column 37 (char 311)
Error decoding record 39325508: Expecting ',' delimiter: line 7 column 22 (char 255)
Error decoding record 39330030: Expecting ',' delimiter: line 3 column 25 (char 93)
Error decoding record 39330487: Expecting value: line 4 column 27 (char 110)
Error decoding record 39330905: Expecting value: line 1 column 1 (char 0)
Error decoding record 39331565: Expecting ',' delimiter: line 19 column 72 (char 689)
Error decoding record 39332081: Expecting value: line 1 column 1 (char 0)
Error decoding record 39333580: Expecting ',' delimiter: line 15 column 29 (char 479)
Error decoding record 39334143: Expecting value: line 4 column 27 (char 118)
Error decoding record 39335379: Expecting value: line 4 column 27 (char 116)
Error decoding record 39335390: Expecting ',' delimiter: line 7 column 22 (char 250)
Error decoding record 39337060: Expecting ',' delimiter: line 4 column 29 (char 132)
Error decoding record 39338848: Expecting ',' delimiter: line 3 column 35 (char 92)
Error decoding record 39344772: Expecting ',' delimiter: line 10 column 25 (char 358)
Error decoding record 39347450: Expecting ',' delimiter: line 15 column 29 (char 546)
Error decoding record 39349065: Expecting ',' delimiter: line 9 column 33 (char 287)
Error decoding record 39349642: Expecting ',' delimiter: line 19 column 18 (char 697)
Error decoding record 39349864: Expecting ',' delimiter: line 19 column 18 (char 651)
Error decoding record 39353461: Expecting ',' delimiter: line 15 column 29 (char 565)
Error decoding record 39354219: Expecting ',' delimiter: line 19 column 20 (char 666)
Error decoding record 39354632: Expecting ',' delimiter: line 19 column 21 (char 724)
Error decoding record 39358379: Expecting ',' delimiter: line 5 column 23 (char 159)
Error decoding record 39360189: Expecting value: line 4 column 27 (char 117)
Error decoding record 39360579: Expecting value: line 1 column 1 (char 0)
Error decoding record 39360851: Expecting ',' delimiter: line 14 column 36 (char 582)

,Record_ID,Affiliation_countries_tags,Centralized_or_Decentralized,Is_Real_World_Data_Set,Size_of_Data_Set,AI_or_ML_Tools_In_The_Paper,Governance_Mode,Patient_Level_Data,Type_of_Patient_Level_Data,Clinical_Data_Type,...,C-centralized_or_decentralized,Centalized_or_Decentralized,type of Patient_Level_Data,Real_World_Data_Set,Using_Survey_Data,Using_Questionnaire,Is_Used_Shared_Dataset,type of Patient Level Data,data Collection Method,data collection method
0,37310046,"[USA, Canada]",Decentralized,True,null,null,null,False,null,null,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,38019000,[Canada],Decentralized,True,null,null,null,False,null,null,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,38190258,[Canada],Decentralized,False,null,null,null,False,null,null,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38409223,"[Canada, USA]",Decentralized,True,over 33 million cells,Generative Pretrained Transformers,null,False,null,null,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,38590142,"[Canada, Canada, Canada]",Decentralized,True,null,"[Ensemble learning methods, Random forest, Gra...",null,False,null,null,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
import json

# Load the JSON file
file_path = 'data_canada_v1_m1.json'
with open(file_path, 'r') as file:
    data = json.load(file)

# Convert the JSON data to a DataFrame
data_canada_v1_m1 = pd.DataFrame(data)

# Display the first few rows of the DataFrame
data_canada_v1_m1.head()

ValueError: If using all scalar values, you must pass an index

In [ ]:
m1_patient_level_data = data_canada_v1_m1[data_canada_v1_m1['Patient_Level_Data'].astype(
    str).str.lower() == 'true']
len(m1_patient_level_data)

2902

In [ ]:
m1_patient_level_data.iloc[0]["PID"]

'27741066'

In [ ]:
canada_df.iloc[0]['PMID']

AttributeError: 'numpy.int64' object has no attribute 'dtypes'

In [ ]:
import pandas as pd
import json

# Load the JSON file
file_path = 'data_canada_v1_m2.json'
with open(file_path, 'r') as file:
    data = json.load(file)

# Convert the JSON data to a DataFrame
data_canada_v1_m2 = pd.DataFrame(data)

# Display the first few rows of the DataFrame
data_canada_v1_m2.head()

,Affiliation_countries_tags,Centralized_or_Decentralized,Is_Real_World_Data_Set,Size_of_Data_Set,AI_or_ML_Tools_In_The_Paper,Governance_Mode,Patient_Level_Data,Type_of_Patient_Level_Data,Clinical_Data_Type,Is_Using_Survey_Data,...,Is_Using_Genomic_Data,Is_Using_Other_Kinds_of_Data,Is_Private,Is_Public,Is_Open,Is_Semi_Public,Is_Semi_Private,Is_Commercially_Sensitive,Is_Sensitive,Is_Industrially_Sensitive
0,None,Decentralized,True,"{'total': 28341, 'returned': 626}","[Artificial Neural Network, Classification Tree]",None,True,None,Predictive model,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,False,None,None,None,True,None (no patient-level data mentioned),None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[Canada],Decentralized,False,None,True,None,False,None,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Decentralized,False,None,True,None,None,None,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'Country': 'Canada', 'Tag': None}, {'Country...",None,False,None,None,None,False,None,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
m2_patient_level_data = data_canada_v1_m2[data_canada_v1_m2['Patient_Level_Data'].astype(
    str).str.lower() == 'true']
len(m2_patient_level_data)

2517

In [ ]:
import numpy as np

m1_patient_level_data['PID'] = m1_patient_level_data['PID'].astype(np.int64)

/var/folders/gx/4hmfp0zd12bblv6znjwbmv600000gn/T/ipykernel_89240/4087479661.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1_patient_level_data['PID'] = m1_patient_level_data['PID'].astype(np.int64)

In [ ]:
m1_patient_level_data.iloc[0]["PID"]

27741066

In [ ]:
canada_df_merged_m1 = pd.merge(
    canada_df, m1_patient_level_data, how='left', left_on='PMID', right_on='PID')

In [ ]:
canada_df_merged_m1.iloc[1]  # ['Patient_Level_Data']

PMID                               28444633
MedlineCitationOwner                    NLM
MedlineCitationStatus               MEDLINE
MedlineCitationVersionID                NaN
MedlineCitationVersionDate              NaN
                                     ...
Isof_Using_Shared_Dataset               NaN
Isof_Using_Large_Language_Model         NaN
Isof_Using_Multimodal_Model             NaN
Isover_ML_Tools_In_The_Paper            NaN
Impact_on_Radiation_Therapy             NaN
Name: 1, Length: 198, dtype: object

In [ ]:
# Set display options to show all columns and rows
pd.set_option('display.max_columns', None)  # None means no limit
pd.set_option('display.max_rows', None)  # Adjust based on your needs
pd.set_option('display.max_colwidth', None)  # No limit on column width
m1_patient_level_data.head(20)

,Affiliation_countries,Centralized_or_Decentralized,Is_Real_World_Data_Set,Size_of_Data_Set,AI_or_ML_Tools_In_The_Paper,Governance_Mode,Patient_Level_Data,Type_of_Patient_Level_Data,Clinical_Data_Type,Is_Using_Survey_Data,Is_Using_Questionnaire,Federated_Learning_Techniques,Privacy_Preserving_Techniques,Data_Collection_Method,Is_Using_Large_Language_Model,Is_Using_Multimodal_Model,Is_Using_Shared_Dataset,Modalities,PID,Affiliation_countries_tags,type_of_patient_level_data,data_collection_method,is_using_large_language_model,is_using_multimodal_model,is_using_shared_dataset,Countries,data_Collection_Method,is_using_survey_data,is_using_questionnaire,Ai_or_ml_tools_in_the_paper,type of patient level data,Clinical Data Type,is using survey data,is using questionnaire,Federated Learning Techniques,Privacy Preserving Techniques,data collection method,is using large language model,is using multimodal model,is using shared dataset,Ai_or_ML_Tools_In_The_Paper,type of Patient Level Data,modalities,is_Using_Survey_Data,is_Using_Questionnaire,is_Using_Large_Language_Model,is_Using_Multimodal_Model,is_Using_Shared_Dataset,Governance_mode,Patient_level_data,Type_of_patient_level_data,Clinical_data_type,Is_using_survey_data,Is_using_questionnaire,Federated_learning_techniques,Privacy_preserving_techniques,Data_collection_method,Is_using_large_language_model,Is_using_multimodal_model,Is_using_shared_dataset,Countries_tags,Is_Using_Claimed_To_Be_Real_World_Data_Set,Is_Using_Patient_Level_Data,Ai_or_Ml_Tools_In_The_Paper,Countries_tag,type of Patient_Level_Data,Tags,C centralized_or_decen_tralized,is_USing_Survey_Data,is_USing_Questionnaire,is_USing_Large_Language_Model,is_USing_Multimodal_Model,is_USing_Shared_Dataset,Centalized_or_Decentralized,C centralized_or_Decentralized,Iso_of_Data_Set,Isof_Patient_Level_Data,P patient_Level_Data_Type,Centralized,Decentralized,is_using_Survey_Data,Countries_tagged,Impact_of_Privacy_Preserving_Techniques,Is_Using_Real_World_Data_Set,C-centralized_or-Decentralized,Type_of_Patient_Level_Dose,is Using Survey Data,is Using Questionnaire,data Collection Method,is Using Large Language Model,is Using Multimodal Model,is Using Shared Dataset,Data Collection Method,Is_Using LARGE_LANGUAGE_MODEL,Is_Using_MULTIMODAL_MODEL,Is_Using_SHARED_DATASET,Real_world_data_set,Survey_Data,Questionnaire,Largest_Language_Model,Multimodal_Model,Shared_Dataset,Is Using Survey Data,Is Using Questionnaire,Is Using Large Language Model,Is Using Multimodal Model,Is Using Shared Dataset,Real_World_Data_Set,Using_Survey_Data,Using_Questionnaire,Using_Large_Language_Model,Using_Multimodal_Model,Using_Shared_Dataset,Impact_on_Patient_Healthcare,is_using_Questionnaire,Impact_of_Synergy_Between_AI_ML_And_Robotic_Systems,is_using_Large_Language_Model,is_using_Multimodal_Model,is_using_Shared_Dataset,Is_Used_Shared_Dataset,C centralized_or_decentralized,data_collection_Method,is_USING_Survey_Data,is_USING_Questionnaire,is_USING_Large_Language_Model,is_USING_Multimodal_Model,is_USING_Shared_Dataset,Patinet_Level_Data,Iso_Patient_Level_Data,C centralized_or_D decentralized,clinical_data_type,Is_Used_Multimodal_Model,Cumulative_sum_analysis_used,Type_of_Patient_Level_Dataset,Airtightness_evaluation_of_Canadian_dwellings_and_influencing_factors_based_on_measured_data_and_predictive_models,AFFILIATION_COUNTRIES,CENTRALIZED_OR_DECentralized,IS_REAL_WORLD_DATA_SET,SIZE_OF_DATA_SET,AI_OR_ML_TOOLS_IN_THE_PAPER,GOVERNANCE_MODE,PATIENT_LEVEL_DATA,TYPE_OF_PATIENT_LEVEL_DATA,CLINICAL_DATA_TYPE,IS_USING_SURVEY_DATA,IS_USING_QUESTIONNAIRE,FEDERATED_LEARNING_TECHNIQUES,PRIVACY_PRESERVING_TECHNIQUES,DATA_COLLECTION_METHOD,IS_USING_LARGE_LANGUAGE_MODEL,IS_USING_MULTIMODAL_MODEL,IS_USING_SHARED_DATASET,MODALITIES,Is_Using MULTIMODAL_MODEL,Isof_Data_Set,Is_Using_Clinical_Data,Mental_Health_Dataset,Centralized_or_Distributed,Implicit_Dataset_Description,Affiliations,Iso_ML_Tools_In_The_Paper,Machine_Learning_Methods,Isof_Using_Survey_Data,Isof_Using_Questionnaire,Isof_Using_Shared_Dataset,Isof_Using_Large_Language_Model,Isof_Using_Multimodal_Model,Isover_ML_Tools_In_The_Paper,Impact_on_Radiation_Therapy
0,[Italy],None,True,28341,"[ANN, CT]",None,True,None,None,False,False,None,None,[retrospective],False,False,False,None,27741066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Decentralized,True,382,None,None,True,Functional brain connectivity data,Schizophrenia diagnosis classification,False,False,None,None,fMRI data from 6 scanning sites and under different task conditions,False,True,True,[fMRI],28601499,"[Canada, Australia]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Decentralized,True,"220 (schizophrenia), 110 (depression), 240 (healthy controls)",[],None,True,Neurocognitive performance data,None,False,False,[],[],None,NaN,NaN,NaN,"[Computerized Cambridge Neurocognitive Test Automated Battery, Short version of the Wechsler Adult Intelligence Scale-Revised in China, Immediate and delayed logical memory of the Wechsler Memory Scale-Revised in China]",28651909,"[Canada, China]",NaN,NaN,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Centralized,False,None,True,None,True,Nil,Nil,False,False,None,None,None,False,False,False,[Nil],28673115,[Canada],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Decentralized,False,None,None,None,True,None,None,False,False,None,None,Experimental,False,False,False,"[Haptics, Robot]",28696831,"[Canada, Colombia]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,None,True,3915,[Support Vector Machine (SVM)],None,True,Microbial profiles,None,False,False,None,None,[Subgingival biofilm samples],False,False,False,[Checkerboard DNA-DNA hybridisation],28771699,"[Brazil, Israel, Canada]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,"[China, Canada]",Decentralized,True,None,None,None,True,Lower Limbs Rehabilitation Robot,None,False,False,None,None,None,False,False,False,[Lower Limbs Rehabilitation Robot],28869436,NaN,NaN,NaN,NaN,NaN,NaN,"[China, Canada]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,Decentralized,True,None,None,None,True,Medical,Blood Pressure,False,False,None,None,Observational,False,False,False,[Medical],28952798,"[USA, Canada]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"[Canada, Germany, USA]",Decentralized,True,None,"[{'name': 'Novel analytical framework'}, {'name': 'Supervised learning approaches'}]",None,True,"[MRI markers, Cortex-wide MRI]",[Autism Diagnostic Observation Schedule],False,False,None,None,Multi-centric cohort,False,True,False,[MRI],28968847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"[Germany, Canada]",Decentralized,True,None,[ML],None,True,Clinical and demographic data,Nil,False,True,False,None,Experimental,False,False,True,[Nil],28981875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Decentralized,True,145,"[Convolution Neural Network, Recurrent Neural Network]",None,True,MR sequences,Cardiac function assessment,False,False,None,None,Medical Imaging,False,True,False,[MR],28987903,[Canada],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,[Canada],None,True,None,None,None,True,None,None,None,None,None,None,NaN,False,None,None,None,29042099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Decentralized,True,41,None,None,True,Cerebrovascular responsiveness,ICP and cortical laser Doppler flowmetry (LDF),False,False,None,None,Retrospective cohort,False,False,True,"[Transcranial Doppler (TCD), Intracranial pressure (ICP), Cortical laser Doppler flowmetry (LDF)]",29043544,"[UK, Canada, Poland]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Decentralized,True,172,None,None,True,Clinical Data,Traumatic Spinal Cord Injury,False,None,None,None,None,None,None,None,[Clinical],29065782,[Canada],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,[Canada],Centralized,True,None,"[Deep learning, Random Forest]",None,True,Image,None,False,False,None,None,Multimodal,False,True,False,"[Myelin, T1-weighted MRI]",29071211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,"[Canada, Ontario]",Decentralized,True,None,NaN,None,True,"Sensorimotor, visuospatial attention, and executive function impairments","Montreal Cognitive Assessment, Fugl-Meyer upper extremity assessment, and Purdue Peg Board",False,None,None,None,NaN,False,True,None,"[Sensorimotor, Visuospatial attention, Working Memory, Executive Function]",29084099,NaN,NaN,Observational case series,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,Decentralized,True,None,None,None,True,None,None,None,None,None,None,None,False,False,True,[Electronic medical data],29094375,"[Canada, USA]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,Decentralized,True,577,None,None,True,Cognitive features,None,False,False,None,None,Neurocognitive tests,False,False,None,[Cognitive features],29098645,"[China, Canada, The Netherlands]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,Decentralized,True,50,None,None,True,EEG,Depression,False,False,None,None,EEG,False,False,False,[EEG],29128490,"[Australia, Canada]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# len(canada_df)
canada_df.to_json('countries_affiliation_df_canada.json', orient='records')

In [ ]:
! pip install selenium

Collecting selenium
  Downloading selenium-4.23.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.2)
Collecting trio~=0.17 (from selenium)
  Downloading trio-0.26.2-py3-none-any.whl.metadata (8.6 kB)
Collecting trio-websocket~=0.9 (from selenium)
  Using cached trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: certifi>=2021.10.8 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from selenium) (2024.6.2)
Requirement already satisfied: typing_extensions~=4.9 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from selenium) (1.8.0)
Collecting attrs>=23.2.0 (from trio~=0.17->selenium)
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sortedcontainers in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from trio~=0.17->selenium) (3.7)
Collecting outcome (from trio~=0.17->selenium)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from trio~=0.17->selenium) (1.3.0)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Using cached wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Downloading selenium-4.23.1-py3-none-any.whl (9.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 16.2 MB/s eta 0:00:0000:0100:01
Downloading trio-0.26.2-py3-none-any.whl (475 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 476.0/476.0 kB 8.4 MB/s eta 0:00:00:00:01
Using cached trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 3.4 MB/s eta 0:00:00
Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Installing collected packages: h11, attrs, wsproto, outcome, trio, trio-websocket, selenium
  Attempting uninstall: attrs
    Found existing installation: attrs 23.1.0
    Uninstalling attrs-23.1.0:
      Successfully uninstalled attrs-23.1.0
Successfully installed attrs-24.2.0 h11-0.14.0 outcome-1.3.0.post0 selenium-4.23.1 trio-0.26.2 trio-websocket-0.11.1 wsproto-1.2.0

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

service = Service('/opt/homebrew/bin/chromedriver')
options = Options()
options.headless = True  # Run Chrome in headless mode
driver = webdriver.Chrome(service=service, options=options)

driver.get('https://www.google.com')
print(driver.title)
driver.quit()

Google

In [ ]:
canada_df['PMID'].to_csv('canada_pmid.csv', index=False, header=False)

In [ ]:
import os
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
import pandas as pd

# Load the PMIDs from the CSV file
df_data = pd.read_csv('canada_pmid.csv', header=None, names=['PMID'])

# Set up Chrome driver for macOS M1
# Adjust this path to where you placed the chromedriver
chrome_driver_path = "/opt/homebrew/bin/chromedriver"
# Replace with your desired download folder path
download_folder = "/Users/yumcoder/Desktop/pubmed/download"

service = Service(chrome_driver_path)
options = webdriver.ChromeOptions()

# Set the download folder for Chrome
prefs = {"download.default_directory": download_folder}
options.add_experimental_option("prefs", prefs)

# Initialize the WebDriver
driver = webdriver.Chrome(service=service, options=options)

try:
    for index, row in df_data.iterrows():
        pmid = row['PMID']
        pdf_filename = os.path.join(download_folder, f"{pmid}.pdf")
        if index > 10:
            break

        # Check if the file already exists
        if os.path.exists(pdf_filename):
            print(f"File for PMID {pmid} already exists, skipping download.")
            continue

        # Open the PubMed article page
        driver.get(f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/")

        # Wait for the page to load and the full-text links to be visible
        wait = WebDriverWait(driver, 10)

        # Wait for the full-text links container to be present
        wait.until(EC.presence_of_element_located(
            (By.CLASS_NAME, "full-text-links-list")))

        # Find all full-text links
        try:
            links = wait.until(EC.presence_of_all_elements_located(
                (By.XPATH, "//div[@class='full-text-links-list']/a")))

            # Debug: Print information about each link using textContent
            for link in links:
                link_text = link.get_attribute('textContent').strip()
                link_href = link.get_attribute('href')
                print(f"Link text: {link_text}")
                print(f"Link href: {link_href}")

            # Optionally click on a specific link (e.g., PMC link)
            for link in links:
                link_text = link.get_attribute('textContent').strip()
                if "Free PMC article" in link_text:
                    link.click()
                    break

        except NoSuchElementException:
            print(f"Full-text links not found for PMID {pmid}.")
            continue

        # Check if a new tab opened
        window_handles = driver.window_handles
        if len(window_handles) > 1:
            # Switch to the new tab
            driver.switch_to.window(window_handles[-1])
        else:
            print("No new tab detected, continuing in the current tab.")

        # Wait for the new page or current page to load the PDF link
        wait.until(EC.presence_of_element_located(
            (By.XPATH, "//a[contains(@href, '.pdf')]")))

        # Find the download PDF link (if available)
        try:
            pdf_link = driver.find_element(
                By.XPATH, "//a[contains(@href, '.pdf')]")

            # Debug: Print the PDF link
            print(f"Found PDF link: {pdf_link}")
            print(f"PDF URL: {pdf_link.get_attribute('href')}")

            # Get the URL of the PDF file
            pdf_url = pdf_link.get_attribute("href")

            # Mimic a real browser request by adding headers
            headers = {
                "User-Agent": driver.execute_script("return navigator.userAgent;"),
                "Referer": driver.current_url,
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
            }

            # Download the PDF file using requests with headers
            response = requests.get(pdf_url, headers=headers, stream=True)

            # Ensure the request was successful
            if response.status_code == 200:
                with open(pdf_filename, 'wb') as f:
                    for chunk in response.iter_content(chunk_size=1024):
                        if chunk:  # filter out keep-alive new chunks
                            f.write(chunk)
                print(f"Downloaded full text PDF to: {pdf_filename}")
            else:
                print(
                    f"Failed to download PDF for PMID {pmid}. Status code: {response.status_code}")

        except NoSuchElementException:
            print(f"PDF link not found for PMID {pmid}.")

finally:
    # Close the browser
    driver.quit()

File for PMID 28350526 already exists, skipping download.
File for PMID 28444633 already exists, skipping download.
File for PMID 28550657 already exists, skipping download.
File for PMID 28589480 already exists, skipping download.
File for PMID 28596271 already exists, skipping download.
Link text: Elsevier Science
Link href: https://linkinghub.elsevier.com/retrieve/pii/S0920-9964(17)30302-X
Link text: Elsevier Science
Link href: https://linkinghub.elsevier.com/retrieve/pii/S0920-9964(17)30302-X
No new tab detected, continuing in the current tab.

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.101)
Stacktrace:
0   chromedriver                        0x0000000100a090b8 cxxbridge1$str$ptr + 1887276
1   chromedriver                        0x0000000100a01794 cxxbridge1$str$ptr + 1856264
2   chromedriver                        0x000000010061082c cxxbridge1$string$len + 88524
3   chromedriver                        0x00000001005ebe50 core::str::slice_error_fail::he7b2aa4898bc357e + 3908
4   chromedriver                        0x0000000100679574 cxxbridge1$string$len + 517908
5   chromedriver                        0x000000010068bdd8 cxxbridge1$string$len + 593784
6   chromedriver                        0x0000000100649474 cxxbridge1$string$len + 321044
7   chromedriver                        0x000000010064a0e4 cxxbridge1$string$len + 324228
8   chromedriver                        0x00000001009d0a9c cxxbridge1$str$ptr + 1656336
9   chromedriver                        0x00000001009d54f8 cxxbridge1$str$ptr + 1675372
10  chromedriver                        0x00000001009b6980 cxxbridge1$str$ptr + 1549556
11  chromedriver                        0x00000001009d5ca8 cxxbridge1$str$ptr + 1677340
12  chromedriver                        0x00000001009a8690 cxxbridge1$str$ptr + 1491460
13  chromedriver                        0x00000001009f2af0 cxxbridge1$str$ptr + 1795684
14  chromedriver                        0x00000001009f2c6c cxxbridge1$str$ptr + 1796064
15  chromedriver                        0x0000000100a013c8 cxxbridge1$str$ptr + 1855292
16  libsystem_pthread.dylib             0x000000019c846f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000019c841d34 thread_start + 8

In [ ]:
import os
import ecdsa
import hashlib
import base58


def private_key_to_address(private_key_bytes):
    sk = ecdsa.SigningKey.from_string(private_key_bytes, curve=ecdsa.SECP256k1)
    vk = sk.verifying_key
    public_key_bytes = b'\x04' + vk.to_string()
    sha256_pk = hashlib.sha256(public_key_bytes).digest()
    ripemd160 = hashlib.new('ripemd160')
    ripemd160.update(sha256_pk)
    hashed_pk = ripemd160.digest()
    prefix = b'\x00' + hashed_pk
    checksum = hashlib.sha256(hashlib.sha256(prefix).digest()).digest()[:4]
    return base58.b58encode(prefix + checksum).decode()


# Brute-force loop (useless, but technically correct)
target = "1PMycacnJaSqwwJqjawXBErnLsZ7RkXUAs"
while True:
    pk = os.urandom(32)
    addr = private_key_to_address(pk)
    print("tes:", pk.hex())

    if addr == target:
        print("Match found!", pk.hex())
        break